### ISSUE TITLE
Buttons in sodium GUI become duplicated.

### ISSUE THREAD

**Issue by Kichura** [FlashyReese/sodium-extra-fabric#1]
When visiting the sodium page with this mod installed, Maxmizing the game's dialog box will cause the extra buttons to become duplicated.

The current workaround is to close the sodium page and then re-open it so that the duplicated buttons are gone.
![image](https://user-images.githubusercontent.com/68134602/101983259-35218d00-3c7a-11eb-90de-5e6e25769c94.png)

**Comment by FlashyReese** [comment]
Caused by lack of API to add pages into Sodium, mixing directly into Sodium has some odd behaviors.
