### ISSUE TITLE
Config option for cheaty stuff

### ISSUE THREAD

**Issue by Madis0** [FlashyReese/sodium-extra-fabric#10]
I suggest having a config option that hides the following options from the GUI:

- Brightness over 100
- Show time
- No overlays

This is for modpacks that would like the extra options but don't want to encourage people to cheat 🙂 
By "config option" I mean a default-disabled boolean in the JSON, it doesn't need a GUI toggle.

**Comment by FlashyReese** [comment]
I will look into it, I'm quite busy these past few days.

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> I suggest having a config option that hides the following options from the GUI:
> 
>     * Brightness over 100
> 
>     * Show time
> 
>     * No overlays
> 
> 
> This is for modpacks that would like the extra options but don't want to encourage people to cheat 🙂
> By "config option" I mean a default-disabled boolean in the JSON, it doesn't need a GUI toggle.

In addition tho, they should be enabled by default, and only disabled by modpacks.
