### ISSUE TITLE
Interface bug with Iris Shaders

### ISSUE THREAD

**Issue by DelofJ** [FlashyReese/sodium-extra-fabric#100]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.5

### Sodium version.

Iris 1.1.2 build 9

### What happened?

When I want to use Iris Shaders with Sodium Extra, a graphical bug appears where the tabs at the top of the screen are superimposed and difficult to access, which did not happen with the old interface of v0.3.3, and this bug appears from the new interface of v0.3.4
Please put the interface back as before, I think it was better organized especially with Iris Shaders

### Relevant log.

https://gist.github.com/DelofJ/5ae03eae6fcb36df4cce8452323cd51d

**Comment by FlashyReese** [comment]
[Here](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options) :)
