### ISSUE TITLE
[Feature Request] Option to toggle between Fast and Fancy leaves

### ISSUE THREAD

**Issue by SkyTheNerd** [FlashyReese/sodium-extra-fabric#103]
Fast leaves save a lot of fps but you have to use Fast graphics, so I think that an option for leaves would be pretty cool.

**Comment by Kichura** [comment]
Already added in DEV builds via 1.17.x of sodium,

[Commit for reference. 😛](https://github.com/CaffeineMC/sodium-fabric/commit/843b0f0469aed3196a33f6377563ac6ff99abbbc)
