### ISSUE TITLE
Allow the debug screen to refresh slower?

### ISSUE THREAD

**Issue by Kichura** [FlashyReese/sodium-extra-fabric#107]
When using OptiFine or canvas renderer (with **Steady Debug Screen** switch enabled); the debug screen becomes slow at refreshing debug screen which allows accuracy to be improved and allows FPS to be kept stable without having to refresh every frame.

Sodium on the other hand completely lacks this as it relays on the every-frame-refresh method instead which vanilla has, meaning accuracy is decreased [as discussed in one of the mods here](https://github.com/juliand665/Dynamic-FPS/issues/46) and can also sometimes decrease FPS entirely in specific machine units.

**Comment by Felix14-v2** [comment]
Now you can use [Exordium](https://modrinth.com/mod/exordium) (previously FasterGUI) to configure this.

**Comment by Kichura** [comment]
> Now you can use [Exordium](https://modrinth.com/mod/exordium) (previously FasterGUI) to configure this.

Seems nice to have but at the same time kinda uneasy to make use of so i rather wanna have this in sodium extras instead.

**Comment by FlashyReese** [comment]
Solved with https://github.com/FlashyReese/sodium-extra-fabric/commit/876fad6bc6b07397668d1f98bbdecf053b9bbda9.
