### ISSUE TITLE
[Suggestion] Option to remove enchant glint

### ISSUE THREAD

**Issue by andreasdc** [FlashyReese/sodium-extra-fabric#115]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.5

### Sodium version.

0.4.0 experimental

### What happened?

Enchant glint takes a lot of resources, option to disable it would be awesome. 

### Relevant log.

0

**Comment by randewd** [comment]
Yeah, that is true, and i tried to make a resource pack disabling the enchant glint, and it still lags.

**Comment by FlashyReese** [comment]
Sodium `0.4.9` optimizes this area of the game.
