### ISSUE TITLE
Crash on attempts to join any servers/worlds

### ISSUE THREAD

**Issue by Scarlaid** [FlashyReese/sodium-extra-fabric#116]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.6

### Sodium version.

0.3.3

### What happened?

Sodium Extra was working fine for me yesterday, until this morning it threw me a crash on attempts to join any server, even singleplayer

### Relevant logs

My lastest log: [https://pastebin.com/mMdATUss](url)
My crash report: [https://pastebin.com/F1k6iBRT](url)

Crash message: [https://imgur.com/a/OhPCTRC](url)
Files if the links are unusable
[2021-12-07-7.log.gz](https://github.com/FlashyReese/sodium-extra-fabric/files/7665342/2021-12-07-7.log.gz)
[crash-2021-12-07_10.22.51-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/7665343/crash-2021-12-07_10.22.51-client.txt)

**Comment by FlashyReese** [comment]
Your config file is corrupted, delete them and try again. They can be found at `.minecraft/config/`

**Comment by Scarlaid** [comment]
It worked, thanks.
