### ISSUE TITLE
Pitch Black 

### ISSUE THREAD

**Issue by GurunandanNadig** [FlashyReese/sodium-extra-fabric#118]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18

### Sodium Extra version.

0.3.7

### Sodium version.

0.4.0

### What happened?

![Minecraft_ 1 18 - Singleplayer 14-12-2021 01_51_32 PM](https://user-images.githubusercontent.com/96112787/145970986-56be2e22-a9ea-4044-ba26-ab8b47b2a449.png)
 
Pitch Black Bug 

### Relevant log.

![mods 14-12-2021 02_59_29 PM](https://user-images.githubusercontent.com/96112787/145971206-09b43090-33b2-4f67-96b6-51a1294c3f9e.png)

### Additional information.

please help i am not able to record video

**Comment by FlashyReese** [comment]
Does this occur without Sodium Extra?

**Comment by GurunandanNadig** [comment]
No

**Comment by GurunandanNadig** [comment]
> Does this occur without Sodium Extra?

No

**Comment by Felix14-v2** [comment]
Can confirm. I had the same problem even with new worlds until I reinstalled Sodium Extra. I thought it was a bug in the mod configs, but it turned out to be easier...

I just forgot to enable "light updates" option. @GurunandanNadig , make sure you have this option enabled.

**Comment by FlashyReese** [comment]
The option is enabled by default and is mostly used for huge redstone machines. 

I guess I will be updating the tooltip to prevent users from disabling it without knowing what it does.

**Comment by GurunandanNadig** [comment]
> Can confirm. I had the same problem even with new worlds until I reinstalled Sodium Extra. I thought it was a bug in the mod configs, but it turned out to be easier...
> 
> I just forgot to enable "light updates" option. @GurunandanNadig , make sure you have this option enabled.

Ok I'll Try

**Comment by GurunandanNadig** [comment]
> The option is enabled by default and is mostly used for huge redstone machines.
> 
> I guess I will be updating the tooltip to prevent users from disabling it without knowing what it does.

ok thank you for your help
