### ISSUE TITLE
Sodium extra options don't seem to fit on the screen. 

### ISSUE THREAD

**Issue by AryanShetty** [FlashyReese/sodium-extra-fabric#119]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.3.7

### Sodium version.

0.4.0 Alpha

### What happened?

The top level menu options eg. General, Quality, Performance and etc. Don't fit properly on the screen. The last button i can see if render. How can i fix this? I have asked for help in the sodium discord, and they said I'd have to come here.
![Screenshot (20)](https://user-images.githubusercontent.com/16573088/146820984-28f8397a-2c56-4336-960c-e650052fb063.png)

### Relevant log.

There is no log for this.

**Comment by Dr-B-Wisser** [comment]
I have the same issue, for now it seems as if changing the Gui scale helps to avoid the issue.

**Comment by DioEgizio** [comment]
Install Reese's Sodium Options, it should make things better
