### ISSUE TITLE
Thoughts: Cords and vanilla video settings screen

### ISSUE THREAD

**Issue by piemanau** [FlashyReese/sodium-extra-fabric#12]
Could you possibly add a coordinates option? It would be cool if it displayed similar to how the FPS counter is displayed. Any thoughts of adding them to the vanilla video settings screen? https://www.curseforge.com/minecraft/mc-mods/better-sodium-video-settings-button read the description and it will tell you what it does.

**Comment by FlashyReese** [comment]
Coordinates option sounds good. I'm not planning to add any toggles to vanilla video settings screen anytime soon.

**Comment by piemanau** [comment]
> Coordinates option sounds good. I'm not planning to add any toggles to vanilla video settings screen anytime soon.

Alright cool, when do you think you can work on it?

**Comment by FlashyReese** [comment]
Probably the weekend, no guarantees I have a bunch of university stuff going on.

**Comment by FlashyReese** [comment]
Closing this cause of https://github.com/FlashyReese/sodium-extra-fabric/commit/ca49f065435e9545512538900bef233acb50ffe1

**Comment by piemanau** [comment]
Sorry I saw this but forgot to say thank you!
