### ISSUE TITLE
When fog is set to "vanilla fog" it still touches fog

### ISSUE THREAD

**Issue by ShaneTRS** [FlashyReese/sodium-extra-fabric#122]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.3.7

### Sodium version.

0.4.0-alpha5+build.9

### What happened?

When fog is set to vanilla (default), other mods that interact with the fog still conflict. Sodium Extra takes priority with the one I tested (Tweakeroo), forcing fog to be enabled in all circumstances. 

My expectation would be: when the fog setting is set to vanilla, it's hands-off on Sodium Extra's end. All other mods would be able to interact with the fog free of disruption/interference.

### Relevant log.

No relevant log.

### Additional information.

Disabling the mixin for changing the fog does fix compatibility with other mods that interact with fog, but obviously breaks Sodium Extra's fog changes (which is fine in my case, but might not be for everyone?).

**Comment by FlashyReese** [comment]
Can you try this developer build out and tell me if this resolves this issue? https://github.com/FlashyReese/sodium-extra-fabric/suites/4783431081/artifacts/133580753

**Comment by ShaneTRS** [comment]
I just tested it out and it does resolve the issue, thanks!
Other mods interacting with fog work with Sodium Extra as long as it's set to "default"
