### ISSUE TITLE
Crash when using Sodium Extra with an external monitor

### ISSUE THREAD

**Issue by vyprestrike** [FlashyReese/sodium-extra-fabric#124]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.3.7

### Sodium version.

0.4.0 alpha 5

### What happened?

I was attempting to use Sodium Extra to downscale my resolution in fullscreen. On my 16:10 laptop, i was able to set a custom fullscreen resolution just fine. When I tried to set a custom resolution on my 21:9 monitor, the game crashed instantly and kept crashing on startup until I removed Sodium Extra from my mods folder and restarted the game on my laptop screen.

### Relevant logs

<removed>

### Additional information

![Desktop Screenshot 2022 01 05 - 14 46 59 39](https://user-images.githubusercontent.com/97193975/148281504-128b5cdd-6623-4b1d-a9f3-6590449b022a.png)

**Comment by FlashyReese** [comment]
Hello, can you also provide `.minecraft/logs/latest.log` please?

I have removed the heap dump provided as it contains your Minecraft account's access token.
