### ISSUE TITLE
[Feature Request] Smooth Lighting Level

### ISSUE THREAD

**Issue by Manamongods** [FlashyReese/sodium-extra-fabric#125]
100% smooth lighting is hard on my eyes, and the "Smooth Lighting Level" setting in optifine is really nice, and I'm missing it with sodium.

**Comment by FlashyReese** [comment]
This is a vanilla feature, there isn't a difference between `Minimum` and `Maximum` at least in Sodium, so it's just been a single toggle under `Quality > Smooth Lighting`.

**Comment by Manamongods** [comment]
From minecraft's wiki smooth lighting Minimum is just "an older version of the engine".
I'm requesting an equivalent to optifine's "Smooth Lighting Level" slider, where you can choose whatever ambient occlusion darkness you want (the name of the slider is not very accurate). 

For some examples, smooth lighting Maximum with 0% Smooth Lighting Level:
![Smooth lighting maximum 0% level](https://user-images.githubusercontent.com/45214197/183292774-136a54a8-cd96-49ee-96fd-113a6eb7a0fa.png)

Smooth lighting Maximum with 100% Smooth Lighting Level:
![Smooth lighting maximum 100% level](https://user-images.githubusercontent.com/45214197/183292778-af9eb401-1f73-4e9a-8c36-b6fbef9ce48e.png)

Smooth lighting Off:
![Smooth lighting off](https://user-images.githubusercontent.com/45214197/183292783-f2539d4d-0a5b-4e9e-be67-47138bb0dd56.png)

The slider in question:
![2022-08-07_15 22 58](https://user-images.githubusercontent.com/45214197/183292899-51773fb9-8b78-4b51-89f1-59e28deabb09.png)

**Comment by RaptaG** [comment]
Is this still planned?

**Comment by FlashyReese** [comment]
Likely not, the way sodium does smooth lighting is quite different.

**Comment by Kichura** [comment]
1.19.3 has also dropped the minimium smooth lighting system entirely as it was pointless to have and didn't actually function anymore as intended,

and instead they have chosen to convert it into a boolean instead where disabled means no smooth lighting and enabled means maxmium.

**Comment by Manamongods** [comment]
> Likely not, the way sodium does smooth lighting is quite different.

How so? Even though it's different surely it's still possible to do this though?

> 1.19.3 has also dropped the minimium smooth lighting system entirely as it was pointless to have and didn't actually function anymore as intended,
> 
> and instead they have chosen to convert it into a boolean instead where disabled means no smooth lighting and enabled means maxmium.

But this feature request is about ambient occlusion darkness, nothing to do with the difference between minimum/maximum smooth lighting?

**Comment by heladeradr** [comment]
I would like this issue to be reopened. The smooth lightning level/slider is not a vanilla feature, and doesn't have anything to do with the old minimum/maximum options
