### ISSUE TITLE
Feature Request: Fade-in Chunks

### ISSUE THREAD

**Issue by Boobies** [FlashyReese/sodium-extra-fabric#126]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.x

### Sodium Extra version.

N/A

### Sodium version.

N/A

### What happened?

Would be nice to have a feature for fade-in chunks like Bedrock Edition. There is a Java Edition mod for this but it was never updated for 1.18.x. Here it is: https://www.curseforge.com/minecraft/mc-mods/fade-in-chunks

Seems like Sodium Extra would be a great place for this feature.

### Relevant log.

N/A

**Comment by FlashyReese** [comment]
https://github.com/Johni0702/fade-in-chunks/issues/15#issuecomment-907479892

It would be better off updated than ported into this mod.

**Comment by Felix14-v2** [comment]
> It would be better off updated than ported into this mod.

So, it looks like Rubidium Extra did it for Forge. Fabric was left with nothing...
