### ISSUE TITLE
Two variables are missing

### ISSUE THREAD

**Issue by Disguys** [FlashyReese/sodium-extra-fabric#130]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.3.8

### Sodium version.

0.4.0-alpha6

### What happened?

Apparently, these variables are displayed this way because they are not in the folders with the languages into which the mod is translated.
![image](https://user-images.githubusercontent.com/60795989/149555240-11eddf72-5d3d-4386-b18e-c68051580625.png)

### Relevant log.

-

**Comment by FlashyReese** [comment]
Resolved in https://github.com/FlashyReese/sodium-extra-fabric/commit/185f490f33a50d7afa47fd99ef3ad85fad8ca1c0. Will be present in the next release.
