### ISSUE TITLE
Crashing after updating to latest Sodium Extra version

### ISSUE THREAD

**Issue by HYPExMon5ter** [FlashyReese/sodium-extra-fabric#136]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.3.9

### Sodium version.

0.4.0-alpha6+build.14

### What happened?

I updated to the latest Sodium extra version and my game started crashing - narrowed it down to this by disabling mods until it didn't crash anymore.

### Relevant logs

[crash report](https://github.com/FlashyReese/sodium-extra-fabric/files/7940347/crash-2022-01-26_04.13.38-client.txt)
[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/7940350/latest.log)

**Comment by FlashyReese** [comment]
Looking at the crash log it says `thonkutils-coords` is at fault.

> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for thonkutil-coords-v1.mixins.json:CoordOverlayMixin during activity: [Attach method -> renderCoords(Lnet/minecraft/class_4587;)V]

The latest log says it's completely fine but the `lwjgl.dll` failed to load, you probably need to create a new instance.

Can you test this with only Sodium and Sodium Extra?

**Comment by HYPExMon5ter** [comment]
Yeah I seen that thonk utils stack trace however it was working fine previous update and thonk utils has not updated - only this mod has. I will test them alone this evening

**Comment by HYPExMon5ter** [comment]
Just got around to testing, loads fine with just sodium and sodium extra

**Comment by FlashyReese** [comment]
Perhaps try creating a new instance with all the same mods, and try without `thonkutils-cord`?

**Comment by HYPExMon5ter** [comment]
I’m pretty sure thonk utils is a dependency for another mod so I’ll have to figure out what depends on it and remove that as well. I’m out of town for
the next like 5 days or so but I will test asap

**Comment by B00MxHartShotx** [comment]
> Perhaps try creating a new instance with all the same mods, and try without `thonkutils-cord`?

this is for the goblin traders and end goblin traders mods for fabric
i updated the modpack for my server/client files and just spent two hours trying to diagnose why none of us could get online. after searching logs, crash reports, and google, i started with the previous version of my modpack and started installing mods one by one. each was fine until i updated sodium extra. the last version that you had out is loading fine and i'll be using it until there is further update on this issue

**Comment by FlashyReese** [comment]
> > Perhaps try creating a new instance with all the same mods, and try without `thonkutils-cord`?
> 
> this is for the goblin traders and end goblin traders mods for fabric i updated the modpack for my server/client files and just spent two hours trying to diagnose why none of us could get online. after searching logs, crash reports, and google, i started with the previous version of my modpack and started installing mods one by one. each was fine until i updated sodium extra. the last version that you had out is loading fine and i'll be using it until there is further update on this issue

Are there any relevant logs you can provide for me?

**Comment by chungyentsai** [comment]
> 
Hi hi, i have some problems too, i dont know if is caused by sodium extra, if you can guide me on this it could be awesome.
thanks
[minecraft-exported-logs-2022-02-13T21-33-04.log](https://github.com/FlashyReese/sodium-extra-fabric/files/8057057/minecraft-exported-logs-2022-02-13T21-33-04.log)

**Comment by StuffByJimm** [comment]
I've had a similar experience and have narrowed it down to Sodium Extra as [well](https://pastebin.com/5tkkFaqs).

**Comment by ZielFos** [comment]
I Try  The Lastest Version ( 1.18.1-0.4.0 ) And Then, when i destroy a block, the block that i have destroyed turns black or something like a glitch, Plis I Dont Know What To Do

**Comment by vrgtics** [comment]
just for suggestion here for you #149
