### ISSUE TITLE
Glitch biome blend in 1.18?

### ISSUE THREAD

**Issue by BoraiperXD** [FlashyReese/sodium-extra-fabric#137]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.3.9

### Sodium version.

0.4.0 alpha6

### What happened?

The biome blend is broken & I only used disabled or zero level even I tested on new worlds for biomes still incorrect color biome & glitchy or buggy in 1.18 causes problem like generates new biomes underground & terrain I think. I hope anyone experienced or saw a bug like me & fix a bug please.

### Relevant log.

[mylog.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/7941438/mylog.txt)

### Additional information.

![2022-01-26(1)](https://user-images.githubusercontent.com/80188692/151157126-1e084897-e846-4fc9-b740-c4142dc09b86.png)
![2022-01-26(2)](https://user-images.githubusercontent.com/80188692/151157187-64c545ea-79f3-43c3-aac3-d1454792fbc6.png)

**Comment by FlashyReese** [comment]
This is a Sodium bug, I believe.

Sodium Extra only touches biome colors when you have the `Details>Biome Colors` disabled.
