### ISSUE TITLE
Unable to create and load single player worlds 

### ISSUE THREAD

**Issue by YukiSnowYue** [FlashyReese/sodium-extra-fabric#139]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

sodium-extra-mc1.17.1-0.3.9

### Sodium version.

sodium-fabric-mc1.17.1-0.3.4+build.13

### What happened?

When I create a world it gets stuck at 9% and won't keep loading
(At the same time, it is impossible to enter the created world, and there is no problem in multiplayer)
The world can be created normally after removing the sodium extra
There are no errors in the log 

### Relevant log.
[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/7945347/latest.log)

### Additional information.

![image](https://user-images.githubusercontent.com/73242379/151239530-9d6c3da4-65d7-4e6a-85a8-cc931f44489e.png)
![image](https://user-images.githubusercontent.com/73242379/151239551-28656462-b3d4-4445-a636-04d652405194.png)

**Comment by FlashyReese** [comment]
Do you have `Render > Light Updates` turned off by any chance?
