### ISSUE TITLE
'Render tab>Light Updates' issus / don't uncheck this box.

### ISSUE THREAD

**Issue by vrgtics** [FlashyReese/sodium-extra-fabric#149]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.3.9

### Sodium version.

0.4.0

### What happened?

I saw this.. and have a video for full describe down below.
![Screenshot (63)](https://user-images.githubusercontent.com/99676066/153910273-cd2eb57c-c453-47d5-b3b9-01d20fa4549d.png)

https://user-images.githubusercontent.com/99676066/153911080-ef5c00e9-a009-47a7-b952-0eacaff44f9a.mp4

in case that you couldn't see it well what's happening,
here some screenshot:
![Screenshot (60)](https://user-images.githubusercontent.com/99676066/153915176-3612457b-b07b-4ac2-841f-f27a4e522698.png)
_(as you can see the brightness is already set to Bright 100%, but if Light Updates 'off' I need to use 'boosted-brightness' mod to set it maximum 1200% brightness to see actual like normal 100% brightness)_
![Screenshot (61)](https://user-images.githubusercontent.com/99676066/153915185-8682f1b5-9388-44cd-9656-efe749c868f8.png)
![Screenshot (63)](https://user-images.githubusercontent.com/99676066/153915204-0d2393b5-f2ee-47ce-91e5-a0c5071f3401.png)

### Relevant log.

[tehlatest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/8062713/latest.log)

**Comment by FlashyReese** [comment]
It does what it says in the title of the toggle.
