### ISSUE TITLE
Sodium Extra messes up GUI scale, makes everything looks pixelated.

### ISSUE THREAD

**Issue by ultra-black** [FlashyReese/sodium-extra-fabric#150]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.3.9

### Sodium version.

0.4.0-alpha6+build.14

### What happened?

After Installing the mod, you notice that your GUI scale gets messed up, you fix it, then you realise that the sizes changed, so you just mess around with it until you get something that matches you last GUI Scale. Opening the settings in sodium you see all the new features, now if you join Singleplayer/Multiplayer. You notice your world looks pixelated like some low-quality image. I removed the mod and restarted minecraft and then everything came back normally. 

**Im on macOS and most issues seemed to match mine but never said my issue.
I even tried to go to extra and disable that feature but nothing seemed to happen.**

### Relevant log.

[Logs for Sodium-Extra](https://gist.github.com/hypixelsweat/8eda9283645b29da97933095da4aed35)

### Additional information.

With Sodium Extra (Pixalated):
[With Sodium Extra Video](https://www.dropbox.com/s/rj3ro8sdxgzfzqf/pixalated%3Asodiumextra.mov?dl=0
)
Without Sodium Extra (Normal):
[Without Sodium Extra Video](https://www.dropbox.com/s/qkegloqnu2o46x7/pixalated%3Awithoutsodiumextra.mov?dl=0)

> **_Please ignore the FPS lag, it doesn't do that. Its just that I have too many apps open and running._**
> **_Also Due to how Dropbox handles compression, you not see much details._**

**Comment by FlashyReese** [comment]
For performance reasons 'Extras > Reduce Resolution on macOS' is enabled by default. You will have a side effect of breaking 'Reese's Sodium Options' if you disable it.

Unfortunately I have figure out how to fix the issue because I don't own a Mac.

**Comment by ultra-black** [comment]
> For performance reasons 'Extras > Reduce Resolution on macOS' is enabled by default. You will have a side effect of breaking 'Reese's Sodium Options' if you disable it.
> 
> Unfortunately I have figure out how to fix the issue because I don't own a Mac.

Good news and bad news.
I was about to stay that, and I restarted and removed retINO and it works.

Bad news
Same thing. It messes up Reese's Sodium Options

**Comment by ultra-black** [comment]
There is now a new issue, lag spikes.
????

**Comment by FlashyReese** [comment]
Well without it enabled you are rendering twice your resolution.

**Comment by ultra-black** [comment]
It seems like I will close this issue since it's my fault for not realizing I have retiNO and forgetting to restart my game.
Thanks.

**Comment by FlashyReese** [comment]
Hello, do you mind helping me debug `Reese's Sodium Options` with `Sodium`?

[build-artifacts.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/8094273/build-artifacts.zip)

This build is an attempt to fix the broken viewport on macOS.

**Comment by ultra-black** [comment]
Yeah sure.

**Comment by ultra-black** [comment]
Yes it works. 😃
<img width="2560" alt="nice!" src="https://user-images.githubusercontent.com/97588864/154764617-1f2a3c92-8a01-4b43-9b40-7fc962f122a3.png">

**Comment by FlashyReese** [comment]
Thanks

**Comment by ultra-black** [comment]
> There is now a new issue, lag spikes. ????

Last reply, to anyone looking at this its just one of my mods causing this. This has nothing to do with Sodium extra
