### ISSUE TITLE
Incompatibility: Enhanced Celestials

### ISSUE THREAD

**Issue by Sunconure11** [FlashyReese/sodium-extra-fabric#154]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.4.0

### Sodium version.

Sodium mc1.18.1-0.4.0-alpha6

### What happened?

After updating, the mod seemed to start throwing a crash

### Relevant logs

https://pastebin.com/NSCuQLRf

**Comment by FlashyReese** [comment]
Can you provide a screenshot of your mod list or the mod pack you are using?

**Comment by Sunconure11** [comment]
I have a vague idea for the mod at fault, could you investigate this mod? https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric

**Comment by FlashyReese** [comment]
Looks like just a minor incompatibility, you can temporarily work around this by adding `mixin.sun_moon=false` to `./minecraft/config/sodium-extra.properties`

**Comment by janitor-raus** [comment]
Here to also confirm this bug, as well as the suggested workaround taking care of it.
