### ISSUE TITLE
Incompatibility: Crimson Moon

### ISSUE THREAD

**Issue by ZeldasWetDream** [FlashyReese/sodium-extra-fabric#157]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.4.0

### Sodium version.

Sodium mc1.18.1-0.4.0-alpha6

### What happened?

I updated this mod to the latest update and started crashing upon booting up. 

As far as I can tell it has something to do with the sun and moon options that were added.

### Relevant logs

Both logs are uploaded on one page.

https://paste.gg/p/anonymous/f2a2174cc2c74fd5b530f9cf36dd1b06 

### Additional information

_No response_ I did check all my other mods that I recently updated. And through process of elimination I found this mod to cause the crash

**Comment by ZeldasWetDream** [comment]
I checked the closed issues and found out what was wrong. 

Adding this to the properties file fixed it. "mixin.sun_moon=false"

**Comment by ThinkWithPbody** [comment]
> Adding this to the properties file fixed it. "mixin.sun_moon=false"

Hello, I'm facing the same problem. How do you locate this properties file?

**Comment by FlashyReese** [comment]
https://github.com/FlashyReese/sodium-extra-fabric/issues/154#issuecomment-1046054272

**Comment by FlashyReese** [comment]
This [build](https://github.com/FlashyReese/sodium-extra-fabric/suites/5388289291/artifacts/169577953) should fix this bug
