### ISSUE TITLE
I Try  The Lastest Version ( 1.18.1-0.4.0 ) And Then, when i destroy a block, the block that i have destroyed turns black or something like a glitch, Plis I Dont Know What To Do

### ISSUE THREAD

**Issue by ZielFos** [FlashyReese/sodium-extra-fabric#158]
I Try  The Lastest Version ( 1.18.1-0.4.0 ) And Then, when i destroy a block, the block that i have destroyed turns black or something like a glitch, Plis I Dont Know What To Do

_Originally posted by @ZielFos in https://github.com/FlashyReese/sodium-extra-fabric/issues/136#issuecomment-1051542363_

**Comment by FlashyReese** [comment]
Closing this issue as it does not follow the bug format.
