### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Madis0** [FlashyReese/sodium-extra-fabric#16]
Sodium [has been translated for a while](https://github.com/CaffeineMC/sodium-fabric/issues/44), but the release versions have not gotten the translation support just yet. Wonder how hard would it be to backport that via Sodium Extra?
Additionally, it would then make sense to make Sodium Extra's options translatable as well.

**Comment by FlashyReese** [comment]
I'm not looking forward on backporting PRs from Sodium to Sodium Extra, MrMangoHands has mentioned that he wants to get that merged as soon as possible. It's just a manner of time(despite being a long time). As for Localization for Sodium Extra, I still need to wait until https://github.com/CaffeineMC/sodium-fabric/pull/517 is merged, I don't want to be hacking at the GUI code.

**Comment by Sanluli36li** [comment]
Now that sodium and extra support localization, maybe it should provide an entrance to contribute to the localization of sodium-extra?

**Comment by FlashyReese** [comment]
Yes, but before that happens I would like to formalize these translations first.

**Comment by FlashyReese** [comment]
I will be accepting PRs for translations.
