### ISSUE TITLE
options are not visible properly

### ISSUE THREAD

**Issue by EGOIST1372** [FlashyReese/sodium-extra-fabric#164]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.2

### Sodium version.

0.4.1

### What happened?

options are not visible properly
in this screenshot top right corner options are not visible
![image](https://user-images.githubusercontent.com/86555131/157947100-89f60008-0cac-4884-825b-404de66135fc.png)
in this one options are going out of screen
![image](https://user-images.githubusercontent.com/86555131/157947187-f8141efa-6a60-4678-9512-3ded8d3684b9.png)
hmmmmm
![image](https://user-images.githubusercontent.com/86555131/157947437-acd9e35a-a640-4bbe-baa7-ddda625f6fcc.png)

### Relevant log.

none

### Additional information.

4k display
GUI scale 8x

**Comment by EGOIST1372** [comment]
it get fix by [Reese's Sodium Options](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
![image](https://user-images.githubusercontent.com/86555131/157949276-21dac328-c933-453b-8047-2970280039ba.png)


but there is no dependency in main description page. yeah there is one but in relation page and people tend to not look there.
I keep it open so if there is anything beside the dependency that you need say and if not you can close it :D

**Comment by FlashyReese** [comment]
![image](https://user-images.githubusercontent.com/30311066/158932129-7deee9b3-0ba2-4e37-bf3e-381790d074a8.png)
Implemented in with https://github.com/FlashyReese/sodium-extra-fabric/commit/2a375833ccad0c43519bf3cff8ad69acce1a0fc8.

Feedback is appreciated :)
