### ISSUE TITLE
Resse's Sodium Options Crashes with SSPB

### ISSUE THREAD

**Issue by SafeOfArsenal** [FlashyReese/sodium-extra-fabric#165]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2

### Sodium Extra version.

1.4.2

### Sodium version.

0.4.1+build.15

### What happened?

Crashes when you try to change the settings.

### Relevant log.

it does not work

**Comment by FlashyReese** [comment]
Closing as it's not in the proper issue tracker and it must be fixed on sspb's end. https://github.com/FlashyReese/reeses-sodium-options/issues/31#issuecomment-1064425079
