### ISSUE TITLE
GPU Hard Crash on Linux with amdgpu drivers

### ISSUE THREAD

**Issue by zack-emmert** [FlashyReese/sodium-extra-fabric#168]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.16.5

### Sodium Extra version.

0.4.2

### Sodium version.

0.2.0

### What happened?

I'm running into graphical corruption issues when running custom 1.16.5 modpack I'm putting together which cause the entire system to freeze, necessitating a hard reboot of the entire machine. I can start up the game, play for about a minute or two, then my monitor briefly loses signal, before visuals return looking like [this](https://i.imgur.com/s9eYdSa.jpeg). At this point, the system requires a hard reboot to restore functionality. I can only reproduce this with Sodium and Sodium Extras installed. I was able to switch to a different tty for the purpose of extracting a dmesg log.

### Relevant logs

[dmesg.log](https://github.com/FlashyReese/sodium-extra-fabric/files/8328393/dmesg.log)

### Additional information

I'm running fully updated Arch Linux with an AMD RX 580 GPU. I've observed this issue on both Wayland and X.org, with both linux and linux-lts kernels with systemd-based initramfs, and with both mesa and mesa-git packages.

I initially discovered this issue using the Forge port Magnesium Extras, however I can confirm the issue is also present under Sodium Extras.

**Comment by FlashyReese** [comment]
> I initially discovered this issue using the Forge port Magnesium Extras, however I can confirm the issue is also present under Sodium Extras.

Magnesium Extras is a completely different mod, it is not a port of Sodium Extra. As for Sodium Extra, it is very unlikely for Extra to cause the game to hang using its current codebase. You might be looking at an issue with Sodium itself not playing nicely with drivers or possibly a bug with Sodium 0.2.0 itself.

Edit: Additionally I'm not affiliated with the developer/developers of Magnesium Extras.
