### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by azurenekowo** [FlashyReese/sodium-extra-fabric#169]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.2

### Sodium version.

0.4.1 build15

### What happened?

Whenever I fire up Minecraft w/ Sodium extra the game just crashes.

### Relevant logs

MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.91.48, 13.225.91.42, 13.225.91.37, 13.225.91.43]

session.minecraft.net resolves to:
    [52.205.99.166, 3.211.39.224, 3.224.239.34]

textures.minecraft.net resolves to:
    [216.137.37.62, 216.137.37.93, 216.137.37.77, 216.137.37.79]

api.mojang.com resolves to:
    [13.225.94.40, 13.225.94.28, 13.225.94.82, 13.225.94.25]

Minecraft folder is:
E:/Minecraft/MultiMC/instances/1.18.2/.minecraft

Java path is:
C:/Program Files/Zulu/zulu-17/bin/javaw.exe

Checking Java version...
Java is version 17.0.2, using 64-bit architecture, from Azul Systems, Inc..

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  E:/Minecraft/MultiMC/instances/1.18.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  E:/Minecraft/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  E:/Minecraft/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  E:/Minecraft/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  E:/Minecraft/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  E:/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  E:/Minecraft/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  E:/Minecraft/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  E:/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  E:/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  E:/Minecraft/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  E:/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  E:/Minecraft/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  E:/Minecraft/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  E:/Minecraft/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  E:/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  E:/Minecraft/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  E:/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  E:/Minecraft/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  E:/Minecraft/MultiMC/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  E:/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  E:/Minecraft/MultiMC/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  E:/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  E:/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  E:/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  E:/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  E:/Minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  E:/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  E:/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  E:/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  E:/Minecraft/MultiMC/libraries/net/fabricmc/intermediary/1.18.2/intermediary-1.18.2.jar
  E:/Minecraft/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  E:/Minecraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar
  E:/Minecraft/MultiMC/libraries/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
  E:/Minecraft/MultiMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  E:/Minecraft/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  E:/Minecraft/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  E:/Minecraft/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  E:/Minecraft/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  E:/Minecraft/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  E:/Minecraft/MultiMC/libraries/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar
  E:/Minecraft/MultiMC/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  E:/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  E:/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-windows.jar

Mods:
  [❌] c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar (disabled)
  [✔️] fabric-api-0.48.0+1.18.2
  [❌] ferritecore-4.2.0-fabric.jar (disabled)
  [❌] indium-1.0.2+mc1.18.2.jar (disabled)
  [❌] krypton-0.1.9.jar (disabled)
  [❌] lazydfu-0.1.2.jar (disabled)
  [❌] lithium-fabric-mc1.18.2-0.7.9.jar (disabled)
  [❌] modmenu-3.1.0.jar (disabled)
  [✔️] sodium-extra-mc1.18.2-0.4.2-sources
  [✔️] sodium-fabric-mc1.18.2-0.4.1+build.15
  [❌] starlight-1.0.2+fabric.89b8d9f.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir E:/Minecraft/MultiMC/instances/1.18.2/.minecraft --assetsDir E:/Minecraft/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 11424

Using onesix launcher.

[20:42:14] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[20:42:14] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) ${version} recommends version 1.4.2 or later of reeses-sodium-options, which is missing!
	 - You should install version 1.4.2 or later of reeses-sodium-options for the optimal experience.
[20:42:14] [main/INFO]: Loading 48 mods:
	- fabric 0.48.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.2+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.3+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.2+2540745460 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- java 17
	- minecraft 1.18.2
	- org_joml_joml 1.10.2 via sodium
	- sodium 0.4.1+build.15
	- sodium-extra ${version}
[20:42:14] [main/WARN]: Mod `sodium-extra` (${version}) does not respect SemVer - comparison support is limited.
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod sodium-extra
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:487)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 8 more
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:485)
	... 11 more
Exiting with -1
Process exited with code -1.

**Comment by FlashyReese** [comment]
You downloaded the source file of the mod, download the one that doesn't end with `source` in its name.

**Comment by azurenekowo** [comment]
@FlashyReese it worked, thanks man. _I shouldn't trust Modrinth release that much, lol_

**Comment by FlashyReese** [comment]
I'm unsure why Modrinth places it's primary file at the bottom.
