### ISSUE TITLE
Latest version breaks compatibly with boosted brightness mod

### ISSUE THREAD

**Issue by RangoMcRoony** [FlashyReese/sodium-extra-fabric#17]
Particularly the brightness slider does not go above 100% since the lastest update. It worked fine on the previous version of sodium extra so something must have changed here. With boosted brightness you can also press "b" to go to maximum brightness. This still works it's just the brightness slider that broke

**Comment by FlashyReese** [comment]
The toggle is hidden by default you can go into the config `.minecraft/config/sodium-extra-options.json` and change `"hide_cheats": false`

**Comment by RangoMcRoony** [comment]
Thanks
