### ISSUE TITLE
Support for Emissive Textures

### ISSUE THREAD

**Issue by ChristopherHaws** [FlashyReese/sodium-extra-fabric#176]
Would it be possible to add support for emissive textures, similar to OptiFine's emissive textures feature?

Specifically, I would like to be able to use this with Sodium (i.e. without OptiFine):
https://www.curseforge.com/minecraft/texture-packs/emissive-ores-1-17

**Comment by DragonEggBedrockBreaking** [comment]
The developer of a mod called Continuity, which currently adds support for connected textures, is currently adding emissive texture support to his mod. It is not completed yet, but you can join his discord for progress.

**Comment by ChristopherHaws** [comment]
For anyone interested, here is the issue in Continuity's backlog: https://github.com/PepperCode1/Continuity/issues/7
