### ISSUE TITLE
Cannot open Video setting with sodium extras installed

### ISSUE THREAD

**Issue by offbeat-stuff** [FlashyReese/sodium-extra-fabric#180]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.3

### Sodium version.

0.4.1

### What happened?

I am not able to open video settings with sodium extras installed. Everything works ok with the mod installed.

### Relevant log.

![2022-04-04_05 39 47](https://user-images.githubusercontent.com/34603072/161481638-5dddcebd-6af8-4421-8ed4-ee3b61843754.png)
[latest-world-join.log](https://github.com/FlashyReese/sodium-extra-fabric/files/8407011/latest-world-join.log)
[console-output.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/8407012/console-output.txt)
[latest-no-world-join.log](https://github.com/FlashyReese/sodium-extra-fabric/files/8407013/latest-no-world-join.log)
- My config

**Comment by offbeat-stuff** [comment]
I also have disabled sodium chunk rendering

**Comment by FlashyReese** [comment]
It looks like you are using a custom fork of Sodium, the build numbers don't match Sodium's releases. I have no way of debugging this as you are also running it via PojavLauncher which is not officially supported.

**Comment by offbeat-stuff** [comment]
I am using this https://github.com/CaffeineMC/sodium-fabric/actions/runs/2041400661

**Comment by offbeat-stuff** [comment]
The latest-no-world-join.log has the error message from sodium-extra

**Comment by offbeat-stuff** [comment]
@FlashyReese This line is giving the error https://github.com/FlashyReese/sodium-extra-fabric/blob/a7f33ab6fac6b5933fac93c5fddc3552c7546111/src/main/java/me/flashyreese/mods/sodiumextra/client/gui/options/control/SliderControlExtended.java#L23 according to the log

**Comment by offbeat-stuff** [comment]
Actually there seems to be a series of errors in the log

**Comment by FlashyReese** [comment]
I ran into this issue on PojavLauncher previously, the code path breaks somehow when using PojavLauncher even though it's the code is identical to [Sodium's SliderControl](https://github.com/CaffeineMC/sodium-fabric/blob/e6288d68b2f26300e2be646f0553ca27a9f1549c/src/main/java/me/jellysquid/mods/sodium/client/gui/options/control/SliderControl.java#L18).

Unfortunately, I can't just remove it for sake of using it with Pojav; but if you are knowledgeable with Java and know how to compile it yourself.

You can replace the following with Sodium's SliderControl.
https://github.com/FlashyReese/sodium-extra-fabric/blob/35d7e161e471d9a6e9795cc5dd8c50e2f14ea4b0/src/main/java/me/flashyreese/mods/sodiumextra/client/gui/SodiumExtraGameOptionPages.java#L269

https://github.com/FlashyReese/sodium-extra-fabric/blob/b577ad33c9affafb086178bafe28965b574fbe69/src/main/java/me/flashyreese/mods/sodiumextra/mixin/sodium/resolution/MixinSodiumGameOptionPages.java#L38

**Comment by offbeat-stuff** [comment]
Probably this gave the error
https://github.com/FlashyReese/sodium-extra-fabric/blob/b577ad33c9affafb086178bafe28965b574fbe69/src/main/java/me/flashyreese/mods/sodiumextra/mixin/sodium/resolution/MixinSodiumGameOptionPages.java

**Comment by FlashyReese** [comment]
You can also disable that mixin via `.minecraft\config\sodium-extra.properties` and adding `mixin.sodium.resolution=false`

**Comment by offbeat-stuff** [comment]
mixin.sodium.resolution=false
Did it thanks

**Comment by offbeat-stuff** [comment]
Sorry Didnt read your message until now because I did not refresh the page and your messages did not show up.
