### ISSUE TITLE
[Feature request] Toggle/Adjust Beacon Beam

### ISSUE THREAD

**Issue by Felix14-v2** [FlashyReese/sodium-extra-fabric#181]
Even with Sodium installed, the beacon beams have a significant impact on FPS. For example, in my case, 50 activated beacons reduce FPS by 27% if the beams are not colored in any color, and by 87% if 10 layers of glass are used for coloring.

I suggest adding an option to switch the visibility of the beams or a slider to adjust their height. At the moment, the beam is visible up to a height of 1080 blocks, which greatly affects FPS. In 1.16.5 and below, the maximum beam height was 256 blocks and did not have such a disastrous effect, so even a simple possibility of adjusting the beam height between these values or just disabling them would be very useful.

**Comment by FlashyReese** [comment]
~~I'm currently implementing this feature, assuming we can adjust the beacon beam height. What would be the optimal minimum number?~~

Edit: I have just made it a toggle since adjusting the height on the beacon beam does in a way affect achievements.

**Comment by Felix14-v2** [comment]
> adjusting the height on the beacon beam does in a way affect achievements

It's sad, maybe in the future?

> What would be the optimal minimum number?

Imho, at least 128 blocks (≈60b beam height, based on the average terrain level). This allows the player to keep the visibility of the beam at low rendering distance, and at the same time the beam remains a beam.
The problem is different – worlds with custom dimensions can have a depth (and height) of more than 2000 blocks, so a good implementation would be to calculate the minimum and maximum values dynamically when connecting to the world and receiving data on the height of the chunk.
Anyway, if it's so hard to implement, the game really isn't worth the candle.

**Comment by FlashyReese** [comment]
> at least 128 blocks

Any beacon above 128 won't render, that's the problem I have to deal with.

> good implementation would be to calculate the minimum and maximum values dynamically

I'm not able to achieve this using Sodium's GUI library.

Edit: Hence why I have settled with a simple toggle, perhaps this problem can be tackled another time.
