### ISSUE TITLE
Missing sodium extra options

### ISSUE THREAD

**Issue by BoraiperXD** [FlashyReese/sodium-extra-fabric#182]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

minecraft 1.18.2

### Sodium Extra version.

sodium-extra-mc1.18.2-0.4.3 with reese's sodium options

### Sodium version.

sodium-fabric-mc1.18.2-0.4.1+build.15

### What happened?

![missing_sodium_options](https://user-images.githubusercontent.com/80188692/161930829-b9e5c8c1-494a-4c95-9ef4-a5b76367a864.png)

Please fix this small bug in the latest version because I can't see it and it's missing from the sodium extra settings except for the Iris Shaders menu. Here's a screenshot also to prove it. But it only works in the config folder in sodium-extra-options I changed. I believe Reese's Sodium Options is an issue. Thank you.

### Relevant log.

[mylatestlog.log](https://github.com/FlashyReese/sodium-extra-fabric/files/8425047/mylatestlog.log)

**Comment by 7777777-4547** [comment]
Try to update RSO version 1.4.2？

**Comment by FlashyReese** [comment]
Reese's Sodium Options underwent some changes recently for better mod compatibility, you update to the latest version which is `1.4.2` at the time of writing. Thank you :)

**Comment by BoraiperXD** [comment]
> Try to update RSO version 1.4.2？

Oh i forgot to put RSO version it is 1.4.2 didn't work idk why still missing only works in config file too lazy to change and edit settings...

**Comment by BoraiperXD** [comment]
UPDATE: SORRY i messed up and illooked in folder mods it was RSO 1.4.1 i'm so stupid.. (what's wrong with me)
