### ISSUE TITLE
[Suggestion] additional features

### ISSUE THREAD

**Issue by amongusenjoyer69** [FlashyReese/sodium-extra-fabric#188]
is it possible to add support to the features that optifine has over sodium? (eg dynamic lights, better grass, connected textures etc.)
have seen other mods that provide these features in sodium but id like to see them all in sodium extra

**Comment by FlashyReese** [comment]
No, I will not be adding these mentioned features to the Sodium Extra. It's just extra work to maintain features that other mods already provide. It's easier to remove a mod breaking 1 feature than a mod that breaks 50 of your features.
