### ISSUE TITLE
ITS LIKE NOT COMPATIBLE WITH IRIS!

### ISSUE THREAD

**Issue by SZASUKE10** [FlashyReese/sodium-extra-fabric#189]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.16.5

### Sodium Extra version.

0.4.3

### Sodium version.

0.2.0

### What happened?

IT CRASHED WHEN IRIS IS INSTALLED

### Relevant log.

d

**Comment by DragonEggBedrockBreaking** [comment]
Please add a crash report or log, or you cannot be helped.

**Comment by Sparib** [comment]
I had issues with Iris as well. [This pastebin](https://pastebin.com/Rw4nAEPQ) has the errors that are thrown immediately after enabling a shader, and the final `[Render thread/INFO]` error is printed until the shader is disabled.

**Comment by FlashyReese** [comment]
> I had issues with Iris as well. [This pastebin](https://pastebin.com/Rw4nAEPQ) has the errors that are thrown immediately after enabling a shader, and the final `[Render thread/INFO]` error is printed until the shader is disabled.

Sodium Extra doesn't actually touch any shaders, it seems more of an unsupported uniform on Iris's end. Is this reproducible without Sodium Extra installed?

**Comment by DragonEggBedrockBreaking** [comment]
> I had issues with Iris as well. [This pastebin](https://pastebin.com/Rw4nAEPQ) has the errors that are thrown immediately after enabling a shader, and the final `[Render thread/INFO]` error is printed until the shader is disabled.

Those look like issues with Iris not supporting custom uniforms yet…
