### ISSUE TITLE
[Feature Request] 32+ Render Distance

### ISSUE THREAD

**Issue by Julienraptor01** [FlashyReese/sodium-extra-fabric#192]
Could you add ability to go past vanilla 32 chunk render distance like in OF ?
This is being rejected by sodium but sodium extra is "Features that shouldn't be in Sodium." so...
https://github.com/CaffeineMC/sodium-fabric/issues/178
(Some guy asked in FO server if some mod provided the option and i thought it was in the scope of sodium extra)

**Comment by 7777777-4547** [comment]
You can try to use [bobby](https://www.curseforge.com/minecraft/mc-mods/bobby).

**Comment by Madis0** [comment]
If the feature is just "unlocking" some hardcoded limits, I think it is in scope for Sodium Extra. If it requires more changes to the renderer, then indeed a different mod is preferable.

If implemented to Sodium Extra, I'd make it a toggle "Extended rendering distance for singleplayer" which then allows the slider to go up to... 128? Maybe more?

**Comment by Julienraptor01** [comment]
> You can try to use [bobby](https://www.curseforge.com/minecraft/mc-mods/bobby).

Bobby still can't go past vanilla 32 render distance on its own. You still need to have something that unlock 32+ or load the chunks before.

**Comment by Julienraptor01** [comment]
> If the feature is just "unlocking" some hardcoded limits, I think it is in scope for Sodium Extra. If it requires more changes to the renderer, then indeed a different mod is preferable.
> 
> If implemented to Sodium Extra, I'd make it a toggle "Extended rendering distance for singleplayer" which then allows the slider to go up to... 128? Maybe more?

Why for single player ? With the help of bobby or farsight having 128 could be possible.

**Comment by Madis0** [comment]
Well, sure, but from Sodium Extra's context it would apply only for singleplayer for most people, hence the wording. Those who install one of those mods would know it can then apply to multiplayer as well 😉

**Comment by 7777777-4547** [comment]
> > You can try to use [bobby](https://www.curseforge.com/minecraft/mc-mods/bobby).
> 
> Bobby still can't go past vanilla 32 render distance on its own. You still need to have something that unlock 32+.

I only know one is c2me....but I think is no good

**Comment by yesn0t** [comment]
for extreme render distances (like 512) you want to check out [Distant Horizons](https://modrinth.com/mod/distanthorizons)

**Comment by Julienraptor01** [comment]
> for extreme render distances (like 512) you want to check out [Distant Horizons](https://modrinth.com/mod/distanthorizons) 

I already know of Distant Horizon but it's LoD so it's not rendered with the same level of detail and it's still currently alpha, it doesn't support shaders and currently has some bugs that are really easy to encounter.
And it has incompatibility with multiple mods that i use. 
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/49
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/202
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/270
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/271

**Comment by offbeat-stuff** [comment]
c2me also unlockes render distance of upto 128
