### ISSUE TITLE
[ISSUE] Don't use vanilla strings

### ISSUE THREAD

**Issue by FlashyReese** [FlashyReese/sodium-extra-fabric#197]
Some resource packs change the formatting and styling of a string. Which appears to be odd when using existing vanilla translation strings.

**Comment by Madis0** [comment]
I didn't think this was a widespread issue to even bother with, but you could just use "§r" in front of every vanilla string to reset its format instead of creating new strings.
Edit: actually that isn't enough, but I believe this can be fixed with regex.
