### ISSUE TITLE
Sculk sensor animations are disabled by default

### ISSUE THREAD

**Issue by Madis0** [FlashyReese/sodium-extra-fabric#200]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.3

### Sodium version.

0.4.1+build.15

### What happened?

1. Installed Sodium and Sodium Extra
2. Looked at Options -> Video Settings -> Animations
3. Noticed that Sculk sensor animation is disabled

### Relevant log.

Irrelevant

### Additional information.

According to this line it should be enabled, maybe there is a typo somewhere?
https://github.com/FlashyReese/sodium-extra-fabric/blob/1.18.x/dev/src/main/java/me/flashyreese/mods/sodiumextra/client/gui/SodiumExtraGameOptions.java#L111
![Screenshot_20220511_204926](https://user-images.githubusercontent.com/8611110/167914175-2b93b9a5-a2d1-41c2-b78e-3eb11033069d.png)

**Comment by FlashyReese** [comment]
It was disabled by default by accident, I just haven't release the changes fixing it.
