### ISSUE TITLE
Mod doesn't work on Quilt

### ISSUE THREAD

**Issue by jLn0n** [FlashyReese/sodium-extra-fabric#205]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.4

### Sodium version.

0.4.1

### What happened?

when the game loads with this mod, it crashes instead of working fine

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/8715793/latest.log)

**Comment by galeofperil** [comment]
It's because of the hard "x or higher version" dependency on Fabric Loader. You can remove it by opening the mod's .jar with 7zip, opening "fabric.mod.json" in a text editor and removing the line that has fabric-loader mentioned.
However, there'll be more people trying to use the mod with Quilt, so the dependency is better off removed entirely.

**Comment by Julienraptor01** [comment]
I think you could do an override on your side just like with fabric but the best way to add support for quilt would be to add a quilt.mod.json file and keep the fabric.mod.json as it is

**Comment by theRookieCoder** [comment]
> It's because of the hard "x or higher version" dependency on Fabric Loader. You can remove it by opening the mod's .jar with 7zip, opening "fabric.mod.json" in a text editor and removing the line that has fabric-loader mentioned.

This doesn't seem to work?

**Comment by theRookieCoder** [comment]
I'm now able to use Sodium Extra 0.4.5+1.19 with Quilt flawlessly, no modification were required. I think this can be closed now.

Any idea how this was 'fixed'?

**Comment by FlashyReese** [comment]
This was probably fixed on Quilt's end when handling mods that use Fabric API.
