### ISSUE TITLE
Game fails to load when using prime-run wrapper command

### ISSUE THREAD

**Issue by AtomicJay** [FlashyReese/sodium-extra-fabric#213]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.4

### Sodium version.

0.4.1

### What happened?

When trying to use `prime-run` as a wrapper command in MultiMC to use my dedicated GPU (NVIDIA RTX 3070 Max-Q) with Sodium 0.4.1 and Sodium Extra 0.4.4, the game fails to load and exits with:

`X Error of failed request:  BadValue (integer parameter out of range for operation)`
`  Major opcode of failed request:  150 (GLX)`
`  Minor opcode of failed request:  16 (X_GLXVendorPrivate)`
`  Value in failed request:  0xffffffffffffffff`
`  Serial number of failed request:  0`
`  Current serial number in output stream:  181`
`Process exited with code 1.`

Note: this isn't shown in the attached log, but appears in the console directly after what's shown in the log after the game fails to load.

I first encountered this problem when trying to load Fabulously Optimized 3.8.2 while using `prime-run` as the wrapper command. I figured out it was Sodium Extra by getting the game to properly launch when I downgraded it to the version used in Fabulously Optimized 3.8.1 (from 0.4.4 to 0.4.3).

I also tried using `prime-run` as the wrapper command in a clean 1.18.2 Fabric instance with only Sodium 0.4.1 and Sodium Extra 0.4.4, and it still failed to load (the attached log is from this). Once again, downgrading Sodium Extra from 0.4.4 to 0.4.3 allowed the game to load properly.

### Relevant log.

https://pastebin.com/NCEqbbyR

### Additional information.

I use Arch BTW.

**Comment by FlashyReese** [comment]
Does this occur without Sodium Extra?

Edit: Never mind, I read the part where you mentioned downgrading works.

**Comment by puppymati** [comment]
Same exact problem here, I have a 3060 mobile and trying to load the game using prime-run crashes the game. I found downgrading the nvidia drivers to 495 or lower seems to fix the issue so it might not be entirely sodium-extra fault. Nevertheless I think it's an issue worth investigating further.

**Comment by puppymati** [comment]
Okay so upon further investigation it looks like some pre-enabled settings in faboulusy optimized was causing issues. Simply deleting the sodium-extra.json from the config files fixed the problem.
