### ISSUE TITLE
Screen flashing in bottom 1/4 of screen

### ISSUE THREAD

**Issue by FormulaAbyss** [FlashyReese/sodium-extra-fabric#217]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2 FabricMC 0.14.6

### Sodium Extra version.

1.18.2-0.4.1+build15

### Sodium version.

0.4.4+1.18.2-build.39

### What happened?

Whenever I add this mod into my mods folder and load up the game, the bottom 1/4 of the screen flashes. If remove this mod, the flashing stops. It is intermittent, but happens about every 2-4 seconds.

I have tried:
Removing all mods and only using Sodium/Sodium Extra
Still get the flickering. 
Tried only Sodium - no flickering
Tried all mods except Sodium Extra - No flickering
Add Sodium Extra back - Flickering returns. 

### Relevant log.

https://hastebin.skyra.pw/ibamepezul.md

### Additional information.

Sadly I am unable to record on this laptop (not enough memory)
List of mods and versions are in above log.

**Comment by FlashyReese** [comment]
Can you provide me with what operating system/hardware you are using?

**Comment by FormulaAbyss** [comment]
Windows 11 (64 bit)
AMD Athalon Gold3150U with RadeonGraphics 2.4GHz
*GB Ram

**Comment by FormulaAbyss** [comment]
I should add that this didn't happen until Up upgraded to Sodium 0.4.4+1.18.2-build.39, which was recently.

**Comment by 7777777-4547** [comment]
Did you remember the version number backwards?
Sodium 0.4.1
Sodium Extra 0.4.4

**Comment by FlashyReese** [comment]
Do you use V-Sync? If so try disabling Adaptive-Sync in `Extra > Use Adaptive Sync`

**Comment by FormulaAbyss** [comment]
> Did you remember the version number backwards? Sodium 0.4.1 Sodium Extra 0.4.4

You are correct. I'm using sodium fabric 0.4.1 build 15

**Comment by FormulaAbyss** [comment]
> Do you use V-Sync? If so try disabling Adaptive-Sync in `Extra > Use Adaptive Sync`

I tried turning this off to no avail. Turned off VSync and it seemed to resolve the issue.

**Comment by FlashyReese** [comment]
I should have adaptive sync disabled by default, it appears to be affecting vsync.

**Comment by 7777777-4547** [comment]
Maybe this video can show it(look at the hand)

https://user-images.githubusercontent.com/83630775/171987957-17fd83b3-5978-4095-a4a2-0b99a44c5a27.mp4

**Comment by FlashyReese** [comment]
This is very difficult to tell what's going on here. I will take a look into it for the 1.19 release.

**Comment by FormulaAbyss** [comment]
I finally got to get back in and play. VSync being off caused severe control issues. Every movement was delayed at best and acted like I was holding the key at worst. Even tried with a brand new install without any settings changes and still had the flashing. 

For the time being I have removed sodium extra and am having  no issues

**Comment by FlashyReese** [comment]
Try adding `mixin.adaptive_sync=false` to `.minecraft/config/sodium-extra.properties`. Let me know if it still occurs.

**Comment by FormulaAbyss** [comment]
> Try adding `mixin.adaptive_sync=false` to `.minecraft/config/sodium-extra.properties`. Let me know if it still occurs.

This seems to have fixed the issue. Thank you.

**Comment by FlashyReese** [comment]
Let me just ask you to verify what happened before you used the mixin config.

`VSync enabled` + `Adaptive Sync enabled` = Broken
`VSync enabled` + `Adaptive Sync disabled` = Broken
`VSync disabled` + `Adaptive Sync enabled` = Broken
`VSync disabled` + `Adaptive Sync disabled` = Broken

**Comment by FormulaAbyss** [comment]
Yes
Yes
Didn't try this
Game not playable with vsync disabled.

**Comment by FlashyReese** [comment]
Hello, it's me once again. Would you mind testing out a patch for me?
[artifacts.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/8850908/artifacts.zip)

These test case scenarios.
 `VSync enabled` + `Adaptive Sync enabled`
`VSync enabled` + `Adaptive Sync disabled`
`VSync disabled` + `Adaptive Sync enabled`
`VSync disabled` + `Adaptive Sync disabled`

**Comment by FormulaAbyss** [comment]
Do you want me to put both Jars in my mods folder, or is there a specific one?

**Comment by FlashyReese** [comment]
> Do you want me to put both Jars in my mods folder, or is there a specific one?

@AvatarMental Just the one **without** `-sources.jar`.

**Comment by FormulaAbyss** [comment]
> Hello, it's me once again. Would you mind testing out a patch for me? [artifacts.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/8850908/artifacts.zip)
> 
> These test case scenarios. 
Please note in my testing, Windowed goes off the screen top/bottom for me, and I cannot move the window (top window bar is off the screen), so I don't know for sure if it is flickering or not below the screen.

Before Patch: (No settings changed, clean install, Windowed/Fullscreen)
`VSync enabled` + `Adaptive Sync enabled` = No flicker/Flicker
`VSync enabled` + `Adaptive Sync disabled` = No flicker/Flicker
`VSync disabled` + `Adaptive Sync enabled` = No flicker/No flicker, controls are delayed.
`VSync disabled` + `Adaptive Sync disabled`= No flicker/No flicker, controls laggy and go longer than the key presses.

After Patch: (No settings changed, clean install, Windowed/Fullscreen)
`VSync enabled` + `Adaptive Sync enabled` = No flicker/flicker
`VSync enabled` + `Adaptive Sync disabled` = No flicker/No flicker
`VSync disabled` + `Adaptive Sync enabled` = No flicker/No flicker, delayed controls
`VSync disabled` + `Adaptive Sync disabled`= No flicker/No flicker, laggy controls and go longer than key presses

**Comment by FlashyReese** [comment]
Thanks for testing the patch.

One last question
Before the `0.4.4` update, I'm not sure if you play with V-Sync all the time. Do you get delayed controls/laggy controls without V-Sync?

**Comment by FormulaAbyss** [comment]
I'll be honest, I never messed with V-Sync before. I could potentially test it if you would like.

**Comment by FlashyReese** [comment]
Please, that would be much appreciated.

**Comment by FormulaAbyss** [comment]
Tested in `0.4.3`
`VSync enabled` + `Adaptive Sync enabled` = No flicker
`VSync enabled` + `Adaptive Sync disabled` = No flicker
`VSync disabled` + `Adaptive Sync enabled` = No flicker, delayed controls, single tap acts as a long press
`VSync disabled` + `Adaptive Sync disabled` = No flicker, controls seem mostly fine, although a bit laggy at times.

Sorry I didn't get to this yesterday, had a lot going on.

**Comment by FlashyReese** [comment]
`0.4.3` doesn't have `adaptive sync` feature I'm asking if you get delayed controls or lagginess with or without vsync.

**Comment by FormulaAbyss** [comment]
Sorry, without Vsync I do get some delayed controls, I misread one of the other settings.
