### ISSUE TITLE
[Feature Request] Fog falloff

### ISSUE THREAD

**Issue by oqipoDev** [FlashyReese/sodium-extra-fabric#218]
Can you add a fog falloff slider? It would control the distance (in percentage) where the fog starts rendering, like [Custom Fog](https://modrinth.com/mod/custom-fog), or more recently, [Simple Fog Control](https://modrinth.com/mod/simplefog).

Differently from these mods though, I'd suggest to only feature the `fog start` parameter, to make it simpler and easier for users, as these mods can get a little overkill with customizability

**Comment by FlashyReese** [comment]
Implemented in the latest release.
