### ISSUE TITLE
Traditional Chinese translation error

### ISSUE THREAD

**Issue by Starywa** [FlashyReese/sodium-extra-fabric#219]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19 fabric 0.14.6

### Sodium Extra version.

sodium-extra-0.4.5+mc1.19-build.43

### Sodium version.

sodium-fabric-mc1.19-0.4.2+build.16

### What happened?

![2022-06-08 (9)_LI](https://user-images.githubusercontent.com/86212695/172537146-dd50ba91-c902-4d0d-b856-a3624fac1f42.jpg)

### Relevant log.

,

**Comment by StarskyXIII** [comment]
Already fixed in #221 , just waiting for next release version.

**Comment by FlashyReese** [comment]
Fixed in release `0.4.6`
