### ISSUE TITLE
Clouds appear in the end when set a custom cloud height

### ISSUE THREAD

**Issue by arslan716** [FlashyReese/sodium-extra-fabric#22]
With Sodium Extra:
https://i.imgur.com/jf6j5t3.jpg

Without Sodium Extra:
https://i.imgur.com/HWQTQGG.jpg

**Comment by DragonEggBedrockBreaking** [comment]
Has been fixed in the latest development versions. Either build the mod from source, use GitHub actions, or wait for another release.

**Comment by FlashyReese** [comment]
Fixed in https://github.com/FlashyReese/sodium-extra-fabric/commit/fa8fda1e2292cbec91e36aba93e51af7a87483c2, will release later today or tomorrow.
