### ISSUE TITLE
Crashed instantly after launched the whole game

### ISSUE THREAD

**Issue by leon7104** [FlashyReese/sodium-extra-fabric#223]
[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/8986752/latest.log)

**Comment by FlashyReese** [comment]
What launcher are you using?

**Comment by leon7104** [comment]
Official

**Comment by FlashyReese** [comment]
This crash is caused by a mod called `notify`, the error you see above is the mixin config plugin not loading in because of java version, this does not affect the mod in any way.
