### ISSUE TITLE
add disable rendering of entities such as snowballs and enchantment tables

### ISSUE THREAD

**Issue by moderator10000078** [FlashyReese/sodium-extra-fabric#224]
with their help, you can make a machine lag on the client, for example, if the whole chunk is scored with enchantment tables, then minecraft is being painted, there is no render with more functionality in the cheats, and there it is fixed by disabling the book in the enchantment table

**Comment by FlashyReese** [comment]
I won't be implementing a toggle for snowballs, but I have implemented one for enchanting table books in the new release.
