### ISSUE TITLE
Increase visibilty of applied in-game text options.

### ISSUE THREAD

**Issue by themagicalcats** [FlashyReese/sodium-extra-fabric#228]
At the top left screen, there are options you can enable, in the Extras tab in Video Settings. 
**(Show FPS, Show FPS Extended, Show Coordinates.)**

What I'm suggesting is to apply text background of some kind to improve visibility or at least add an option to enable it.

**Comment by FlashyReese** [comment]
You have the option to choose which corner it will render in with Overlay Corner. I'm not sure if this solves your visibility issue.

**Comment by themagicalcats** [comment]
It doesn't solve the problem, the problem is how easy it is to view in certain environments, and how consistent it is with Minecraft's overall text backgrounds (also known as text shading), ect.

Probably should of specified a little more information, haha.

**Comment by FlashyReese** [comment]
Added option in `0.4.6`
