### ISSUE TITLE
Loading screen crash 

### ISSUE THREAD

**Issue by Tempest-5ky** [FlashyReese/sodium-extra-fabric#229]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19

### Sodium Extra version.

0.4.5

### Sodium version.

0.4.5

### What happened?

Loading screen appears for a moment then disappears, creating a crashlog. 
After removing SodiumExtra, there was no more crash and the game loaded correctly.

### Relevant log.

https://crashy.net/T3Lc51Q0ySP0APrVMVpa
https://mclo.gs/6u89i7A

### Additional information.

Modlist can be seen in the crashy.net link!

**Comment by FlashyReese** [comment]
Either disable the cloud slider by adding `mixin.cloud=false` to `.minecraft/config/sodium-extra.properties` or remove Extended Clouds.

**Comment by Tempest-5ky** [comment]
Thank you!
