### ISSUE TITLE
"Show Coordinates" option should be disabled

### ISSUE THREAD

**Issue by wiselder** [FlashyReese/sodium-extra-fabric#231]
"Show Coordinates" option should be disabled if the gamerule reducedDebugInfo is true.
This is really justified, because on some servers (such gameplay is radically different) this gamerule is true.

**Comment by FlashyReese** [comment]
Do you mean "Show Coordinates"?

**Comment by wiselder** [comment]
> 

Sorry, it's a hard day today, all right, coordinates.

**Comment by FlashyReese** [comment]
Fixed in release `0.4.6`
