### ISSUE TITLE
Can't disable fireworks particle

### ISSUE THREAD

**Issue by Zailer43** [FlashyReese/sodium-extra-fabric#234]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19

### Sodium Extra version.

sodium-extra-0.4.6+mc1.19-build.47

### Sodium version.

sodium-fabric-mc1.19-0.4.2+build.16

### What happened?

I can't disable firework explosions particle (`flash`)

### Relevant log.

https://gist.github.com/Zailer43/b4b7a4e244c2aea03e1788324c44511a

### Additional information.

![2022-07-26_16 08 05](https://user-images.githubusercontent.com/63565983/181092472-efa380b0-0f6e-499a-a87c-d781ef9831a8.png)

The wiki says that the effect of firework explosions is called `flash` while the trail as it goes up is called `firework`
https://minecraft.fandom.com/wiki/Particles

**Comment by FlashyReese** [comment]
It's just the flash of light, not the actual explosions. The code dynamically checks all registered particles and creates a toggle based on that. The previous code was hardcoded groups and it only disables `firework`.
Old code: https://github.com/FlashyReese/sodium-extra-fabric/blob/70cc190e7d3443f2d26eb639fca7173ea8aa3bfc/src/main/java/me/flashyreese/mods/sodiumextra/mixin/particle/MixinWorldRenderer.java#L69-L73

New code: https://github.com/FlashyReese/sodium-extra-fabric/blob/af8ad53d58a56f6f2ef9669f48fbefeda116aa33/src/main/java/me/flashyreese/mods/sodiumextra/mixin/particle/MixinWorldRenderer.java#L36-L44

Let me know if you can replicate this in the older version.

**Comment by FlashyReese** [comment]
Okay, after investigating further I found have found the underlying issue.

**Comment by Zailer43** [comment]
> Let me know if you can replicate this in the older version.

In 0.4.4 in 1.18.2 it didn't work either

**Comment by FlashyReese** [comment]
Fixed in https://github.com/FlashyReese/sodium-extra-fabric/commit/2441a4160fda90e9ac8babe3e6090a37efb02970
