### ISSUE TITLE
[Feature Request] to turn of potion and beacon particles

### ISSUE THREAD

**Issue by Aefinn** [FlashyReese/sodium-extra-fabric#235]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.x

### Sodium Extra version.

0.4.6

### Sodium version.

0.4.2

### What happened?

I love how I can individually turn many of the different particles and other effects but for some reason there doesn't seem to be ones for beacon effect particles and potion particles: ie the stink bubbles around you. They only turn off when you turn all particles off. Optifine did have this and I'm pretty sure I have had this with sodium too in past but now couldn't find it anymore.

### Relevant log.

sorry for posting this here, couldn't find another way to contact you :/

**Comment by FlashyReese** [comment]
See [list of particles](https://minecraft.fandom.com/wiki/Particles). Beacon particles fall under `ambient_entity_effect` and the potion effects are `effect` and `entity_effect` according to the list above.
