### ISSUE TITLE
Loading screen crash

### ISSUE THREAD

**Issue by Pl4yer0ne** [FlashyReese/sodium-extra-fabric#238]
Minecraft version.
1.19.2 (but also happens with 1.19 and 1.18.1)

Sodium Extra version.
0.4.6

Sodium version.
sodium-fabric-mc1.19-0.4.2 (replaymod compatible)

What happened?
Loading screen appears for a moment then disappears, creating a crashlog.
After removing SodiumExtra, there was no more crash and the game loaded correctly.

Relevant log.
[crash-2022-08-13_22.03.07-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/9332105/crash-2022-08-13_22.03.07-client.txt)

**Comment by FlashyReese** [comment]
Your config might corrupted, I can't fully tell without a full log but you can delete `.minecraft/config/sodium-extra-options.json` and see if that solves your issue.

**Comment by Pl4yer0ne** [comment]
its now working ty
