### ISSUE TITLE
1.19.1 Sodium Extras makes game crash

### ISSUE THREAD

**Issue by BlitzIR** [FlashyReese/sodium-extra-fabric#240]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.1

### Sodium Extra version.

0.4.6

### Sodium version.

1.19-.0.4.2

### What happened?

The game crashes every time I try to load w/sodium extras mod. When I remove the mod the game loads fine when the mod isn't being used. I'm on ver 1.19.1

### Relevant logs

https://gist.github.com/BlitzIR/373eef4fa0467844435be67f563901c7

**Comment by FlashyReese** [comment]
Your config file is corrupted. Delete `.minecraft/config/sodium-extra-options.json` to fix this issue.

**Comment by BlitzIR** [comment]
That fixed the issue. Thanks!
