### ISSUE TITLE
VSync is a bit buggd

### ISSUE THREAD

**Issue by Kamiszewskyy** [FlashyReese/sodium-extra-fabric#243]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.7

### Sodium version.

0.4.1

### What happened?

Well... After this new update to Sodium Extra, VSync just doesn't work properly. I can disable, enable and this third new option (Idk what is this) but nothing happens. Sometimes I have 300 fps while VSync being enable, sometimes I have 60 fps while VSync being disable. Here's the screenshot of the example.

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/9386004/latest.log)

### Additional information.

![image](https://user-images.githubusercontent.com/62818516/185723957-6a01274b-b006-4f0a-82c3-8032b20d093c.png)

**Comment by FlashyReese** [comment]
Can you upload your '.minecraft/options.txt' and '.minecraf/config/sodium-extra-options.json' while vsync is enabled?

**Comment by Kamiszewskyy** [comment]
[options.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/9386104/options.txt) <-- options.txt
https://pastes.dev/OCT5FDQe4s <-- sodium extra.json

**Comment by FlashyReese** [comment]
Fixed in `0.4.8` from Minecraft `1.16.5` to `1.18.2`.
