### ISSUE TITLE
Crashes Game on Launch

### ISSUE THREAD

**Issue by Dougarooski** [FlashyReese/sodium-extra-fabric#245]
When launching the game, sodium extra crashes the game. Verified that game runs with same mods without the Sodium Extra mod.

Here is the smaller crash code:
The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_758 failed
Exit Code: -1

Mods installed: Better F3, Fabric API, InventoryHUD, lamb dynamic lights, mod menu, sodium options, sodium fabric, xaeros minimap, xaeros world map. 

Attached is the full error report
[crash-2022-08-21_11.37.24-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/9389758/crash-2022-08-21_11.37.24-client.txt)

**Comment by Dougarooski** [comment]
Update, only happens on sodium extras version 0.4.8

If I install extras version 0.4.5 then the game launches.

**Comment by FlashyReese** [comment]
You are running the `1.18.2` version on `1.19.2`. Unfortunately, CurseForge doesn't let me decide which is the latest download button go nor move the existing on display. https://www.curseforge.com/minecraft/mc-mods/sodium-extra/files/all?filter-game-version=1738749986%3a73407

Edit: I notice you also have the `1.16.5` version of Reese's Sodium Options on `1.19.2`. https://modrinth.com/mod/reeses-sodium-options

**Comment by Jackgawe** [comment]
uhuh
