### ISSUE TITLE
Sodium Extra Causes Crash on Startup

### ISSUE THREAD

**Issue by PilotgamerGuy** [FlashyReese/sodium-extra-fabric#247]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19

### Sodium Extra version.

0.4.6+mc1.19-build.47

### Sodium version.

fabric-mc1.19-0.4.2 (replaymod compatible)

### What happened?

Sodium extra causes Minecraft to crash on startup. I isolated the mods down to only the required mods (fabric api & language kotlin, and sodium), and removing sodium extra prevents the crashes.

### Relevant logs

[crash-2022-08-23_11.39.39-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/9409837/crash-2022-08-23_11.39.39-client.txt)

### Additional information

I did try this with sodium-fabric-mc1.19-0.4.2+build.16, which is not replayMod compatible, and it still crashed.

**Comment by FlashyReese** [comment]
Looks like your config file is corrupt, deleting `.minecraft/config/sodium-extra-options.json` will resolve your issue.

**Comment by PilotgamerGuy** [comment]
Thanks for your support! Deleting the file fixed the issue.
