### ISSUE TITLE
Minecraft crashes upon opening video settings

### ISSUE THREAD

**Issue by Jackgawe** [FlashyReese/sodium-extra-fabric#248]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.16.5

### Sodium Extra version.

0.4.8

### Sodium version.

0.2.0

### What happened?

When I go to the settings ----> video settings, it crashes lmao.

### Relevant logs

https://crashy.net/Q6S8fHJKOek3OumD3wXO

or
https://bytebin.lucko.me/x0WaC3pgtS
[crash-2022-08-27_01.16.00-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/9436812/crash-2022-08-27_01.16.00-client.txt)

### Additional information

![image](https://user-images.githubusercontent.com/108591924/187002052-c01be7c6-6399-4ec5-8442-c7911a4f85e7.png)
my mods folder ik its cool haha``

**Comment by FlashyReese** [comment]
Can you zip your mods and upload them here?

**Comment by Jackgawe** [comment]
ehh sure, i also think when i saw sodium extra it looked so cool!

[mods lol.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9436956/mods.lol.zip)

**Comment by FlashyReese** [comment]
You aren't running Sodium `0.2.0`. Updating to `0.2.0` will resolve your issue.

**Comment by Jackgawe** [comment]
i mean i will try it

**Comment by Jackgawe** [comment]
woah thank you so much for helping me :D

**Comment by FlashyReese** [comment]
Although, I'm pretty sure you need an [unofficial port of sodium](https://www.replaymod.com/download/sodium-fabric-mc1.16.5-0.2.0+rev.f42b4ca.jar) for [replay mod](https://www.replaymod.com/download/) to work.

**Comment by Jackgawe** [comment]
Replay mod still works

**Comment by FlashyReese** [comment]
The replayer will end up crashing.

**Comment by Jackgawe** [comment]
i dont use it much lol thanks tho
