### ISSUE TITLE
Chunks not rendering

### ISSUE THREAD

**Issue by astridos2go** [FlashyReese/sodium-extra-fabric#249]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.9

### Sodium version.

0.4.3

### What happened?

When the mod is enabled, entire chunks will not render. When this mod is disabled, the chunks render perfectly fine.

I expected the chunks to render normally.

### Relevant log.

https://paste.ee/p/xpC8n

### Additional information.

# Screenshot
![2022-08-28_19 16 03](https://user-images.githubusercontent.com/45048997/187098653-7fbf08a8-b359-40ba-ada7-fc8feb2296c6.png)

# Mod List
- advanced-tooltips 1.6.0+1.19
- advanced-tooltips-core 1.6.0 via advanced-tooltips
- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
- advancementinfo 1.19.1-fabric0.58.5-1.3.1
- animatica 0.5+1.19
- antighost 1.19.1-fabric0.58.5-1.1.5
- appleskin 2.4.0+mc1.19
- architectury 6.2.43
- armored-elytra 4.0.0+build.20
- armorhide 1.0.1
- badpackets 0.2.0
- balm-fabric 4.5.2+0
- bebooks 1.4.1
- better-dark-mode 2.1.0
- betterbiomeblend 1.19-1.3.6-fabric
- betterf3 1.3.2
- bettermounthud 1.1.4
- blockmeter 1.7
- blue_endless_jankson 1.2.1 via jankson
- boathud 1.1.1
- bookshelf 16.1.4
- borderlessmining 1.1.5+1.19
- c2me 0.2.0+alpha.8.33
- c2me-base 0.2.0+alpha.8.33 via c2me
- c2me-client-uncapvd 0.2.0+alpha.8.33 via c2me
- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.8.33 via c2me
- c2me-fixes-general-threading-issues 0.2.0+alpha.8.33 via c2me
- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.8.33 via c2me
- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.8.33 via c2me
- c2me-notickvd 0.2.0+alpha.8.33 via c2me
- c2me-opts-allocs 0.2.0+alpha.8.33 via c2me
- c2me-opts-chunk-access 0.2.0+alpha.8.33 via c2me
- c2me-opts-chunkio 0.2.0+alpha.8.33 via c2me
- c2me-opts-math 0.2.0+alpha.8.33 via c2me
- c2me-opts-scheduling 0.2.0+alpha.8.33 via c2me
- c2me-opts-worldgen-general 0.2.0+alpha.8.33 via c2me
- c2me-opts-worldgen-vanilla 0.2.0+alpha.8.33 via c2me
- c2me-rewrites-chunkio 0.2.0+alpha.8.33 via c2me
- c2me-server-utils 0.2.0+alpha.8.33 via c2me
- c2me-threading-chunkio 0.2.0+alpha.8.33 via c2me
- c2me-threading-lighting 0.2.0+alpha.8.33 via c2me
- c2me-threading-scheduling 0.2.0+alpha.8.33 via c2me
- c2me-threading-worldgen 0.2.0+alpha.8.33 via c2me
- caffeineconfig 1.0.0+1.17 via sodium-extra
- cardinal-components-base 5.0.1 via impersonate
- cardinal-components-entity 5.0.1 via impersonate
- carpet 1.4.83
- carpet-extra 1.4.83
- carpet-fixes 1.19-1.11.2
- carpet-tis-addition 1.39.0
- cem 0.7.1
- citresewn 1.1.1+1.19
- citresewn-defaults 1.1.1+1.19 via citresewn
- clear-skies 2.0.94
- clickthrough 1.19.1-fabric0.58.5-0.4
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 8.0.75
- coat 1.0.0-beta.17+mc22w17a via completeconfig
- colormatic 3.1.2+mc.1.19
- com_electronwill_night-config_core 3.6.5 via c2me
- com_electronwill_night-config_toml 3.6.5 via c2me
- com_github_llamalad7_mixinextras 0.0.12 via cull-less-leaves
- com_github_luben_zstd-jni 1.5.2-2 via dashloader
- com_ibm_async_asyncutil 0.1.0 via c2me
- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
- completeconfig 2.0.0
- completeconfig-base 2.0.0 via completeconfig
- completeconfig-gui-cloth 2.0.0 via completeconfig
- completeconfig-gui-coat 2.0.0 via completeconfig
- conditional-mixin 0.3.1 via carpet-tis-addition
- continuity 2.0.1+1.19
- controlling 10.0+6
- copper_pipe 1.11-b4
- couplings 1.9.1+1.19
- craftingtweaks 15.1.0
- craftpresence 1.8.10
- crowdin-translate 1.4+1.19 via antighost
- cull-less-leaves 1.0.5
- dashloader 4.1.2+1.19
- detailab 2.6.2+1.19-fabric
- dev_isxander_settxi_settxi-core 2.7.4 via zoomify
- dev_isxander_settxi_settxi-kotlinx-serialization 2.7.4 via zoomify
- dev_quantumfusion_hyphen 0.2.2 via dashloader
- dev_quantumfusion_taski 1.1.0 via dashloader
- draggable-resource-packs 3.0.1+build.9
- dsyt 1.0.0
- dynamiccrosshair 3.5.1+1.19
- dynamicfps 2.2.0
- easiervillagertrading 1.19.1-fabric0.58.5-1.5.4
- enchdesc 13.0.1
- enhancedblockentities 0.7.1+1.19
- entity_texture_features 4.0.2
- entityculling 1.5.2-mc1.19
- error_notifier 1.0.9 via roughlyenoughitems
- fabric-api 0.60.0+1.19.2
- fabric-api-base 0.4.11+e62f51a390 via fabric-api
- fabric-api-lookup-api-v1 1.6.9+9ff28f4090 via fabric-api
- fabric-biome-api-v1 9.0.17+aeb40ebe90 via fabric-api
- fabric-blockrenderlayer-v1 1.1.20+aeb40ebe90 via fabric-api
- fabric-client-tags-api-v1 1.0.1+b35fea8390 via fabric-api
- fabric-command-api-v1 1.2.11+f71b366f90 via fabric-api
- fabric-command-api-v2 2.1.7+0c17ea9690 via fabric-api
- fabric-commands-v0 0.2.28+df3654b390 via fabric-api
- fabric-containers-v0 0.1.34+df3654b390 via fabric-api
- fabric-content-registries-v0 3.2.3+aeb40ebe90 via fabric-api
- fabric-convention-tags-v1 1.1.1+7cd20a1490 via fabric-api
- fabric-crash-report-info-v1 0.2.5+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.1.8+a680b9b490 via fabric-api
- fabric-dimensions-v1 2.1.30+aeb40ebe90 via fabric-api
- fabric-entity-events-v1 1.4.18+9ff28f4090 via fabric-api
- fabric-events-interaction-v0 0.4.28+aeb40ebe90 via fabric-api
- fabric-events-lifecycle-v0 0.2.28+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.21+aeb40ebe90 via fabric-api
- fabric-item-api-v1 1.5.7+35a03c4390 via fabric-api
- fabric-item-groups-v0 0.3.28+aeb40ebe90 via fabric-api
- fabric-key-binding-api-v1 1.0.20+aeb40ebe90 via fabric-api
- fabric-keybindings-v0 0.2.18+df3654b390 via fabric-api
- fabric-language-kotlin 1.8.3+kotlin.1.7.10
- fabric-lifecycle-events-v1 2.1.2+aeb40ebe90 via fabric-api
- fabric-loot-api-v2 1.1.3+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.6+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.3+176380a290 via fabric-api
- fabric-mining-level-api-v1 2.1.14+33fbc73890 via fabric-api
- fabric-models-v0 0.3.17+aeb40ebe90 via fabric-api
- fabric-networking-api-v1 1.2.4+5eb68ef290 via fabric-api
- fabric-networking-v0 0.3.21+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.0.11+aeb40ebe90 via fabric-api
- fabric-particles-v1 1.0.10+aeb40ebe90 via fabric-api
- fabric-permissions-api-v0 0.2-SNAPSHOT via renameit
- fabric-registry-sync-v0 0.9.24+aeb40ebe90 via fabric-api
- fabric-renderer-api-v1 1.0.10+aeb40ebe90 via fabric-api
- fabric-renderer-indigo 0.6.12+aeb40ebe90 via fabric-api
- fabric-renderer-registries-v1 3.2.20+df3654b390 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90 via fabric-api
- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90 via fabric-api
- fabric-rendering-v0 1.1.22+df3654b390 via fabric-api
- fabric-rendering-v1 1.10.16+aeb40ebe90 via fabric-api
- fabric-resource-conditions-api-v1 2.0.11+e62f51a390 via fabric-api
- fabric-resource-loader-v0 0.6.1+aeb40ebe90 via fabric-api
- fabric-screen-api-v1 1.0.26+f05effaf90 via fabric-api
- fabric-screen-handler-api-v1 1.2.13+9ff28f4090 via fabric-api
- fabric-textures-v0 1.0.20+aeb40ebe90 via fabric-api
- fabric-transfer-api-v1 2.0.11+83a8659290 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.0+42d99c3290 via fabric-api
- fabricloader 0.14.9
- farsight 1.19.1-2.0
- ferritecore 4.2.1
- fiber 0.23.0-2 via neat
- forgeconfigapiport 4.2.3
- forgetmechunk 1.0.4-1.18.X-1.19.X
- gammautils 1.6.10
- gbfabrictools 1.3.4+1.19 via clickthrough
- grindenchantments 2.0.0+1.19
- horseinfo 0.4.2-1.19
- impersonate 2.7.0
- indium 1.0.8+mc1.19.2
- inventory_control_tweaks 1.3.18
- inventoryhud 3.4.2
- inventoryprofilesnext 1.7.0
- inventorytabs 0.9.beta-1.19.x
- iris 1.2.7
- itemmodelfix 1.0.3+1.19
- jankson 4.1.1+j1.2.1 via libgui
- java 18
- jukeboxparticles 1.0.0
- krypton 0.2.1
- lambdynlights 2.1.2+1.19
- lazy-language-loader 0.3.1
- lazydfu 0.1.3
- libgui 6.0.0+1.19 via soundboard
- libninepatch 1.1.0 via libgui
- lithium 0.8.3
- malilib 0.13.0
- mbp 1.4
- mcpppp 0.7.2
- memoryleakfix 1.19.1-0.7.0
- midnightlib 0.5.2 via puzzle
- minecraft 1.19.2
- minihud 0.23.3
- modmenu 4.0.6
- moreculling 1.19.1-0.10.0
- moremcmeta 1.19-3.0.5
- mousetweaks 2.22
- neat 1.19-32-FABRIC
- notenoughcrashes 4.1.8+1.19.2
- openpartiesandclaims 0.8.1
- ordinarytweaks 1.3.1
- org_anarres_jcpp 1.4.14 via iris
- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
- org_joml_joml 1.10.4 via sodium
- org_threadly_threadly 7.0 via c2me
- org_yaml_snakeyaml 1.30 via carpet-tis-addition
- ostoverhaul 0.2.6
- packet_tweaker 0.3.0+1.18.2 via server_translations_api
- placeholder-api 2.0.0-beta.7+1.19 via renameit
- pride 1.1.2+1.19 via lambdynlights
- projectsavethepets 3.2.0+2022.e000b2a529.fabric
- puzzle 1.4.0-1.19
- puzzle-base 1.4.0-1.19 via puzzle
- puzzle-gui 1.4.0-1.19 via puzzle
- puzzle-models 1.4.0-1.19 via puzzle
- puzzle-splashscreen 1.4.0-1.19 via puzzle
- quickconnectbutton 1.1
- reeses-sodium-options 1.4.7+mc1.19.2-build.59
- renameit 1.3.0+1.19
- roughlyenoughitems 9.1.530
- roughlyenoughresources 2.6.0
- server_translations_api 1.4.14+1.19-rc2 via renameit
- settxi-gui-cloth-config 2.7.4 via zoomify
- smoothboot 1.19-1.7.1
- sodium 0.4.3+build.17
- sodium-extra 0.4.9+mc1.19.2-build.60
- soundboard 1.2.0
- spark 1.9.26
- spruceui 4.0.0+1.19 via enhancedblockentities
- starlight 1.1.1+fabric.ae22326
- suggestion_tweaker 1.19.1-1.3.1
- tooltipfix 1.0.5-1.19
- tweakeroo 0.14.3
- uglyscoreboardfix 2.7.0
- visuality 0.5.1
- waxednotwaxed 1.1.3
- wthit 5.11.3
- xaerominimap 22.13.2
- xaeroworldmap 1.26.5
- zoomify 2.4.2

**Comment by FlashyReese** [comment]
Has this occurred to you on Sodium `0.4.2`? To be honest, there is no reason for Sodium Extra to cause this because it doesn't touch any chunk rendering but if you can help me by bisecting what feature might be causing this? 

To disable features in Sodium Extra it can be done via `.minecraft/config/sodium-extra.properties`

Here is a list of features you can disable by adding them to the configuration file mentioned above.
```
mixin.animation=false
mixin.biome_colors=false
mixin.cloud=false
mixin.fog=false
mixin.gui=false
mixin.instant_sneak=false
mixin.light_updates=false
mixin.particle=false
mixin.prevent_shaders=false
mixin.reduce_resolution_on_mac=false
mixin.render=false
mixin.render.block=false
mixin.render.block.entity=false
mixin.render.entity=false
mixin.sky=false
mixin.sky_colors=false
mixin.sodium=false
mixin.sodium.accessibility=false
mixin.sodium.resolution=false
mixin.sodium.scrollable_page=false
mixin.stars=false
mixin.sun_moon=false
mixin.toasts=false
```

**Comment by astridos2go** [comment]
So I messed around with the mixins and nothing changed. I have started troubleshooting on my own again, and realized that disabling Sodium Extra is actually not solving the issue.

It must be one of the other mods I have installed. Sorry for the inconvience.
