### ISSUE TITLE
 [Feature Request] Spesific Fog Toggle

### ISSUE THREAD

**Issue by ghost** [FlashyReese/sodium-extra-fabric#252]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.10

### Sodium version.

0.4.4

### What happened?

In the current release of sodium extra the fog toggle affects all types of fog rather than just border fog like previous versions of the mod. This is problematic for people who just want to change or disable one type of fog. (In my case border fog)

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/9455789/latest.log)

**Comment by FlashyReese** [comment]
Can you try this build? It should resolve this issue, I will probably have separate sliders for all fog types in the next release.

~~[fog-fix-test.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9457334/fog-fix-test.zip)~~
[fog-fix-test2.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9457381/fog-fix-test2.zip)

**Comment by CasualWolfGamer** [comment]
> 
Don't add in a no fog option for lava. It could possibly be considered cheating since you can technically find debris under lava lakes in the nether. I don't think it's a problem with water too much but lava, 100%. Also optifine never had that to where there was a no fog toggle for lava. Just render distance chunks.

**Comment by FlashyReese** [comment]
It's a bug in `0.4.10` when I rewrote the fog slider implementation. It should be resolved in the latest commit. You can grab it here https://github.com/FlashyReese/sodium-extra-fabric/suites/8119857259/artifacts/351413916

**Comment by CasualWolfGamer** [comment]
> It's a bug in `0.4.10` when I rewrote the fog slider implementation. It should be resolved in the latest commit. You can grab it here https://github.com/FlashyReese/sodium-extra-fabric/suites/8119857259/artifacts/351413916

I made a new issue relating in this fix.
