### ISSUE TITLE
Fog Fix causes fog when turned off on servers to still show fog.

### ISSUE THREAD

**Issue by CasualWolfGamer** [FlashyReese/sodium-extra-fabric#256]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.2*

### Sodium Extra version.

Newest fog fix build*

### Sodium version.

0.4.4*

### What happened?

ok so i used the new fog sliders for overworld, nether, and end and turned them off and it still is showing fog
![2022-09-06_12 53 24](https://user-images.githubusercontent.com/67299330/188726665-9dc7214f-2be3-4028-b8a3-0708a64e9347.png)
![2022-09-06_12 52 54](https://user-images.githubusercontent.com/67299330/188726668-e74ee6a1-674c-4da9-8890-523d22852703.png)
 
I think it is only not working on servers with multiverse plugin because it does work on my singleplayer world.

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/9500477/latest.log)

**Comment by CasualWolfGamer** [comment]
yes i went to overworld world and it works fine but when i go to another world portal on the server im playing on it doesnt work.

**Comment by FlashyReese** [comment]
[fog-test-fix-multiverse.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9500566/fog-test-fix-multiverse.zip)
Can you try this build instead? It should add an additional slider if the dimension doesn't exist

**Comment by CasualWolfGamer** [comment]
> [fog-test-fix-multiverse.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9500566/fog-test-fix-multiverse.zip) Can you try this build instead? It should add an additional slider if the dimension doesn't exist
![2022-09-06_13 46 28](https://user-images.githubusercontent.com/67299330/188734903-d8d08074-5dab-4246-b4a9-73a7b90ac843.png)

I dont see an option for that in the build i just added
unless im missing something

**Comment by FlashyReese** [comment]
Hmmm I don't have any servers with multiverse plugins that I can join and test. Any chance you can send me the log with this build below?
[fog-test-fix-multiverse-2.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9500645/fog-test-fix-multiverse-2.zip)

**Comment by CasualWolfGamer** [comment]
> Hmmm I don't have any servers with multiverse plugins that I can join and test. Any chance you can send me the log with this build below? [fog-test-fix-multiverse-2.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9500645/fog-test-fix-multiverse-2.zip)

It doesnt show until you go to another world that isnt on the list. seems to have fixed the fog problem too
![2022-09-06_13 58 15](https://user-images.githubusercontent.com/67299330/188736911-0b75f9bd-69be-4144-82fd-44346cf35f84.png)

**Comment by CasualWolfGamer** [comment]
> > Hmmm I don't have any servers with multiverse plugins that I can join and test. Any chance you can send me the log with this build below? [fog-test-fix-multiverse-2.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9500645/fog-test-fix-multiverse-2.zip)
> 
> It doesnt show until you go to another world that isnt on the list. seems to have fixed the fog problem too ![2022-09-06_13 58 15](https://user-images.githubusercontent.com/67299330/188736911-0b75f9bd-69be-4144-82fd-44346cf35f84.png)

also seems to add on to the list when i go to the different worlds
![2022-09-06_14 00 32](https://user-images.githubusercontent.com/67299330/188737232-da65e68a-0f59-4cbe-b608-206a90105fd2.png)

**Comment by CasualWolfGamer** [comment]
is it possible to add one option that applies to all the worlds that isnt overworld, nether, or end? or is this the only way to go?
but other than that the issue is fixed

**Comment by FlashyReese** [comment]
Yeah, since this isn't a vanilla server, the server doesn't provide the custom dimensions list the way that vanilla does so you need to enter the dimension first for the slider to be added. It is possible for me to have a slider for dimensions that aren't vanilla but it would defeat the purpose of a per dimension slider.

If you want the old fog slider that just applies to every world you can still use version `0.4.7` it should be compatible with the latest version of Sodium

**Comment by CasualWolfGamer** [comment]
> Yeah, since this isn't a vanilla server, the server doesn't provide the custom dimensions list the way that vanilla does so you need to enter the dimension first for the slider to be added. It is possible for me to have a slider for dimensions that aren't vanilla but it would defeat the purpose of a per dimension slider.
> 
> If you want the old fog slider that just applies to every world you can still use version `0.4.7` it should be compatible with the latest version of Sodium

oh im alright with the per dimension slider. anyways thanks for fixing this

**Comment by FlashyReese** [comment]
Can you do me one last favor? Can you try this build and upload the log file after joining the server and opening the video options menu?
[fog-fix-test3-logs.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9500757/fog-fix-test3-logs.zip)

**Comment by CasualWolfGamer** [comment]
> 
![2022-09-06_14 16 37](https://user-images.githubusercontent.com/67299330/188739657-a4036bbf-3c03-4e1c-ad13-8ab6448fd5cc.png)
[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/9500775/latest.log)
heres the log and options menu
