### ISSUE TITLE
[Feature Request] Translucency bug fix

### ISSUE THREAD

**Issue by CasualWolfGamer** [FlashyReese/sodium-extra-fabric#257]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.2*

### Sodium Extra version.

0.4.10

### Sodium version.

0.4.4*

### What happened?

ok so my suggestion is to add a fix for the translucency bug that Sodium hasnt fixed yet. meaning its been ongoing as a bug without any fixes for over 2 years and it was fixed but never released as a public version back in 1.18. if possible could this be added in as a fix but made a toggle on and off option incase it ruins performance? because it is said the code can ruin performance on some pcs.

### Relevant log.

heres the code to the fix the translucency bug if you wanna implement it into sodium extra. 
https://github.com/CaffeineMC/sodium-fabric/pull/963
the code should be under files changed or where MeeniMc Commented.

### Additional information.

this would only be until sodium adds it into their code

**Comment by FlashyReese** [comment]
Yeah, this isn't going to happen. Sodium `0.5.0` is right around the corner and should resolve this issue.

**Comment by CasualWolfGamer** [comment]
> Yeah, this isn't going to happen. Sodium `0.5.0` is right around the corner and resolves this issue.

i didnt know that. ty for telling me
