### ISSUE TITLE
[Feature Request] Add an option to turn off hurt cam

### ISSUE THREAD

**Issue by CasualWolfGamer** [FlashyReese/sodium-extra-fabric#258]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.2*

### Sodium Extra version.

0.4.10

### Sodium version.

0.4.4*

### What happened?

ok so my suggestion is to add an option to toggle on and off hurtcam. what hurtcam does is when you take damage your camera tilts in an angle for a second and having an option to have it off would be really cool because its annoying and sometimes nauseous to constantly see it when you're trying to pvp players.

### Relevant log.

*

**Comment by FlashyReese** [comment]
https://github.com/FlashyReese/sodium-extra-fabric/issues/60#issuecomment-885996293

**Comment by STEVE123132** [comment]
u know you can change it in accessibility settings right?
