### ISSUE TITLE
Turning off Fog turns off Blindness and Darkness Effect

### ISSUE THREAD

**Issue by CasualWolfGamer** [FlashyReese/sodium-extra-fabric#259]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.2*

### Sodium Extra version.

Newest fog fix build*

### Sodium version.

0.4.4*

### What happened?

ok so when i got the darkness effect i my vision wasn't limited. same with blindness

### Relevant log.

Blindness Effect
With Fog On. This is how it's supposed to look.
![2022-09-13_19 20 22](https://user-images.githubusercontent.com/67299330/190044180-2fa89da3-0224-4d39-8a9f-4be94c12cae9.png)

With Fog Off. This is not how it's supposed to look.
![2022-09-13_19 20 27](https://user-images.githubusercontent.com/67299330/190044260-c9cda4d8-dff1-4d6d-81e3-0a28651c6694.png)

Darkness Effect
With Fog On. This is how it's supposed to look.
![2022-09-13_19 22 54](https://user-images.githubusercontent.com/67299330/190044410-8bec5c29-7ba8-4bea-b0c0-10b178b512e9.png)

With Fog Off. This is not how it's supposed to look.
![2022-09-13_19 23 03](https://user-images.githubusercontent.com/67299330/190044551-fcfac115-0615-4ce2-9712-8b38bfa5346a.png)

**Comment by CasualWolfGamer** [comment]
Also make it to where the multiverse fog option is in a folder of sorts or sort it with server folders in the render options. so that way it doesnt keep on piling up when you're on a different server or even just in singleplayer. it can be hard to navigate when stuff is piled up.

**Comment by CasualWolfGamer** [comment]
hopefully this darkness/blindness fog bug gets fixed because this is considered a little cheaty

**Comment by gassug3** [comment]
Came here to check if this was posted. Can attest that this is an issue. I need to keep fog enabled when playing on servers so I don't have an unfair advantage.

**Comment by CasualWolfGamer** [comment]
> Came here to check if this was posted. Can attest that this is an issue. I need to keep fog enabled when playing on servers so I don't have an unfair advantage.

Yeah I'm waiting on it to be fixed still

**Comment by CasualWolfGamer** [comment]
It's almost like the one bug where you don't have fog in lava at all

**Comment by FlashyReese** [comment]
It should be fixed, I did a patch a few days ago but I forgot to update the issue tracker. https://github.com/FlashyReese/sodium-extra-fabric/suites/8340735597/artifacts/367005190

**Comment by CasualWolfGamer** [comment]
> It should be fixed, I did a patch a few days ago but I forgot to update the issue tracker. https://github.com/FlashyReese/sodium-extra-fabric/suites/8340735597/artifacts/367005190

yep its fixed just tested it

**Comment by CasualWolfGamer** [comment]
question do i need to close the issue myself or do you usually do it?

**Comment by lunaynx** [comment]
This bug is happening again on 1.21.x. Disabling "Atmospheric Fog" also negates Blindness and Darkness.

**Comment by NinjaGo31** [comment]
I can attest to @lunaynx's comment. This can lead to unfair advantages for multiplayer servers.
