### ISSUE TITLE
Sodium Extra causing game to crash

### ISSUE THREAD

**Issue by isFrame** [FlashyReese/sodium-extra-fabric#260]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.10

### Sodium version.

0.4.4

### What happened?

when i try lauch minecraft , my game crashes. but when i remove sodium extra from the mods folder the the game lauch without any problem

### Relevant logs

[crash-2022-09-16_21.25.47-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/9586752/crash-2022-09-16_21.25.47-client.txt)

**Comment by FlashyReese** [comment]
Remove `Extended Clouds` or disable Sodium Extra's Cloud Height feature by adding `mixin.cloud=false` to `.minecraft/config/sodium-extra.properties`

**Comment by uqtdev** [comment]
Still crashes for me

**Comment by FlashyReese** [comment]
> Still crashes for me

Please provide a crash log

**Comment by uqtdev** [comment]
It didn't give me a crash log and only showed up with the fabric error screen when it happened at first. When I tried to recreate it, it worked, so it might've just been a corrupted download or something (I had downloaded 0.4.9 to replace it and deleted 0.4.10)
