### ISSUE TITLE
Can't change Auto save frequency

### ISSUE THREAD

**Issue by DarkStarOnGitHub** [FlashyReese/sodium-extra-fabric#262]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.10

### Sodium version.

0.4.4

### What happened?

I don't think this is a bug but a feature of Optifine which I feel should be in Sodium Extra.
There's a feature in Optifine which lets me change the frequency of World Autosaves (in singleplayer).

I get painful lag spikes whenever the game autosaves (which is a vanilla feature btw) and I prefer to decrease the frequency of autosaves. Unfortunately, I can't find an option in Sodium or Sodium extra mod which lets me do that. I searched for mods which could do the same but that's a nope.

### Relevant log.

um, theres no need

**Comment by DarkStarOnGitHub** [comment]
Ps: you should make an 'add this feature or smthn' tag

**Comment by FlashyReese** [comment]
As far as I'm aware from looking at the vanilla's autosave code, it tells me:
Integrated Server (singleplayer): Autosaves on the pause screen.
Dedicated Server (multiplayer): Autosaves every 6000 ticks (5 minutes).

After testing and investigating OptiFine's autosave feature, it appears to be not saving on every pause screen and delaying the autosave until the configured time and then triggered by the next pause screen that meets that time. This does nothing but delay saving on pause screens and results in a more extended lag spike from more things being saved between those times. 

The autosave frequency is only beneficial if you are constantly pausing/unpausing within a few frames. In my opinion, this is rather a niche feature that's only beneficial for users that do the above-mentioned. I might consider it and leave this issue open for now but I make no promises to anyone.
