### ISSUE TITLE
Fireworks have white elements

### ISSUE THREAD

**Issue by NotroDev** [FlashyReese/sodium-extra-fabric#274]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.11 build 68

### Sodium version.

0.4.4 build 18

### What happened?

Fireworks have weird, white elements.
![obraz](https://user-images.githubusercontent.com/77281214/199987398-79bd2766-7f09-440f-bbd6-159ba1c3c22a.png)

### Relevant log.

https://gist.github.com/NotroDev/83ae9130d3a8bc25cff321c3f74a3fac

### Additional information.

Yeah, in logs I have a lot of mods, but I tested it with only sodium and sodium extra - it's the same. (Without sodium extra, everything is okay, so it's its fault).

**Comment by FlashyReese** [comment]
[sodium-extra-0.4.11+mc1.19.2-unknown.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9939190/sodium-extra-0.4.11%2Bmc1.19.2-unknown.zip)
Try this build, this should fix the issue.

**Comment by NotroDev** [comment]
> [sodium-extra-0.4.11+mc1.19.2-unknown.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/9939190/sodium-extra-0.4.11%2Bmc1.19.2-unknown.zip) Try this build, this should fix the issue.

Yeah, it works.
