### ISSUE TITLE
ru_ru translate 

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [FlashyReese/sodium-extra-fabric#275]
Why doesn't Sodium Extra have a Russian translation if crowdin has one?
![image](https://user-images.githubusercontent.com/98014624/200129184-b9521314-6cd1-413a-8d73-a635b3c9e203.png)

**Comment by FlashyReese** [comment]
There is one https://github.com/FlashyReese/sodium-extra-fabric/blob/1.19.x/dev/src/main/resources/assets/sodium-extra/lang/ru_ru.json
