### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Cinnaamonn** [FlashyReese/sodium-extra-fabric#280]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.12

### Sodium version.

0.4.1

### What happened?

When I launch the game, it loads briefly up until the "Mojang Studios" screen, before crashing shortly after.

### Relevant logs

[crash-2022-11-16_14.00.53-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/10025796/crash-2022-11-16_14.00.53-client.txt)

**Comment by FlashyReese** [comment]
It appears to be conflicting with the Origins mod. The only workaround, for now, is adding `mixin.fog=false` to `.minecraft/config/sodium-extra.properties` and losing out the fog control functionality or downgrading since Sodium Extra `0.4.12` and Origins both modify the same area of the game.

**Comment by Cinnaamonn** [comment]
I figured it was something like two mods modifying the same thing. Kind of ironic since I wanted to configure the fog to see farther thru this mod lol. Thank you though! That seems to of done the trick, though the first time I tried launching, it didn't do so, and it didn't generate a crash report.
