### ISSUE TITLE
Android/Pojav Launcher support

### ISSUE THREAD

**Issue by Madis0** [FlashyReese/sodium-extra-fabric#281]
Currently Pojav Launcher works with latest Sodium on 1.19.2, as long as the renderer is set to ANGLE, but the video settings screen won't open. Could you add support for it through Extra?

Logs that can help: https://mclo.gs/7dAAOQH

**Comment by FlashyReese** [comment]
Well, I'm not going to explicitly support it but this can probably be a workaround with a mixin config change. Adding `mixin.adaptive_sync=false` and `mixin.sodium.vsync=false` to `.minecraft/config/sodium-extra.properties` should work in theory. I'm just judging based on the log.

**Comment by Madis0** [comment]
Hmm, that didn't help. 

For some reason, only [Better Sodium Video Settings](https://modrinth.com/mod/better-sdoium-video-settings-button) (aka, vanilla settings) work, not even the [Xander's Sodium Options](https://modrinth.com/mod/xanders-sodium-options) when paired with Sodium Extra.

**Comment by FlashyReese** [comment]
Do you have a log for those mixin config changes I mentioned?

**Comment by Madis0** [comment]
https://mclo.gs/wh6FuZE

**Comment by FlashyReese** [comment]
Sorry if you didn't see this earlier but I edited my original comment to include `mixin.sodium.vsync=false`.

**Comment by Madis0** [comment]
Works! So... does it have to be a manual option or could you have a relevant check for it?

**Comment by FlashyReese** [comment]
Well, It seems I can't check for Adaptive VSync extensions on OpenGL ES. I'm not sure what sorts of hacks the PojavLauncher team is doing.

**Comment by Madis0** [comment]
Alright. 

**So, for anyone looking for the same:**

Make a file `sodium-extra.properties` with contents
```
mixin.adaptive_sync=false
mixin.sodium.vsync=false
```
in `.../.minecraft/config/`.
