### ISSUE TITLE
NPE related to fog when attempting to join any world.

### ISSUE THREAD

**Issue by gomhaille** [FlashyReese/sodium-extra-fabric#283]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.12

### Sodium version.

0.4.4

### What happened?

When I attempt to join either a single-player world, or a multi-player world, the game crashes with an NPE with what appears to be a relation to fog. I'm assuming this relation based on the line `net.minecraft.class_758.handler$zlb000$applyFog(class_758.java:1028)` in the crash reports attached below.

I've verified it is Sodium Extra, by launching the game with only Sodium, Fabric API, and this mod. Removing/disabling Sodium Extra allows me to join worlds without issues. Also, downgrading to Sodium Extra 0.4.11 allows me to join worlds; something in the 0.4.12 update is what appears to be the issue.

### Relevant logs

Two identical crashes for you, in different worlds:
* Single-player world: [crash-2022-11-19_05.36.38-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/10047127/crash-2022-11-19_05.36.38-client.txt)
* Multi-player world: [crash-2022-11-19_05.39.42-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/10047128/crash-2022-11-19_05.39.42-client.txt)

### Additional information

The only related issue I was able to find seems to be #280, however it was regarding a mod conflict which is irrelevant in this case.

**Comment by FlashyReese** [comment]
Can you try and see if this build resolves your issue?
[sodium-extra-0.4.12+mc1.19.2-issues-283.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/10047837/sodium-extra-0.4.12%2Bmc1.19.2-issues-283.zip)

**Comment by gomhaille** [comment]
> Can you try and see if this build resolves your issue? [sodium-extra-0.4.12+mc1.19.2-issues-283.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/10047837/sodium-extra-0.4.12%2Bmc1.19.2-issues-283.zip)

Yup, that fixes the issue @FlashyReese. Thank you.
