### ISSUE TITLE
Firework's particles crash the game when Particles were disabled

### ISSUE THREAD

**Issue by Scarlaid** [FlashyReese/sodium-extra-fabric#284]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.12

### Sodium version.

v0.4.4.build18

### What happened?

I have a weird crash and I think it was caused by Sodium Extra, as far as I have tested 
So Sodium Extra has that **Particles** setting where you could disable or enable the particles, but for me somehow disabling the particles, specifically fireworks, crash the game, enabling it does not report any crash whatsoever 💀

### Relevant logs

The crash log (in Crashy): https://crashy.net/514nKqdlWn4MKjTucMaw
The crash log in files: [crash-2022-11-19_23.43.51-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/10047541/crash-2022-11-19_23.43.51-client.txt)

### Additional information

After this issue I reverted back to version 0.4.11 and it works fine
A video for further detail: https://streamable.com/upw27n
The **only** issue that related to my issue is this https://github.com/FlashyReese/sodium-extra-fabric/issues/283, because while having Particles disabled, the Fog setting also affected, enabling back the Particles seems to fix the issue 👀

**Comment by FlashyReese** [comment]
Try this build, it should be fixed now. 
[sodium-extra-0.4.12+mc1.19.2-issue-284.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/10047857/sodium-extra-0.4.12%2Bmc1.19.2-issue-284.zip)

**Comment by FlashyReese** [comment]
Fixed in the latest release.

**Comment by Scarlaid** [comment]
yep the latest and the one you sent fixed, cheers
