### ISSUE TITLE
The new version conflicts with origins_1.41

### ISSUE THREAD

**Issue by chen-Futuro** [FlashyReese/sodium-extra-fabric#287]
Sodium-extra-0.4.13+mc1.18.2-build.75 seems to conflict with origins_1.41, at the same time using them cannot enter the game, the game process and window are closed directly
And sodium-extra-0.4.11+mc1.18.2-build.67 can run normally
I am using 1.18.2Fabric and sodium-fabric-mc1.18.2-0.4.1+build.15

**Comment by FlashyReese** [comment]
The only workaround, for now, is adding `mixin.fog.falloff=false` to `.minecraft/config/sodium-extra.properties` and losing out the fog start multiplier functionality or downgrading since Sodium Extra `0.4.12+` and Origins both modify the same area of the game.

**Comment by chen-Futuro** [comment]
I already do that. Is it possible for later versions to fix this problem?

**Comment by FlashyReese** [comment]
Unless I remove the feature.

**Comment by chen-Futuro** [comment]
I have a suggestion, is it feasible to disable conflicting function modules if origins are detected at startup?

**Comment by FlashyReese** [comment]
I've already committed a patch for it, I will try to get a release out before 1.19.3 drops.

**Comment by FlashyReese** [comment]
This should be resolved in the latest release of `0.4.14`.
