### ISSUE TITLE
Sodium extra crashes at startup demanding fabric despite fabric being installed

### ISSUE THREAD

**Issue by MarkusPolska** [FlashyReese/sodium-extra-fabric#288]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.13-build.76

### Sodium version.

0.4.4-build.18

### What happened?

Crash while launching game. Fabric loader version 0.14.10

### Relevant logs

https://paste.gg/p/anonymous/83db3146ce6543af85601218a81986b7

### Additional information

**Update** The game launches fine after taking out Sodium Extra from the mods folder. Looks like the mod doesn't recognize the newest fabric version?

**Comment by FlashyReese** [comment]
You need to install Fabric API.

**Comment by MarkusPolska** [comment]
Thanks, installed it. Was the requirement for Fabric API recent? Because when I checked my mods folder for 1.19.1 i didn't see Fabric API in there.

**Comment by FlashyReese** [comment]
Since 1.19.2, I unbundled fabric api modules to avoid problems.
