### ISSUE TITLE
Sodium Extra and Iris Sodium rendering issues

### ISSUE THREAD

**Issue by Cozm0z** [FlashyReese/sodium-extra-fabric#296]
When trying to use Sodium Extra with Iris and Sodium, the game will render nothing but chests, everything else is invisible.

https://media.discordapp.net/attachments/1029886135750631447/1057249425149407293/2022-12-27_05.41.29.png?width=1276&height=671
With Sodium Extra plus Iris and Sodium

https://media.discordapp.net/attachments/1029886135750631447/1057249713281302578/2022-12-27_05.34.39.png?width=1276&height=671
Without Sodium Extra plus Iris and Sodium

**Comment by FlashyReese** [comment]
Can you upload your configuration file? It's located at `.minecraft/config/sodium-extra-options.json`. Also please list the versions of Sodium and Sodium Extra you are using or attach a relevant log of the game running with this issue.

Edit:
Perhaps deleting your current configuration might resolve your issue.

**Comment by Cozm0z** [comment]
My Sodium version is 1.19.2-0.4.4
My Sodium Extra is 0.4.15
No idea how to get to the config files so

**Comment by FlashyReese** [comment]
Try downgrading to this version instead https://github.com/FlashyReese/sodium-extra-fabric/releases/tag/mc1.19.2-0.4.10

**Comment by Cozm0z** [comment]
That'll do the trick, thanks for the help

**Comment by FlashyReese** [comment]
I still believe it might be configuration corruption or probably conflicting with some other mod that modifies the fog, a log file, and configuration would be appreciated to help diagnose this issue.
