### ISSUE TITLE
Crash with Sodium dev versions

### ISSUE THREAD

**Issue by Felix14-v2** [FlashyReese/sodium-extra-fabric#30]
[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/6527375/latest.log)
[crash-2021-05-23_04.01.58-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/6527376/crash-2021-05-23_04.01.58-client.txt)

Most likely it's Sodium's fault.

**Comment by FlashyReese** [comment]
You are using build 359, use this build instead. https://github.com/FlashyReese/sodium-extra-fabric/releases/tag/mc.1.16.5-0.3.0-next-compat

**Comment by Felix14-v2** [comment]
Excuse me, what build?

**Comment by FlashyReese** [comment]
The build I linked, and by build 359, I meant Sodium next build 359.

**Comment by Felix14-v2** [comment]
I keep getting crashes when trying to open graphics settings with Sodium Extra 0.3.0 and Sodium dev build361.
[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/6529167/latest.log)
[crash-2021-05-24_03.25.08-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/6529168/crash-2021-05-24_03.25.08-client.txt)
Removing SodiumOptions from sodium_extra.jar solves the problem.

**Comment by FlashyReese** [comment]
You aren't using the build I linked, https://github.com/FlashyReese/sodium-extra-fabric/releases/tag/mc.1.16.5-0.3.0-next-compat

The crash log you uploaded says that you are using the normal release.
