### ISSUE TITLE
Full Ukrainian translation

### ISSUE THREAD

**Issue by forditt** [FlashyReese/sodium-extra-fabric#301]
I play minecraft in Ukrainian and use sodium extra, noticing that it is almost not translated, I decided to fix it. I hope that you will add a translation in the next version. In the future, I will improve and supplement the translation.
[Link to translation ](https://drive.google.com/file/d/1zzhDNFhua6LU4Xy7dxrybOCgYNQq2J3D/view?usp=sharing)
![screenshot](https://user-images.githubusercontent.com/105544922/215263075-99ffdc61-1a75-45e5-850e-78767f0229b7.png)

**Comment by FlashyReese** [comment]
Please see https://github.com/FlashyReese/sodium-extra-fabric#contributing-to-localization

**Comment by forditt** [comment]
mm got it, ok
