### ISSUE TITLE
sodium extra rendering issue

### ISSUE THREAD

**Issue by pleist** [FlashyReese/sodium-extra-fabric#302]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.3

### Sodium Extra version.

0.4.16

### Sodium version.

0.4.8

### What happened?

when using sodium extra without shaders, nothing loads expect animals
![2023-01-28_22 47 43](https://user-images.githubusercontent.com/61575796/215290469-4cc17ffd-8536-4ee1-912c-71e5a90ea892.png)

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/10528264/latest.log)

**Comment by FlashyReese** [comment]
Does this occur with only Sodium and Sodium Extra? If not try a binary search while disabling other mods to see what it may be conflicting with.

Logs themselves doesn't seem to show anything related to Sodium Extra. I personally went through and downloaded all the mods listed in the log and I can't seem to replicate said issue.
![2023-01-29_05 56 12](https://user-images.githubusercontent.com/30311066/215292903-b1d72ee1-ef93-41bc-9e24-51e8e4f3dd52.png)
Only thing I can think of that can cause this is probably some mods setting conflicting it Sodium itself.

**Comment by pleist** [comment]
sodium extra is atleast causing the no rendering, if I remove sodium extra everything is fine. I am using amd gpu btw, I did try using other drivers but it did not help

**Comment by FlashyReese** [comment]
Does this occur with only Sodium and Sodium Extra? Could you please help me find out what other mods it's conflicting with I can't reproduce said the issue with the mods listed in the log? I also have an AMD GPU.

Edit: Sodium Extra itself does not touch any chunk rendering but it might conflict with other mods features.

**Comment by pleist** [comment]
you want me trying removing "x" mod and test if thats causing the problem?

**Comment by FlashyReese** [comment]
> you want me trying removing "x" mod and test if thats causing the problem?

Yes basically, from the list you can try disabling CameraUtils, Farsight, Bobby, and NoFade to see if it still occurs.

**Comment by pleist** [comment]
just removed indium and lithium now its working
actualy i am stupid i had shaders on

**Comment by FlashyReese** [comment]
Do you mean unsupported shaders?

**Comment by pleist** [comment]
If i have shaders on everything works but if i turn off shaders there is that rendering issue (image in the beginning)

**Comment by pleist** [comment]
uninstalled each of those, still rendering issue

**Comment by FlashyReese** [comment]
Can you upload your sodium extra config file at `.minecraft/config/sodium-extra-options.json`?

**Comment by pleist** [comment]
it says that file type is not supported
no i cannot

**Comment by FlashyReese** [comment]
Can you open with a notepad and copy and upload it?

**Comment by pleist** [comment]
[sodium-extra-option.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/10528415/sodium-extra-option.txt)

**Comment by FlashyReese** [comment]
Ah I see, change the Fog Start Multiplier to 100%
![image](https://user-images.githubusercontent.com/30311066/215294406-82824a59-b55c-4d7c-a451-e628c8efcc1d.png)

**Comment by pleist** [comment]
ah thanks m8
