### ISSUE TITLE
[Feature Request] Search Bar for Particles

### ISSUE THREAD

**Issue by Avakining** [FlashyReese/sodium-extra-fabric#303]
When playing a big mod pack there can be thousands of different particles, making it difficult to find the exact one you want to disable. Some way of searching or filtering (by mod that added it and/or name of the particle) would be greatly appreciated.

**Comment by FlashyReese** [comment]
As you know Sodium Extra is using Sodium's UI, and it doesn't include a component for textbox(and I don't have the passion to be writing one). So I can recommend using [Xander's Sodium Options](https://github.com/isXander/xanders-sodium-options/) if you'd like searchable options as it uses vanilla's GUI system.

**Comment by Madis0** [comment]
Implemented in [Reese's Sodium Options 1.6.0](https://modrinth.com/mod/reeses-sodium-options), which works with Sodium Extra. Add that as well
