### ISSUE TITLE
[linux/android]在安装这个mod的时候不能打开视频设置

### ISSUE THREAD

**Issue by UNKNOWPLR** [FlashyReese/sodium-extra-fabric#304]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.16

### Sodium version.

0.14

### What happened?

Cannot open video settings when installing this mod

### Relevant log.

Sorry, I can't capture the log.

### Additional information.

I am a foreign player, and English is translation software.

**Comment by UNKNOWPLR** [comment]
靠 才发现是中国人

**Comment by FlashyReese** [comment]
Delete your configuration in `.minecraft/config/sodium-extra-options.json`, I can't tell what's wrong without a log.

刪除 `.minecraft/config/sodium-extra-options.json` 中的配置，沒有記錄檔我無法判斷出什麼問題。

**Comment by FlashyReese** [comment]
Sorry I didn't see the title properly. Use this link https://github.com/FlashyReese/sodium-extra-fabric/issues/281 

**So, for anyone looking for the same:**

Make a file `sodium-extra.properties` with contents
```
mixin.adaptive_sync=false
mixin.sodium.vsync=false
```
in `.../.minecraft/config/`.

對不起，我沒有正確看到標題。 使用此鏈接 https://github.com/FlashyReese/sodium-extra-fabric/issues/281

**所以，對於任何尋找相同的人：**

製作一個包含內容的文件“sodium-extra.properties”
```
mixin.adaptive_sync=false
mixin.sodium.vsync=false
```
在 `.../.minecraft/config/` 中。
