### ISSUE TITLE
[Feature request] Add text shadow/background option for FPS counter/coordinates 

### ISSUE THREAD

**Issue by mhzen** [FlashyReese/sodium-extra-fabric#306]
In some circumstances the fps/coordinate hud is a bit hard to read since it's just plain white, so adding text shadow or a background option to it would be greatly appreciated since it will increase readability.

**Comment by FlashyReese** [comment]
This feature already exists.
![2023-02-19_15 58 55](https://user-images.githubusercontent.com/30311066/219936198-82f73c29-b050-488b-a6a4-0b13969684c4.png)

**Comment by mhzen** [comment]
ah, didn't see that, sorry for wasting your time
