### ISSUE TITLE
Update to 23w05a

### ISSUE THREAD

**Issue by pedro4666** [FlashyReese/sodium-extra-fabric#307]
Please update to version snapshot 23w05a

**Comment by FlashyReese** [comment]
We do not prioritize snapshots as they are not currently feasible within our allotted time frame.

**Comment by pedro4666** [comment]
but i need a sodium extra version for snapshot 23w05a

**Comment by pedro4666** [comment]
if you do snapshot 23w05a you are already added the new features where you will have less work

**Comment by FlashyReese** [comment]
Please note that fixing an issue for a specific snapshot does not guarantee that it will work for future snapshots. As a volunteer contributing my free time, I may not be able to fulfill every feature request. However, feel free to port it yourself and make a pull request.

**Comment by pedro4666** [comment]
but how do i get sodium extra for snapshot version 23w05a?

**Comment by pedro4666** [comment]
but it costs nothing to update, many people are looking for this version of extra sodium

**Comment by FlashyReese** [comment]
It costs me my time, once again feel free to port it and make a pull request.

**Comment by pedro4666** [comment]
but I don't know port

**Comment by pedro4666** [comment]
that's why I'm asked to update otherwise I would do it myself

**Comment by SuperPro148** [comment]
> but it costs nothing to update, many people are looking for this version of sodium extra
You know, it also costs nothing to learn Java and port it yourself ¯\_(ツ)_/¯
There are plenty of resources, documentation and even IDEs available online for free :p

**Comment by pedro4666** [comment]
why would I waste time learning Java when I own
mod lazybones can do this

**Comment by pedro4666** [comment]
why would I waste time learning Java, when the owner
mod lazybones can do this

**Comment by ccrvincent** [comment]
> why would I waste time learning Java, when the owner mod lazybones can do this

Pro tip: When asking someone who maintains a free resource (mod, website, etc.) to do something, calling them lazybones is not likely to have the response you're looking for.

Also, as a Java dev, "waste time learning Java" comes across as a bit of an insult to a sizable portion of my industry.

I'm not Reese, but I suggest you consider quitting digging this hole.

**Comment by intergrav** [comment]
why would he waste his time updating for a version that barely anybody is using/needs the mod for?

**Comment by FlashyReese** [comment]
Hey @pedro4666, I understand that you're interested in having an update to support snapshot 23w05a. However, as I previously mentioned, supporting snapshots is currently not possible for me within my available time frame. It's also not helpful to resort to personal attacks and insults. Our goal is to keep this community productive and respectful, so please refrain from making personal attacks in the future.

As the owner of this project, I do my best to fulfill the feature requests, but I can't promise to deliver everything. However, I suggest that you try porting it yourself and making a pull request. This would be a great opportunity to learn and contribute to the project. Thanks for understanding.

**Comment by pedro4666** [comment]
@FlashyReese but how do i get sodium extra for snapshot version 23w05a?

**Comment by intergrav** [comment]
port it yourself :troll
