### ISSUE TITLE
CaffeineConfig is not marked as a library

### ISSUE THREAD

**Issue by Madis0** [FlashyReese/sodium-extra-fabric#308]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.3

### Sodium Extra version.

0.4.17+mc1.19.3-build.95

### Sodium version.

0.4.9+build.23

### What happened?

Sodium Extra bundles CaffeineConfig. CaffeineConfig is not marked as a library on Mod Menu:

![image](https://user-images.githubusercontent.com/8611110/222161903-55a7a2f5-66c9-4fff-8f1c-328c5da4416a.png)

The logs told me you are the one to include it (and not Sodium or Lithium), so here I am, blaming you 😁 

### Relevant log.

https://mclo.gs/RJoq8gz

**Comment by FlashyReese** [comment]
Should be done already in the latest releases.
