### ISSUE TITLE
Crashes when opening the video settings

### ISSUE THREAD

**Issue by andywithcatz** [FlashyReese/sodium-extra-fabric#31]
crash log: https://paste.ee/p/fFGQ9

basically it opens for a few settings, then crashes

**Comment by FlashyReese** [comment]
You are using the `sodium-extra-0.3.0-next-compat.jar`. Use the release found [here](https://github.com/FlashyReese/sodium-extra-fabric/releases/tag/mc.1.16.5-0.3.0).

**Comment by srnyx** [comment]
> You are using the `sodium-extra-0.3.0-next-compat.jar`. Use the release found [here](https://github.com/FlashyReese/sodium-extra-fabric/releases/tag/mc.1.16.5-0.3.0).

Could you update the file on CurseForge so that it isn't `sodium-extra-0.3.0-next-compat.jar`?

**Comment by MithicSpirit** [comment]
I have the same issue, even using the release you linked to.

**Comment by MithicSpirit** [comment]
Upon further testing, the issue appears to be with Reese's Sodium Options. Manually building it from the `next-compat` branch fixes the issue.

**Comment by FlashyReese** [comment]
Resolved in 3a3d8f47e0d1383c9efbafb7c77257e839ca140a
