### ISSUE TITLE
About 3D Textures

### ISSUE THREAD

**Issue by yuuyuu6250** [FlashyReese/sodium-extra-fabric#310]
I am Japanese and my English is not good. This is using deepL.

I wrote the same question to Sodium. I am having trouble using the 3D model in Sodium Extra.
If it is available please let me know the settings and any additional mods.
If it's not available, I'd like to add that setting.

**Comment by Madis0** [comment]
Sodium Extra does not do anything with 3D models... You can use vanilla model editing features for that.
