### ISSUE TITLE
Minecraft Crashes when Sodium Extra is Enabled

### ISSUE THREAD

**Issue by Anonymas-Doge** [FlashyReese/sodium-extra-fabric#313]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.16

### Sodium version.

0.4.4

### What happened?

Whenever I open Minecraft with Sodium Extra enabled it crashes.  Minecraft opens briefly before crashing.

### Relevant logs

https://paste.ee/d/i8m3r

### Additional information

I am using the Multimc launcher and I have the latest version of fabric installed.
Mods:
  [✔️] advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar
  [✔️] alternate-current-mc1.19-1.5.0.jar
  [✔️] animatica-0.5+1.19.jar
  [✔️] antighost-1.19.1-forge42.0.1-1.1.3.jar
  [✔️] betterbeds-1.2.0.jar
  [✔️] betterfpsdist-fabric-1.19-2.4.jar
  [✔️] capes-1.5.2+1.19.2-forge.jar
  [✔️] cem-0.7.3-1.19.jar
  [✔️] Chunky-1.3.38.jar
  [✔️] cloth-config-8.2.88-fabric.jar
  [✔️] Clumps-fabric-1.19.2-9.0.0+14.jar
  [✔️] continuity-2.0.2+1.19.jar
  [✔️] cullclouds-0.1.0.jar
  [✔️] CullLessLeaves-1.0.6.jar
  [✔️] dashloader-4.1.3+1.19.jar
  [✔️] Debugify-2.8.0.jar
  [✔️] DimThread-1.2.7.jar
  [✔️] dynamic-fps-2.2.0.jar
  [✔️] Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0.jar
  [✔️] entity_texture_features_fabric_1.19.2-4.3.3.jar
  [✔️] entityculling-fabric-1.6.1-mc1.19.2.jar
  [✔️] exordium-fabric-1.0.2-mc1.19.2.jar
  [✔️] fabric-api-0.76.0+1.19.2.jar
  [✔️] fabric-chunkpregen-0.3.5.jar
  [✔️] fabric-language-kotlin-1.9.2+kotlin.1.8.10.jar
  [✔️] fabricskyboxes-0.6.2+mc1.19.2.jar
  [✔️] fabrishot-1.9.1.jar
  [✔️] fast-chest-1.3+1.19.jar
  [✔️] Fastload+1.19.2-2.6.11.jar
  [✔️] ferritecore-5.0.3-fabric.jar
  [✔️] FixMySpawnR-fabric-1.19.2-1.1.3.jar
  [✔️] forgetmechunk-1.0.4-1.18.X-1.19.X.jar
  [✔️] fsb-interop-1.1.3+mc1.19.2-build.25.jar
  [✔️] indium-1.0.9+mc1.19.2.jar
  [✔️] iris-mc1.19.2-1.5.2.jar
  [✔️] item-model-fix-1.0.3+1.19.jar
  [✔️] krypton-0.2.1.jar
  [✔️] lambdabettergrass-1.3.0+1.19.jar
  [✔️] lambdynamiclights-2.2.0+1.19.2.jar
  [✔️] lazydfu-0.1.3.jar
  [✔️] lazy-language-loader-0.3.1.jar
  [✔️] lithium-fabric-mc1.19.2-0.11.1.jar
  [✔️] lunade-fastanim-1.5.7.jar
  [✔️] memoryleakfix-1.19.3-0.8.0.jar
  [✔️] MixinConflictHelper-1.2.0.jar
  [✔️] mixintrace-1.1.1+1.17.jar
  [✔️] modmenu-4.1.2.jar
  [✔️] optigui-1.1.6.jar
  [✔️] Particle-Blocker.jar
  [✔️] puzzle-1.4.2-1.19.jar
  [✔️] reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
  [✔️] servercore-1.3.3-1.19.2.jar
  [✔️] smoke-suppression-1.0.13+MC1.19-1.19.2.jar
  [✔️] smoothboot-fabric-1.19-1.7.1.jar
  [✔️] smoothchunk-fabric-1.19.1-2.0.jar
  [✔️] sodium-extra-0.4.16+mc1.19.2-build.90.jar
  [✔️] sodium-fabric-mc1.19.2-0.4.4+build.18.jar
  [✔️] starlight-1.1.1+fabric.ae22326.jar
  [✔️] vmp-fabric-mc1.19.2-0.2.0+beta.7.28-all.jar
  [✔️] YetAnotherConfigLib-2.2.0-for-1.19.2.jar
  [✔️] Zoomify-2.9.0.jar

**Comment by EuropaYou** [comment]
Particle Blocker and Sodium-Extra are not compatible with each other. Deleting either one solves the problem.

**Comment by Anonymas-Doge** [comment]
> 

Thank you
