### ISSUE TITLE
Feature request: Dirt Path shadow

### ISSUE THREAD

**Issue by Draacoun** [FlashyReese/sodium-extra-fabric#316]
As stated in this issue https://github.com/CaffeineMC/sodium-fabric/issues/50, Sodium won't be fixing the missing shadow, and it would be nice if Sodium Extra reimplements that to keep the vanilla style.

![2023-04-16_18 20 11](https://user-images.githubusercontent.com/47063486/232345449-1e4db2ae-b849-44d0-a49d-ea5a7dc5642d.png)

**Comment by FlashyReese** [comment]
Use [SSPB](https://www.curseforge.com/minecraft/mc-mods/sodium-shadowy-path-blocks). I won't be adding back a vanilla bug nor stripping out a significant amount of optimizations just for shadowy paths.
