### ISSUE TITLE
You require Sodium 0.4.11 when that version does not exist yet. Latest is 0.4.10+build.24

### ISSUE THREAD

**Issue by NopeProsOnly** [FlashyReese/sodium-extra-fabric#323]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.4

### Sodium Extra version.

0.4.19+mc1.19.3-build.101

### Sodium version.

0.4.10+build.24

### What happened?

The game crashed because sodium-extra requires a version of sodium that isn't out yet.

### Relevant log.

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.10+build.24 with version 0.4.11 or later.
Unmet dependency listing:
	 - Mod 'Sodium Extra' (sodium-extra) 0.4.19+mc1.19.3-build.101 requires version 0.4.11 or later of mod 'Sodium' (sodium), but only the wrong version is present: 0.4.10+build.24!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by FlashyReese** [comment]
![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/30311066/ecb4ea51-17cb-4cf2-bc17-8148bd1f178f)


The reason it is still up is because some users probably have that version already or some users are intentionally using that version, so it's still up on GitHub/Modrinth/CurseForge. I have already marked this release as alpha on MR and CF, and I have archived it on CF but MR doesn't have any archival feature yet.

**Comment by mja00** [comment]
> MR doesn't have any archival feature yet.

It looks like they do but it's only a flag on the API. Probably need to reach out to one of their moderators to get it archived unfortunately.

**Comment by KB-Q** [comment]
This is still an issue, sodiumextra keeps demanding sodium-0.4.11 when the latest version downloadable from Modrinth is 0.4.10. Please fix it. Thanks

**Comment by FlashyReese** [comment]
Please refer to my comment above.
