### ISSUE TITLE
Sodium Extras Crashing 

### ISSUE THREAD

**Issue by Slurdo9** [FlashyReese/sodium-extra-fabric#324]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.4

### Sodium Extra version.

0.4.18

### Sodium version.

0.4.11

### What happened?

I only use 3 mods [ Sodium, Sodium Extra, Fabric API ]. It is only crashing while using sodium extra please fix this as soon as possible

### Relevant logs

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_31548()" because "this.field_3712.field_1724" is null

### Additional information

![Uploading Screenshot (5).png…]()

**Comment by FlashyReese** [comment]
Either downgrade Sodium to `0.4.10` or update [Sodium Extra to `0.4.19`](https://github.com/FlashyReese/sodium-extra-fabric/releases/tag/mc1.19.3-0.4.19). Sodium `0.4.11` has plenty of issues and you should really not use it.

**Comment by Slurdo9** [comment]
Thanks Really Means alot
