### ISSUE TITLE
I turned off explosion particles in the settings and my game dont open no more

### ISSUE THREAD

**Issue by DxlqXD** [FlashyReese/sodium-extra-fabric#325]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.2

### Sodium Extra version.

sodium-extra-0.4.16mc1.19.2-build.90.jar

### Sodium version.

sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### What happened?

ok so basically I went to my settings, and went to particle (the mods im using are: lithium + sodium + sodium extra + reese sodium options) and I turned off the explosion particles and my game crashed, i was on 1.19.3... my game crashed and i couldn't reopen it... i tried reinstalling feather + repairing it and it did not work... then I switched to 1.19.2 and all my mods work other than sodium extra, it legit crashes when i try to open it... mc opened with all the mods on and it would just loop the feather logo that transitions into main menu at start of launch of MC... and so now I legit cant even open minecraft with sodium extra.. AND I REALLY NEED IT NGL, anyways please help me out

### Relevant logs

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/11658868/latest.log)

### Additional information

i own many minecraft servers and I really need to be active... please I need help (Dxlq#8357) is my discord if u want to contact me

**Comment by FlashyReese** [comment]
Your configuration file got corrupted while trying to save I think. You can remove it from `.minecraft/config/sodium-extra-options.json`.
