### ISSUE TITLE
Crash on launch or when opening a world/server

### ISSUE THREAD

**Issue by sszYchaa** [FlashyReese/sodium-extra-fabric#330]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.4

### Sodium Extra version.

0.4.18+build.99

### Sodium version.

0.4.10+build.24

### What happened?

When i tried launching minecraft with Sodium Extras, Reeses sodium options and some other mods which worked fine before, i get a toast saying "Failed to reload recources" and my texture pack gets disabled, when i try to reenable it i get the same toast and the pack is still not enabled. When i try to enter any world/server i get a crash. But when i disable Reeses Sodium Options the game just crashes on launch. I didn't really know whether i should report a crash here or on Reeses sodium options' github

### Relevant logs

When using RSO (entering a world)
Log: https://paste.ee/p/ng8xc 
Crash report: https://paste.ee/p/sPC2x
When not using RSO (on launch)
Log: https://paste.ee/p/8vh3k
Crash report: https://paste.ee/p/xc3re

### Additional information

Mods folder: https://www.mediafire.com/file/tt5l5cz5ik8kioq/mods.zip/file 
Recording of the crashes: https://www.mediafire.com/file/fpzairwwzcd4u63/2023-06-30_17-05-19.mkv/file

**Comment by FlashyReese** [comment]
You are using the 1.19.3 version on 1.19.4. Update your mod to this version: https://modrinth.com/mod/sodium-extra/version/mc1.19.4-0.4.18
