### ISSUE TITLE
Sodium Extra crashing feather launcher

### ISSUE THREAD

**Issue by PrinceSoap** [FlashyReese/sodium-extra-fabric#334]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.16

### Sodium version.

0.4.4

### What happened?

Using these mods together has worked for me for a while. Then, I must of changed a setting or something, because whenever I turn on sodium extra, even with only sodium and sodium extra, my game crashes and it says game launching stalled.

### Relevant logs

anti-auto-totem: Anti Auto Totem 1.0-SNAPSHOT
		betterhurtcam: BetterHurtCam 1.5.5
			betterhurtcam-mc119: BetterHurtCam+mc1.19 1.5.5
		clickcrystals: ClickCrystals 1.19.2-0.8.6
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		controlling: Controlling For Fabric 10.0+7
		custom_hud: CustomHud 3.1.0+1.19.2
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		dynamicviewmodel: Dynamicviewmodel 1.0-SNAPSHOT
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.21
		fakemoney: fakemoney 1.0.0
		feather: Feather Client 1.0.0-SNAPSHOT
		inventoryhud: Inventory HUD + 3.4.7
		java: OpenJDK 64-Bit Server VM 17
		malilib: MaLiLib 0.13.0
		marlows-crystal-optimizer: Marlow's Crystal Optimizer 1.0.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.2.0-beta.2
		morecosmetics: MoreCosmetics 1.2
		nohurtcamplus: NoHurtCam+ 2.1.0-1.19.4
		oldwalkinganimation: Old Walking Animation 1.1.0
		quick_elytra: Quick Elytra 3.0.2
		replaymod: Replay Mod 1.19.2-2.6.10
		showdurability: Show Durability 1.1.0+1.19
		shulkerboxtooltip: Shulker Box Tooltip 3.2.2+1.19.2
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		tier-tagger: TierTagger 1.4
		ukulib: ukulib 0.6.1+1.19.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		xaerominimap: Xaero's Minimap 22.16.2
	Launched Version: 1.19.2-feather
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.40, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'Feather Fabric'
	Type: Client (map_client.txt)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
info: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\(my user)\AppData\Roaming\.minecraft\crash-reports\crash-2023-07-17_10.20.33-client.txt
info: [2023-07-17T17:20:34Z INFO  rust_launcher::start::bindings] launch stalled

### Additional information

i turned off all my mods but sodium and sodium extra and it happens also sodium works fine its just sodium extra

**Comment by FlashyReese** [comment]
Please upload crash log located at `C:\Users(my user)\AppData\Roaming.minecraft\crash-reports\crash-2023-07-17_10.20.33-client.txt`

**Comment by PrinceSoap** [comment]
it says it doesnt exist

**Comment by FlashyReese** [comment]
Without a proper crashlog I can't really help you. Considering you said it was working fine, either your config got corrupt or something else happen. You can try deleting your configs at `.minecraft/config`.

**Comment by PrinceSoap** [comment]
it works!!!!! thx!!!!11
