### ISSUE TITLE
smithing table bug

### ISSUE THREAD

**Issue by Latino2k7** [FlashyReese/sodium-extra-fabric#337]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.4.24

### Sodium version.

0.4.10

### What happened?

sodium extra broke the animatic icons inside the smithing table 
![Screenshot 2023-07-31 050442](https://github.com/FlashyReese/sodium-extra-fabric/assets/37272834/d52bccd2-fcdf-4b71-8635-f3c382e4045f)

### Relevant log.

n/a

**Comment by FlashyReese** [comment]
Add `mixin.optimizations.draw_helpers=false` to `.minecraft/config/sodium-extra.properties` for a temporary fix. I will look into this later.

**Comment by FlashyReese** [comment]
Fixed in https://github.com/FlashyReese/sodium-extra-fabric/releases/tag/mc1.20.1-0.4.25
