### ISSUE TITLE
F3 Screen's FPS is higher than Show FPS

### ISSUE THREAD

**Issue by HowardZHY** [FlashyReese/sodium-extra-fabric#344]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.5.0

### Sodium version.

0.5.0

### What happened?

![2023-08-05_15 48 39](https://github.com/FlashyReese/sodium-extra-fabric/assets/96782166/42bbcb45-d4c0-4589-8a1f-33ac19cfbec7)
![2023-08-05_15 48 52](https://github.com/FlashyReese/sodium-extra-fabric/assets/96782166/f98509f1-1436-4b9f-a5e8-3932a4eafa1f)
When opened F3, the fps is 100 higher than Show FPS option's shown fps

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/12266499/latest.log)

**Comment by FlashyReese** [comment]
Just so you realize that it takes resources to also render your mini-map.

Especially the icons... and I use the same FPS counter from the game which can be seen here

https://github.com/FlashyReese/sodium-extra-fabric/assets/30311066/175badde-e271-4e6f-aa5f-ae1d9afec0e4
