### ISSUE TITLE
Update to 0.5.1

### ISSUE THREAD

**Issue by Slooshie1** [FlashyReese/sodium-extra-fabric#348]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.5.0 build 111

### Sodium version.

0.5.1

### What happened?

Game crashes upon joining a world. I assume this is because Sodium Extra needs an update for Sodium 0.5.1

### Relevant logs

https://mclo.gs/oTDXYr9 (latest.log)
https://mclo.gs/wmz3gId (crash report)

**Comment by 4unduck** [comment]
same bro

**Comment by NotDarkn** [comment]
issue occurs for me as well

**Comment by 4unduck** [comment]
just downgrade sodium to 0.5.0 if you want it to work

**Comment by NotDarkn** [comment]
> just downgrade sodium to 0.5.0 if you want it to work

i know, but i decided to just delete Sodium Extra till it updates

**Comment by NotDarkn** [comment]
seems they just updated for 0.5.1

i just installed it and it seems to work as well, so yeah
