### ISSUE TITLE
idk,but can you try to fix this?

### ISSUE THREAD

**Issue by sihuantianyu2020** [FlashyReese/sodium-extra-fabric#349]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.5.0

### Sodium version.

0.5.1

### What happened?

I don't know why,but when i update all my mods and try to play,i find that the sodium extra didn't  work with the mod voxelmap,so i was crazy about that.

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/12331803/latest.log)

### Additional information.

![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/106470249/1190e22c-2452-49db-8fc4-b1601c382711)

**Comment by FlashyReese** [comment]
#348

**Comment by sihuantianyu2020** [comment]
emmmm,with some simple tests,the game crashed after i enabled the mod sodium extra,so i think it need more discussion

**Comment by FlashyReese** [comment]
Update Sodium Extra to `0.5.1`
