### ISSUE TITLE
Join server = Crash

### ISSUE THREAD

**Issue by inlovewithgoths** [FlashyReese/sodium-extra-fabric#350]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.5.0

### Sodium version.

0.5.1

### What happened?

Game crashes upon joining a multiplayer server.

### Relevant logs

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/12332088/latest.log)

**Comment by FlashyReese** [comment]
#348
