### ISSUE TITLE
Stuck on 2 chunks when turning off fog

### ISSUE THREAD

**Issue by Tatertot5s** [FlashyReese/sodium-extra-fabric#351]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.5.1

### Sodium version.

0.5.1

### What happened?

When turning off fog by sliding the single fog slider to the right, it acts as you turned it to 1 chunk, but without the fog. (even if you have 32 chunks, it only shows the ones next to you, vertically)

What should happen, is that it just turns off fog entirely, and acts like its on loads up to 32 chunks.

### Relevant log.

not sure how relevant the log is but here
https://pastebin.com/LpddZ6ES

**Comment by FlashyReese** [comment]
I simply ask you to read the changelog in https://github.com/FlashyReese/sodium-extra-fabric/releases/tag/mc1.20.1-0.5.1
