### ISSUE TITLE
Chunks don't render properly when fog is disabled

### ISSUE THREAD

**Issue by Kavin7k** [FlashyReese/sodium-extra-fabric#353]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.5.1

### Sodium version.

0.5.1

### What happened?

Chunks don't render properly when fog is disabled. Tested with both single fog and multidimension fog enable
![2023-08-16_00 21 26](https://github.com/FlashyReese/sodium-extra-fabric/assets/70807843/c701ee07-19b1-4683-8399-c45fed3026b0)
![2023-08-16_00 21 28](https://github.com/FlashyReese/sodium-extra-fabric/assets/70807843/b63b3928-7c4f-4872-9fb7-bf4d4e44bdfb)
![2023-08-16_00 21 59](https://github.com/FlashyReese/sodium-extra-fabric/assets/70807843/d8756edb-293e-4ee0-be04-df704f96242c)
![2023-08-16_00 22 31](https://github.com/FlashyReese/sodium-extra-fabric/assets/70807843/68a04a69-ffb2-46f8-9e3f-232530b85db1)
![2023-08-16_00 22 52](https://github.com/FlashyReese/sodium-extra-fabric/assets/70807843/3e938676-0151-494a-ab88-96751f4fa059)
d.

### Relevant log.

https://gist.github.com/Kavin7k/89ebd6a297ae50a79f38dcb6ec5f73c7

**Comment by FlashyReese** [comment]
![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/30311066/2e72a8ca-f0c5-420f-bcfa-be38dc56b7ee)
![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/30311066/cf4f9f8a-b788-4062-ac08-942f9fe9517a)
Not our fault, this is a bug caused by **Sodium 0.5.1**.
