### ISSUE TITLE
Chunks won't load after 2 to 3 chunks

### ISSUE THREAD

**Issue by DeadbushCarrot** [FlashyReese/sodium-extra-fabric#354]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.1

### Sodium Extra version.

Sodium Extra 0.5.1 for Minecraft 1.20.1

### Sodium version.

Sodium 0.5.1

### What happened?

Chunks wont load past like 2 to 3 and I test with only these mods
fabric-api-0.87.0+1.20.1
modmenu-7.2.1
reeses_sodium_options-1.6.4+mc1.20.1-build.94
sodium-extra-0.5.1+mc1.20.1-build.112
sodium-fabric-mc1.20.1-0.5.1
sodium-shadowy-path-blocks-3.2.0

### Relevant log.

[latest-log.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/12353696/latest-log.zip)

### Additional information.

![2023-08-15_16 28 22](https://github.com/FlashyReese/sodium-extra-fabric/assets/109874700/2ab76038-da05-47b0-9866-e6db909b4467)
![2023-08-15_16 28 26](https://github.com/FlashyReese/sodium-extra-fabric/assets/109874700/d7cfb7d0-f4fb-45f8-99cd-d4225b013f6f)
![2023-08-15_16 28 27](https://github.com/FlashyReese/sodium-extra-fabric/assets/109874700/0f5f6522-a005-4b6f-a550-c552f9660f1b)

**Comment by FlashyReese** [comment]
https://github.com/FlashyReese/sodium-extra-fabric/issues/353#issuecomment-1679442194
