### ISSUE TITLE
Max fog distance incompatibility with Nvidium mod, causing blacked out terrain

### ISSUE THREAD

**Issue by Synnef-8826** [FlashyReese/sodium-extra-fabric#363]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.2

### Sodium Extra version.

0.5.2

### Sodium version.

0.5.3

### What happened?

<sub>*[Nvidium 0.2.0](https://modrinth.com/mod/nvidium) is a Sodium rendering engine used to greatly increase performance on systems with certain NVIDIA graphics cards.*</sub>

Pretty much the title. Setting the max fog distance to the maximum (so, disabling fog) causes faraway terrain *that'd otherwise be hidden by fog* to fade out to all black. Other mods [(example)](https://modrinth.com/mod/bactromod) that disable fog don't seem to cause this problem.

### Examples:
*The vanilla fog in the Nether is thicker by design (and slightly different to the Overworld's), leading to this. Note how entities that technically are within my render distance are rendered properly.*
![](https://github.com/FlashyReese/sodium-extra-fabric/assets/106876032/2342dd12-da2e-4116-8257-6b41545018d8)

*Fresh instance with just Nvidium, Sodium and Sodium Extra (meaning there are no other incompatibilities). Notice the black terrain.*
![2023-10-14_09 34 37](https://github.com/FlashyReese/sodium-extra-fabric/assets/106876032/7483575b-ba48-4b6a-aa9e-0a98b3cb2ae8)

*Same world/instance, but fog distance reverted to default. The terrain that was previously black is now completely hidden by the fog.*
![](https://github.com/FlashyReese/sodium-extra-fabric/assets/106876032/9a18665e-7145-4b37-8391-ceb9a5690030)

### Relevant log.

No log is required to observe the issue

### Additional information.

My best assumption is that the method Sodium Extra uses to change fog distance does not integrate well with alternative rendering engines, and rather focuses on *just* Sodium's default rendering. I think it should be changed, seeing how alternative mods can already change fog regardless of rendering engine, and how Sodium Extra is considered the go-to and most popular option for disabling fog on Fabric.

**Comment by FlashyReese** [comment]
This is technically a bug on Nvidium's end. They are using their own fog fragment shader which doesn't account for the alpha component of the fog color. Cortex contacted me about it, and it should be resolved in their next release.

![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/30311066/2414c6e9-6205-421a-aea4-2e21ca6d70ef)

I was previously using a method of setting fog distance for very large distances (this is the method most fog-modifying mods use). However, I stopped using that method because it would drastically affect frame times in 0.5.x if you go above world height. Therefore, JellySquid suggested that I modify the fog alpha instead.

**Comment by Synnef-8826** [comment]
Ah, perfect then! I did reach out to Cortex on Nvidium's issue page before ending up here, so it makes sense why he wrote you as well. Unfortunately I don't have the skills to dive into both mods' code and figure out who's problem it was, so I thought I'd ask around on both ends :p

Either way, thanks for replying! I'm glad it's solved now.

**Comment by MCRcortex** [comment]
You should be able to close this now as i have released 0.2.1 which should fix it

**Comment by FlashyReese** [comment]
Thank you for resolving this.
