### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by PowerRubik** [FlashyReese/sodium-extra-fabric#364]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.2

### Sodium Extra version.

0.5.2

### Sodium version.

0.5.3

### What happened?

When i join a server, the various stages of connecting to the server (connecting to server, encrypting etc.) overlaps with the cancel button (i have a gui scale of 2, if i put it at 3 its normal).
![2023-10-19_14 27 05](https://github.com/FlashyReese/sodium-extra-fabric/assets/126591243/e1f7e332-e3cc-4c82-a0af-87de2180d634)

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/13042597/latest.log)

**Comment by FlashyReese** [comment]
I don't modify this area of the game, unless you can reproduce this with only Sodium and Sodium Extra.
