### ISSUE TITLE
Clouds disappear after Single Fog distance set to 33 (disabled)

### ISSUE THREAD

**Issue by HowardZHY** [FlashyReese/sodium-extra-fabric#366]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.2

### Sodium Extra version.

0.5.3

### Sodium version.

0.5.3

### What happened?

![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/96782166/181c1ebc-105f-4398-b24c-d8d746ce8cc1)
![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/96782166/39367223-7e34-4f7f-a993-c6db3b775736)

### Relevant log.

https://mclo.gs/aXEd1oA

**Comment by FlashyReese** [comment]
This is an issue with Sodium's own cloud renderer, you can disable Sodium's cloud renderer by adding `mixin.features.render.world.clouds=false` to `.minecraft/config/sodium-mixins.properties`.

Edit: This is not an issue with vanilla's cloud renderer.
