### ISSUE TITLE
Request: Port the Cloud Distance addition and other new things to 1.20.1

### ISSUE THREAD

**Issue by VeggeieDude** [FlashyReese/sodium-extra-fabric#368]
Hello! I was wondering if you were gonna port the new features on 1.20.2 to 1.20.1? Specifically the new cloud distance feature!

**Comment by FlashyReese** [comment]
Currently, my schedule is full with other commitments and some personal tasks that need my immediate attention. Perhaps in the future, I'll be able to address this.
