### ISSUE TITLE
Clouds don't render

### ISSUE THREAD

**Issue by DeadbushCarrot** [FlashyReese/sodium-extra-fabric#370]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.4

### Sodium Extra version.

Sodium Extra 0.5.3 for Minecraft 1.20.4

### Sodium version.

Sodium 0.5.5

### What happened?

The clouds don't render no matter what your setting are

### Relevant log.

With the mod
![2023-12-11_16 58 35]
(https://github.com/FlashyReese/sodium-extra-fabric/assets/109874700/0dc6bf69-4d15-4cbb-b22c-6ded1bbd4e8c)
Without the mod
![2023-12-11_16 59 44](https://github.com/FlashyReese/sodium-extra-fabric/assets/109874700/1d6cd6a8-6e89-4910-b96b-3999042d92f3)

**Comment by AagneyS** [comment]
same issue here

**Comment by FlashyReese** [comment]
https://github.com/FlashyReese/sodium-extra-fabric/issues/366#issuecomment-1804903528
