### ISSUE TITLE
Make the FPS counter text shaded for better readability

### ISSUE THREAD

**Issue by mrjasonn** [FlashyReese/sodium-extra-fabric#373]
Please make the FPS counter text shaded for better readability for in areas in a world that are more white. An example of shaded text is in the F3 debug menu the text is shaded. If this affects FPS too much like the F3 debug menu, please just make the text shadowed (e.g. action bar).

**Comment by mrjasonn** [comment]
@FlashyReese please implement this as its really useful, it should not be too hard

**Comment by FlashyReese** [comment]
I'd like to, but my weekends are my only downtime during military service, and if they're all about updating mods and adding features; it's a bit tough. Hope you understand where I'm coming from.

P.S. This mod is open source you can always open a pull request and contribute to the project.

**Comment by mrjasonn** [comment]
Just found out actually this can already be done with setting the text background for Sodium Extra overlays, however it should enabled by default

**Comment by mrjasonn** [comment]
Made that suggestion in #376
