### ISSUE TITLE
Make the Sodium Extra text contrast setting enabled by default and make the background setting in the text contrast setting colour to be same as F3 Debug Menu

### ISSUE THREAD

**Issue by mrjasonn** [FlashyReese/sodium-extra-fabric#376]
Please make the Sodium Extra text contrast setting enabled by default and make the background setting in the text contrast setting colour to be same as F3 Debug Menu. I would personally recommend the background option be enabled by default, but if there are any major enough FPS drops (e.g. F3 Debug Menu) then it should be set to shadow mode and it really depends on which one you think looks nicer.

**Comment by christopherplaysminecraft** [comment]
In my opinion, it is fine as-is.

I think that it looks nicer without a shadow or background, it makes it look "cleaner"
For those that prefer to have a shadow or background, they can just activate it with a few simple clicks.
