### ISSUE TITLE
Iris compatibility might be broken

### ISSUE THREAD

**Issue by mrjasonn** [FlashyReese/sodium-extra-fabric#390]
Seems like its using the old class before the rename in Iris 1.7.0 `net.coderbot.iris.vertices.IrisVertexFormats` and there might be some other things as well broken with Iris 1.7.0, please check if that is the case

**Comment by FlashyReese** [comment]
![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/30311066/768e95dd-4474-4177-9c40-0ceaeaebe66d)
Seems fine on my end

**Comment by mrjasonn** [comment]
> ![image](https://private-user-images.githubusercontent.com/30311066/327062339-768e95dd-4474-4177-9c40-0ceaeaebe66d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDQ3ODEsIm5iZiI6MTcxNDU0NDQ4MSwicGF0aCI6Ii8zMDMxMTA2Ni8zMjcwNjIzMzktNzY4ZTk1ZGQtNDQ3NC00MTc3LTljNDAtMGNlYWVhZWJlNjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA2MjEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YzcxODhhOGE2YjJkNjU4MzQ3ZTVhZjBlYThmOTFhNDRkY2FhZjAzMWJkZjc2ZDY5MTBmYTM1ZjZjYWQ5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DisnqFp_6rIzlkO3t9MB6dMYtIN4RDD5yutnK7IFHcs) Seems fine on my end

hmm... I would suggest removing the compatibility class if you find out if not needed after a bit more investigation, and if it is still needed maybe update it to be future-proof

**Comment by mrjasonn** [comment]
@FlashyReese If you do some more testing on this (if you haven't yet or not enough including use more shader packs for test) and find out the compat is not needed, then the best choice might be to remove it (if not make it do nothing but still available for viewing)

**Comment by FlashyReese** [comment]
It's still needed I looked at Iris and it still has this in it.

**Comment by mrjasonn** [comment]
> It's still needed I looked at Iris and it still has this in it.

Hmm... @FlashyReese I have seen that the issues regarding this beacon compatibility with Iris have been just crashes and you haven't observed one (as you were able to take a screenshot of the beacon beam), so I think you may want to ask @IMS212 if anything can be removed with regards to Iris compat

**Comment by FlashyReese** [comment]
That won't be necessary; I have already released a fix for it. Removing the compatibility won't be possible unless I throw out the entire beacon beam rendering optimization. Also, please provide crash logs next time.

**Comment by mrjasonn** [comment]
> That won't be necessary; I have already released a fix for it. Removing the compatibility won't be possible unless I throw out the entire beacon beam rendering optimization. Also, please provide crash logs next time.

@FlashyReese I haven't experienced a crash as I have not even seen a beacon with shaders in 1.20.5 and 1.20.6, I was just trying to help by pointing out if there is an issue in the code.

**Comment by mrjasonn** [comment]
@FlashyReese because of the fact of what I have said above, if you haven't, you may want to investigate if Iris has actually made the compat not needed because Iris 1.7.0 did make a lot of changes to the code and might already contain what is needed.

**Comment by FlashyReese** [comment]
I already said I did so in https://github.com/FlashyReese/sodium-extra-fabric/issues/390#issuecomment-2088685366
