### ISSUE TITLE
confused on why this is happening

### ISSUE THREAD

**Issue by pkoverjr** [FlashyReese/sodium-extra-fabric#396]
![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/171203763/256f1f18-2837-4ddd-8722-3c8b693f7c29)

**Comment by FlashyReese** [comment]
According to https://github.com/CaffeineMC/sodium-fabric/issues/2522, it seems to be the Language Reload mod. You can replace it with [Lazy Language Loader](https://www.modrinth.com/mod/lazy-language-loader) if that is the case.
