### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by Hazardous544** [FlashyReese/sodium-extra-fabric#398]
Minecraft 1.21
Sodium Extra 0.5.7
Sodium 0.5.9

![2024-06-14_195457](https://github.com/FlashyReese/sodium-extra-fabric/assets/15476634/3f725665-d191-4aaa-9cdc-23bea906ba97)

Windows Defender:
Detected: Trojan:Win32/SuspExecRep.A!cl

**Comment by FlashyReese** [comment]
It's a false positive, might be defender acting up. If you are concerned you can scan the file on [virustotal](https://www.virustotal.com/gui/url-analysis/u-ee5ff6831340140514a81fcc280acd9ee4aa240d2a3876614aeeaffa16114ca5-1718421685)
