### ISSUE TITLE
Please release the fix for beacon beam colour

### ISSUE THREAD

**Issue by mrjasonn** [FlashyReese/sodium-extra-fabric#399]
It would be much appreciated thanks

**Comment by FlashyReese** [comment]
![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/30311066/766d4405-4475-4342-9f4e-a3bfcf294760)

My computer is broken I can't release anything right now. I have to get replacement parts.

**Comment by mrjasonn** [comment]
> ![image](https://private-user-images.githubusercontent.com/30311066/341395107-766d4405-4475-4342-9f4e-a3bfcf294760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjQ3OTMsIm5iZiI6MTcxODk2NDQ5MywicGF0aCI6Ii8zMDMxMTA2Ni8zNDEzOTUxMDctNzY2ZDQ0MDUtNDQ3NS00MzQyLTlmNGUtYTNiZmNmMjk0NzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEwMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3Njg0M2U0MWEyNDExMTRlNjYwMDIwNTVkNGRjNzJmMzFkNTI2YTM3YzMyMjVkMzA0ZGIxNzMxODMyOTE1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QhdOA_Jm1L7JLCHk5jWo_oaDR8KYr7bHzBDwJWhp_3M)
> 
> My computer is broken I can't release anything right now. I have to get replacement parts.

Sorry to hear your computer is broken, but could you please release it using GitHub on your phone to run the script please? It's also not that hard to change the version numbers on phone. Thanks.

**Comment by FlashyReese** [comment]
Please build it yourself or use the GitHub Actions build. I'm not releasing it anytime soon, period. A release will be available when I deem it production-ready. Regarding the beacon color issue, I released a temporary fix for that a while ago in version `0.5.7` by disabling those optimizations.

You can't just come here and make requests without being reasonable. There have been multiple instances of you doing so, and I've already tried, in the nicest indirect way, to let you know in some of the past issues you've created.

You need to stop making demands or creating pointless issues/comments. This is your first and final warning: I will ban you from the issue tracker if you continue this behavior. This is an **issue tracker**, not a forum. It may look like one, but it is not.
