### ISSUE TITLE
[Feature Request] Neoforge Question

### ISSUE THREAD

**Issue by Silvertail4764** [FlashyReese/sodium-extra-fabric#405]
Since Sodium & Iris Shaders are in alpha builds for neo 1.20.1 $ 1.21, do you plan to add neo support? Or should that fall on embeddium/rubidium extras?

Thanks!!

**Comment by FlashyReese** [comment]
Support for NeoForge is coming. I don't support third party forks.

**Comment by Silvertail4764** [comment]
Cool, thank you so much for your work
