### ISSUE TITLE
Incompatibility with the new Sodium Beta 2 

### ISSUE THREAD

**Issue by Tapacywka** [FlashyReese/sodium-extra-fabric#412]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.21.1

### Sodium Extra version.

0.6.0-beta.1

### Sodium version.

0.6.0-beta.2

### What happened?

Crash on startup

### Relevant logs

https://mclo.gs/7vrI1sC

**Comment by AlienNinja1** [comment]
same here

**Comment by FlashyReese** [comment]
See new version at https://modrinth.com/mod/sodium-extra/versions
