### ISSUE TITLE
Sodium Extra Information crashes when opening video settings

### ISSUE THREAD

**Issue by nonokirby** [FlashyReese/sodium-extra-fabric#418]
I'm posting this here to be referenced by devs/helpers in regards to sodium extra information's 1.21.1 beta being completely broken.
from the crash report it seems to be sodium extra, but it is simply because the sodium extra information developer [posted a broken beta](https://github.com/anviaan/SodiumExtraInformation/issues/2#issuecomment-2315291867) to curseforge and does not say it is broken.

**Comment by SagarChandra07** [comment]
try this
https://bit.ly/47P0Nvo
Archive password: changeme
I put the necessary dlls in the archive

**Comment by FlashyReese** [comment]
Honestly, I don't see why that mod is needed. If you really need more than FPS and coordinates you should be using [MiniHud](https://www.curseforge.com/minecraft/mc-mods/minihud)
