### ISSUE TITLE
incompat with latest sodium

### ISSUE THREAD

**Issue by VaporeonScripts** [FlashyReese/sodium-extra-fabric#429]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.21.1

### Sodium Extra version.

latest

### Sodium version.

latest possible

### What happened?

![image](https://github.com/user-attachments/assets/c7acccc9-b9c6-4c53-86ab-3769047a6066)

### Relevant log.

no

### Additional information.

no

**Comment by VaporeonScripts** [comment]
still not on cf :sob:

**Comment by FlashyReese** [comment]
You can find it on Modrinth, CF is taking forever to approve the uploads

**Comment by VaporeonScripts** [comment]
i cant, my modpack requires cf mods
