### ISSUE TITLE
Error during pre-loading phase:

### ISSUE THREAD

**Issue by OBS3SS1ON** [FlashyReese/sodium-extra-fabric#430]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.21.1

### Sodium Extra version.

sodium-extra-neoforge-0.6.0-beta.3+mc1.21.1

### Sodium version.

sodium-neoforge-0.6.0+mc1.21.1

### What happened?

[latest.log](https://github.com/user-attachments/files/17791825/latest.log)Mod sodium_extra requires sodium 0.6.0-beta.2 or above, and below 0.6.0
Currently, sodium is 0.6.0+mc1.21.1
[crash-2024-11-17_15.04.20-fml.txt](https://github.com/user-attachments/files/17791826/crash-2024-11-17_15.04.20-fml.txt)

[[NeoForge] Sodium Extra 0.6.0 for Minecraft 1.21.3 in the web  I need 1.21.1 I have last update sodium-neoforge-0.6.0+mc1.21.1

### Relevant logs

[latest.log](https://github.com/user-attachments/files/17791836/latest.log)

**Comment by FlashyReese** [comment]
It's been updated, see GitHub releases or Modrinth. CF is taking long in approving the releases.
