### ISSUE TITLE
FPS counter additions.

### ISSUE THREAD

**Issue by K0-RR** [FlashyReese/sodium-extra-fabric#44]
Option to display min, avg, and max FPS below each other to make it obstruct the game less.
Option to disable additional info - without max, avg, and min as this can bother some players - takes much more space than just the current FPS.
Option to change the size of this text (IMO it's too big).

**Comment by K0-RR** [comment]
Also, shouldn't both these options (FPS counter and Coordinates) be disabled by default?

**Comment by DragonEggBedrockBreaking** [comment]
Also (copied from #38 because it would be better to put these together):

> The co-ordinates and FPS counter can get in the way of information from another mod, so being able to choose (in the video settings menu) where the info lines are located (top left - default, top right, bottom left, bottom right) would be nice.
