### ISSUE TITLE
Sodium Extra crashed my mc

### ISSUE THREAD

**Issue by ChickenKing1233** [FlashyReese/sodium-extra-fabric#45]
I dont know why my sodium extra crashed my mc when I click Video Setting. When it crash it appear Exit Code -1. I only have Sodium and Sodium Extra in the fabric loader, I used fabric 0.11.3, Can u have help me to fix this issue?

**Comment by Apprisco** [comment]
No logs, No nothing, what the hell man?
Github issues aren't for support, it's for bugs and errors.

**Comment by catgirldoll** [comment]
I can elaborate on this. Sodium-Extra is not currently compatible with dev branch Sodium 0.3.0:
`java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages` appears in the logs only when both are loaded. Subsequently, attempting to load `SodiumGameOptionPages` ingame will cause a crash.

The solution? Using [Reese's Sodium fork](https://github.com/FlashyReese/sodium-fabric/actions?query=branch%3A1.17.x) until the incompatibility is resolved.
