### ISSUE TITLE
Broken particle options with sodium extras

### ISSUE THREAD

**Issue by Apprisco** [FlashyReese/sodium-extra-fabric#46]
![image](https://user-images.githubusercontent.com/34324909/125030171-9cdf6f80-e0c5-11eb-98eb-28f7c64744fa.png)
I am not sure exactly how many particles this apply to, but I've tested a list of particles with the bubbles option:
Disabling (even only one) of rain splash, explosions , water, smoke, potions, portal, etc , while having bubbles also disabled, will enable bubbles in game although settings clearly mark them as disabled.
No errors in logs.
![image](https://user-images.githubusercontent.com/34324909/125030316-e760ec00-e0c5-11eb-9e27-0c251440b065.png)

**Comment by FlashyReese** [comment]
What version of Sodium Extra is this?

**Comment by Apprisco** [comment]
Latest on github actions.
