### ISSUE TITLE
Resolution Slider Inconvinent 

### ISSUE THREAD

**Issue by lenicyl** [FlashyReese/sodium-extra-fabric#49]
![image](https://user-images.githubusercontent.com/73347143/125575387-e106e79e-b28d-4468-aaaf-98568e858068.png)

Im bad at explaining my issue but from the screenshot above you can see that when you try to change the resolution, its from number 0 - 66. 
However its kinda inconvenient to change the resolution because the numbers 0-66 dont mean anything 
Could it please be changed to show the resolution the respective number so its more convenient ? 

Thank you

**Comment by FlashyReese** [comment]
Since I'm using hacky code to add that control. I can not change it, unless I replace it with a cycling control(ex. Attack Indicator).

**Comment by lenicyl** [comment]
> 
> 
> Since I'm using hacky code to add that control. I can not change it, unless I replace it with a cycling control(ex. Attack Indicator).

ah ok no worries 
good thing sodium doesnt update settings in real time else it would take me ages to change resolution
ill close this issue now 👍
