### ISSUE TITLE
Official CF/MR release

### ISSUE THREAD

**Issue by Madis0** [FlashyReese/sodium-extra-fabric#5]
I suggest having and maintaining an official Curseforge and/or Modrinth release. As far as I can see, [there already is one](https://www.curseforge.com/minecraft/mc-mods/sodium-extra-fabric), but as they say it was directly compiled from this (and not even a derivative fork), it doesn't give as much confidence that they will give any support or maintenance...

**Comment by FlashyReese** [comment]
Thank you for making me aware of this situation.

**Comment by FlashyReese** [comment]
[CurseForge](https://www.curseforge.com/minecraft/mc-mods/sodium-extra) and [Modrinth](https://modrinth.com/mod/sodium-extra)
