### ISSUE TITLE
Crash on Minecraft Initializing

### ISSUE THREAD

**Issue by ghost** [FlashyReese/sodium-extra-fabric#50]
I launched sodium 0.2.0 with sodium extra 0.3.2(dev) - 0.2.6(dev). 0.2.6 is stable(not crash)
[crash-2021-07-15_12.28.49-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/6821966/crash-2021-07-15_12.28.49-client.txt)

**Comment by FlashyReese** [comment]
Are you using the proper jar files for these versions? Can you provide a screenshot of your mods folder?

**Comment by ghost** [comment]
You can look at crash-reports to see my mods. So im used sodium 2.0  and
sodium extra 0.3.2. I tried different combinations of versions, but the
crash was still

пт, 16 июл. 2021 г. в 02:04, Yao Chung Hu ***@***.***>:

**Comment by FlashyReese** [comment]
Looks like you were using source jars
