### ISSUE TITLE
1.17 BSVSB Compatibility

### ISSUE THREAD

**Issue by Felix14-v2** [FlashyReese/sodium-extra-fabric#55]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.3

### Sodium version.

0.3.0 build 494

### What happened?

Sodium Video Settings in Better Sodium Video Settings Button mod (v2.0.0) does nothing when Sodium Extra installed.
Sodium v0.3.0 build 5 (release) is good.

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/6835520/latest.log)

**Comment by MenacingPerson** [comment]
Can confirm this bug.
