### ISSUE TITLE
Obsolete Sodium Version Included with Sodium Extra

### ISSUE THREAD

**Issue by jakey1995abc** [FlashyReese/sodium-extra-fabric#56]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.3

### Sodium version.

0.3.0

### What happened?

The latest version of Sodium Extra for Minecraft 1.17.1 bundles in an obsolete version of sodium with it, preventing players and modpack users from using the mod with the latest version of sodium due to crashing on startup. I know I can manually remove the mod myself to prevent a conflict but if I include sodium extra and sodium (latest modrinth version) in my modpack, it will not work for any users.

### Relevant logs

n/a

### Additional information

n/a

**Comment by FlashyReese** [comment]
The 0.3.3 does not bundle any version of Sodium 0.3.0, the only mod that is bundled is the `reeses-sodium-options-mc1.17.1-1.1.2.jar` via Jar In Jar. This release is explicitly marked compatible for only `0.3.0`. Be sure to remove any duplicated mods you have installed.

**Comment by Madis0** [comment]
You probably installed Sodium Extra through Curseforge Launcher - yes, that automatically downloads the 1.16.3 version of Sodium because Sodium Extra has Sodium as a dependency and Curseforge has 1.16.3 version as the latest.
The fix:

1. Install Sodium Extra via Curseforge Launcher
2. Remove old Sodium from mods folder
3. Add new Sodium to mods folder

**Comment by jakey1995abc** [comment]
> The 0.3.3 does not bundle any version of Sodium 0.3.0, the only mod that is bundled is the `reeses-sodium-options-mc1.17.1-1.1.2.jar` via Jar In Jar. This release is explicitly marked compatible for only `0.3.0`. Be sure to remove any duplicated mods you have installed.

I didn't install it. It literally came with Sodium Extra on CurseForge like I said. You most likely did the config for the curseforge upload incorrect, or the way curseforge reads the config has now changed since you last uploaded.

> You probably installed Sodium Extra through Curseforge Launcher - yes, that automatically downloads the 1.16.3 version of Sodium because Sodium Extra has Sodium as a dependency and Curseforge has 1.16.3 version as the latest.
> The fix:
> 
> 1. Install Sodium Extra via Curseforge Launcher
> 2. Remove old Sodium from mods folder
> 3. Add new Sodium to mods folder

But won't modpack users still get the old version of Sodium like I suggested?

**Comment by Madis0** [comment]
> But won't modpack users still get the old version of Sodium like I said?

Not if they check which Sodium is used and export it accordingly, I just [released a version](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files/3392479) of my modpack with correct Sodium and latest Sodium Extra so I can confirm it works. 

I'm not sure what FlashyReese should do here, the dependency is marked correctly, it is just a Curseforge bug that the launcher does not check which version to download.
