### ISSUE TITLE
Underwater fog is removed when fog settings are off, despite settings saying it is being exempted

### ISSUE THREAD

**Issue by foxdst** [FlashyReese/sodium-extra-fabric#57]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.3

### Sodium version.

0.3.0+build.5

### What happened?

As per title.
Issue also seen in the Nether, however I would prefer if the Nether fog was removed or togglable instead.

**Vanilla Fog**
![2021-07-18_17 31 58](https://user-images.githubusercontent.com/42083205/126056929-043e5c59-55c6-430b-b135-7eead36aa18c.png)

**Fog tuned to 33 (disabled)**
![2021-07-18_17 32 14](https://user-images.githubusercontent.com/42083205/126056935-04075a4e-1e2b-4d0c-a6ec-ed58771723c7.png)
![2021-07-18_17 32 16](https://user-images.githubusercontent.com/42083205/126056941-3b268ce6-ea2b-44e4-b61e-8f6065f76951.png)

### Relevant log.

[2021-07-18-7.log.gz](https://github.com/FlashyReese/sodium-extra-fabric/files/6835727/2021-07-18-7.log.gz)

**Comment by FlashyReese** [comment]
Yes, I will need to update the tooltips.

**Comment by filips123** [comment]
Can you make separate controls for air/terrain, nether, water and lava fogs?

**Comment by Tommeh1** [comment]
> Can you make separate controls for air/terrain, nether, water and lava fogs?

For more precise control like that you can use NoFog.

**Comment by Rajbir98** [comment]
what's the problem it's better that sodium extra can now control nether fog and water fog nice

**Comment by Madis0** [comment]
Perhaps Reese could cherrypick this implementation? https://github.com/capnkork/fog-control/blob/1.17/src/main/java/com/capnkork/fogcontrol/mixin/MixinBackgroundRenderer.java
License is MIT
