### ISSUE TITLE
Iris Shaders custom Sodium crashes client when opening Video Settings menu

### ISSUE THREAD

**Issue by foxdst** [FlashyReese/sodium-extra-fabric#58]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.3

### Sodium version.

0.3.0+IRIS1-rev7491e3a   +  Iris-mc1.17-1.1.0

### What happened?

Loading the Sodium extra mod alongside Iris + Custom Sodium for Iris Shaders crashes the client when trying to access the Video Settings menu. 

### Relevant log.

[2021-07-18-7.log.gz](https://github.com/FlashyReese/sodium-extra-fabric/files/6835734/2021-07-18-7.log.gz)

### Additional information.

**Crash Report:**

[crash-2021-07-18_17.46.50-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/6835735/crash-2021-07-18_17.46.50-client.txt)

**Comment by Apprisco** [comment]
This isn't an issue with Sodium extras, it's with latest iris sodium being heavily outdated. The recent versions are being worked on still for mem leaks, I can confirm that starline sodium works perfectly fine with sodium extras on the latest release.

**Comment by Rajbir98** [comment]
i have not enough crashes and it shows that the new gui of sodium extra is causing problems

**Comment by DragonEggBedrockBreaking** [comment]
Reeses-sodium-options (the new gui inbuilt in sodium extra) only works with the latest release version of sodium (or newer), and the equivalent for the iris fork of sodium. For regular sodium, make sure you're using the release version and not an older dev build, and for iris sodium, build the latest commit just to be safe.

**Comment by Apprisco** [comment]
For the iris sodium, I suggest using the latest versions(aka bleeding edge builds) if you are going to use latest versions of sodium extras. Starline sodium is compatible with iris sodium, and is even more bleeding edge.
Granted, remember that you won't get support for starline with iris.

**Comment by DioEgizio** [comment]
update to 1.1.1

**Comment by FlashyReese** [comment]
As stated in the previous comments, the version of Sodium that Iris uses is outdated. Extra mainly targets Sodium releases,

**Comment by DioEgizio** [comment]
> As stated in the previous comments, the version of Sodium that Iris uses is outdated. Extra mainly targets Sodium releases,

Not true, I tried on windows and it worked well

**Comment by Apprisco** [comment]
> > As stated in the previous comments, the version of Sodium that Iris uses is outdated. Extra mainly targets Sodium releases,
> 
> Not true, I tried on windows and it worked well

It was outdated, Iris recently published a new public version.
