### ISSUE TITLE
Hurtcam

### ISSUE THREAD

**Issue by llViiinyLll** [FlashyReese/sodium-extra-fabric#60]
Not sure why this feature was removed in 1.17 but it was a good addition to the mod for sodium. if I could ask for some transparency on why this addition was removed that would be great. I liked this feature because it removed alot of the annoyance of skeleton spam during combat.

**Comment by FlashyReese** [comment]
I have removed it and deemed it too "cheaty" as an sodium extra extension.

**Comment by llViiinyLll** [comment]
I suppose it could be deemed "Cheaty". thanks for letting me know.
