### ISSUE TITLE
Found conflicting mods: sodium-extra conflicts with {sodium @ [0.1.x || 0.2.0+IRIS_rev.400af47 || >=0.3.x]}

### ISSUE THREAD

**Issue by RainOfPain125** [FlashyReese/sodium-extra-fabric#61]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.16.5

### Sodium Extra version.

sodium-extra-0.3.2

### Sodium version.

sodium-fabric-mc1.16.3-0.1.0

### What happened?

On start with just Sodium and Extra gives
"Could not find required mod: sodium-extra requires {fabric @ [*]}
Creating Empty clause ?"
https://hastebin.com/gehivocure.js

On start with Sodium, Extra, and fabric-api-0.37.1+1.16 gives
"Found conflicting mods: sodium-extra conflicts with {sodium @ [0.1.x || 0.2.0+IRIS_rev.400af47 || >=0.3.x]}
Creating Empty clause ?"
https://hastebin.com/taxelaluni.js

I uhh, err... Yeah, no idea whats wrong.

### Relevant logs

n/a

### Additional information

n/a

**Comment by FlashyReese** [comment]
Install Fabric API

**Comment by RainOfPain125** [comment]
> Install Fabric API

The post clearly explains what error I get with FAPI installed.


> On start with Sodium, Extra, and fabric-api-0.37.1+1.16 gives
> "Found conflicting mods: sodium-extra conflicts with {sodium @ [0.1.x || 0.2.0+IRIS_rev.400af47 || >=0.3.x]}
> Creating Empty clause ?"
> https://hastebin.com/taxelaluni.js

**Comment by DragonEggBedrockBreaking** [comment]
> The post clearly explains what error I get with FAPI installed.

You are using an outdated version of sodium. Latest for 1.16 is 0.2.0, which is required for sodium extra on 1.16, but you have sodium 0.1.0.
