### ISSUE TITLE
Suggestion: Disabling block breaking particles

### ISSUE THREAD

**Issue by epic0421** [FlashyReese/sodium-extra-fabric#62]
I would really like to see a toggle for turning off block breaking particles in the particles menu. This setting can help those who struggle to see when instant mining and can help to reduce lag on lower end systems.

**Comment by DragonEggBedrockBreaking** [comment]
Tweakeroo has this feature btw

**Comment by epic0421** [comment]
> 
> 
> Tweakeroo has this feature btw

I am aware of this fact. It would just be nice to see this in Sodium Extras and would be fitting for a project like this.
