### ISSUE TITLE
What does prevent shaders do?

### ISSUE THREAD

**Issue by dewyi** [FlashyReese/sodium-extra-fabric#63]

**Comment by Rajbir98** [comment]
i dont know it doesnt do anything i thing i used iris with prevent shaders enable but no response

**Comment by Rajbir98** [comment]
and i dont know what no overlay does in older versions of sodium extra

**Comment by FlashyReese** [comment]
Prevent Shaders - prevents vanilla shaders from enabling.
No Overlay - Removes the overlay presented when submerged in a fluid.
