### ISSUE TITLE
FPS counter should be disabled by default

### ISSUE THREAD

**Issue by emielderckx** [FlashyReese/sodium-extra-fabric#64]
The fps and coords thingy should really be disabled by default <3

**Comment by K0-RR** [comment]
Also mentioned here https://github.com/FlashyReese/sodium-extra-fabric/issues/44#issuecomment-883614473.

**Comment by FlashyReese** [comment]
Closed with https://github.com/FlashyReese/sodium-extra-fabric/commit/5a4920dddee3b23ab2371a0710e84b89d9feb48e
