### ISSUE TITLE
Minecraft crash when open with sodium extra

### ISSUE THREAD

**Issue by dinouse** [FlashyReese/sodium-extra-fabric#65]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.17

### Sodium Extra version.

0.3.3

### Sodium version.

0.3.0+Build 5

### What happened?

I open Minecraft and it will crash. Im on Mac OS 11. My Minecraft will work again without Sodium Extra but i really need your mods. Love it!!

### Relevant logs

[2021-07-31-2.log.gz](https://github.com/FlashyReese/sodium-extra-fabric/files/6908998/2021-07-31-2.log.gz)

### Additional information

hydrogen-fabric-mc1.17.1-0.3
lithium-fabric-mc1.17.1-0.7.3
sodium-extra-mc1.17.1-0.3.3
sodium-fabric-mc1.17.1-0.3.0+build.5

**Comment by FlashyReese** [comment]
The log does not contain extra as a mod.

**Comment by dinouse** [comment]
im sorry, maybe this. 
[2021-07-31-4.log.gz](https://github.com/FlashyReese/sodium-extra-fabric/files/6911424/2021-07-31-4.log.gz)

**Comment by necrophili** [comment]
Same here, MC wouldnt launch with those 2 versions of sodium and sodium extras

**Comment by FlashyReese** [comment]
> im sorry, maybe this.
> [2021-07-31-4.log.gz](https://github.com/FlashyReese/sodium-extra-fabric/files/6911424/2021-07-31-4.log.gz)

This log also doesn't not contain extra. Please try with only Sodium and Extra to verify if it occurs.

**Comment by dinouse** [comment]
Sorry again, I put 3 logs it has same time. Just in case.
[2021-07-31-4.log.gz](https://github.com/FlashyReese/sodium-extra-fabric/files/6925555/2021-07-31-4.log.gz)
[2021-07-31-5.log.gz](https://github.com/FlashyReese/sodium-extra-fabric/files/6925556/2021-07-31-5.log.gz)
[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/6925557/latest.log)

This is Minecraft Sodium and Sodium Extra only mods.

**Comment by FlashyReese** [comment]
I forgot to request you also install the Fabric API. Sorry about that.

**Comment by dinouse** [comment]
Its ok, I got time no worries. Here the logs.
[2021-08-04-1.log.gz](https://github.com/FlashyReese/sodium-extra-fabric/files/6925824/2021-08-04-1.log.gz)
[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/6925825/latest.log)

Sodium
Sodium Extra
Fabric API

**Comment by FlashyReese** [comment]
Seems like you are running Fabric API for 1.17.1-rc on 1.17.1, use this one https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3398557

**Comment by dinouse** [comment]
Actually I'm not running the RC version of Fabric API instead of the top download on curseforge.
By the way, I got it work by playing it on 1.17.1 even with all other mods. All the crash was on 1.17 actually. Maybe Sodium Extra not working on 1.17 Mac(I got it work on linux).

Thank you for your help!! Love your mods
