### ISSUE TITLE
[Feature Request] Foliage mipmap similar to optifine

### ISSUE THREAD

**Issue by Soham52** [FlashyReese/sodium-extra-fabric#68]
Adding the foliage mipmap would a great feature to add because it greatly improves the quality of grass that is far away.

 Currently no other mod except optifabric offer this feature on fabric.

**Comment by Rajbir98** [comment]
You requested this same thing in lamdabettergrass

**Comment by Soham52** [comment]
Yes I did, so?

> You requested this same thing in lamdabettergrass

**Comment by TheMadHau5** [comment]
> Yes I did, so?
> 
> > You requested this same thing in lamdabettergrass

so wait for it to be implemented there lol
