### ISSUE TITLE
Crashes with Boosted Brightness - Latest Actions

### ISSUE THREAD

**Issue by Apprisco** [FlashyReese/sodium-extra-fabric#69]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.3 latest actions

### Sodium version.

sodium-fabric-mc1.17.1-0.3.0+IRIS2-build.117

### What happened?

Opened video settings, immediate crash

### Relevant logs

https://paste.gg/p/anonymous/c851085510a74669b103c880de6f41e7

Edit:
Proven to be a incompatibility with Boosted Brightness.

**Comment by Apprisco** [comment]
![image](https://user-images.githubusercontent.com/34324909/129446462-789c734e-ee7c-4c03-a33e-88a42e734baf.png)
All of the above immediately crashes.

**Comment by FlashyReese** [comment]
Do you have a full crash log, current log isn't giving me anything useful to work off of.

**Comment by FlashyReese** [comment]
Seems to work fine on my end 
![image](https://user-images.githubusercontent.com/30311066/129464593-f126adf9-cff6-44da-b160-8657e46449bf.png)
![image](https://user-images.githubusercontent.com/30311066/129464606-492d62f3-fd57-4322-b150-0a075981d0c2.png)

Current list of mods:
![image](https://user-images.githubusercontent.com/30311066/129464601-e3cfaf78-bff4-4ffa-ae8d-12df26f9fe24.png)

**Comment by FlashyReese** [comment]
Just make sure your configuration isn't corrupted.

**Comment by Apprisco** [comment]
https://paste.gg/p/anonymous/f901cce98cb142ed98d0e6aaf065ffba
Still crashes, nothing is corrupted. Works fine with the fix before spyglass.

**Comment by Apprisco** [comment]
Clearing the config doesn't work either, removed the sodium-extras-options and same behavior.

**Comment by Apprisco** [comment]
> Just make sure your configuration isn't corrupted.

Tried on a completely fresh install, still nothing.
Probably because it's not compiled off of the latest sodium dev versions.

**Comment by FlashyReese** [comment]
> > Just make sure your configuration isn't corrupted.
> 
> Tried on a completely fresh install, still nothing.
> Probably because it's not compiled off of the latest sodium dev versions.

Unlikely, we are both using the exact same versions. Yet this only occurs to your instance. As far as crash log goes nothing points directly at our mod. Will investigate further this weekend.

**Comment by Apprisco** [comment]
> > > Just make sure your configuration isn't corrupted.
> > 
> > 
> > Tried on a completely fresh install, still nothing.
> > Probably because it's not compiled off of the latest sodium dev versions.
> 
> Unlikely, we are both using the exact same versions. Yet this only occurs to your instance. As far as crash log goes nothing points directly at our mod. Will investigate further this weekend.

So are you using the latest dev sodium versions?
I'm using Starline's sodium, which works fine with starline and itself:
https://github.com/HyperCubeMC/sodium-fabric/tree/1.17-starline

**Comment by FlashyReese** [comment]
Yes I'm using starline in said screenshots above. Build number is also listed there.

**Comment by Apprisco** [comment]
> > > Just make sure your configuration isn't corrupted.
> > 
> > 
> > Tried on a completely fresh install, still nothing.
> > Probably because it's not compiled off of the latest sodium dev versions.
> 
> Unlikely, we are both using the exact same versions. Yet this only occurs to your instance. As far as crash log goes nothing points directly at our mod. Will investigate further this weekend.

If removing your mod or downgrading it fixes it, chances are it's your mod.
Build #59 works perfectly, anything beyond that immediately crashes when opening video settings.
What was changed that could cause this?

**Comment by FlashyReese** [comment]
> > > > Just make sure your configuration isn't corrupted.
> > > 
> > > 
> > > Tried on a completely fresh install, still nothing.
> > > Probably because it's not compiled off of the latest sodium dev versions.
> > 
> > Unlikely, we are both using the exact same versions. Yet this only occurs to your instance. As far as crash log goes nothing points directly at our mod. Will investigate further this weekend.
> 
> If removing your mod or downgrading it fixes it, chances are it's your mod.
> Build #59 works perfectly, anything beyond that immediately crashes when opening video settings.
> What was changed that could cause this?

Can you upload the mods in a zip? I have no way of reproducing this whatsoever.

**Comment by Apprisco** [comment]
[sodium-fabric-mc1.17.1-0.3.0+IRIS2-build.118.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/7017074/sodium-fabric-mc1.17.1-0.3.0%2BIRIS2-build.118.zip)

**Comment by Apprisco** [comment]
Huh, issue went away when I removed all mods but those again, which is odd.
Enabling the mods brought it back, so for some odd reason, it now seems to be a mod incompatibility.
(odd bec it was crashing on a fresh installation)
So I decided to become thanos and do a binary search, and I think I found the mod incompat.
It seems to be incompatible with Boosted Brightness.

**Comment by srnyx** [comment]
> It seems to be incompatible with Boosted Brightness.

Can confirm. Using Boosted Brightness and when opening Video Settings it crashes. Disabling Sodium Extra (and I assume disabling Boosted Brightness would work too) makes it work agin.

**Comment by Eatham532** [comment]
> It seems to be incompatible with Boosted Brightness.

Can also confirm that using boosted Brightness makes minecraft crash when opening video settings. Its such a shame because sodium extra and boosted brightness are both mods that I want to use at the same time. Please fix this.

**Comment by srnyx** [comment]
> Its such a shame because sodium extra and boosted brightness are both mods that I want to use at the same time. Please fix this.

This Pull Request from Boosted Brightness' GitHub works for me: https://github.com/adamviola/BoostedBrightness/pull/18
