### ISSUE TITLE
Modified settings do not save (mod incompatibility issue)

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [FlashyReese/sodium-extra-fabric#7]
When this mod is used with [Sodium Extras](https://github.com/eatmyvenom/sodium-extras) (a mod similar to this which adds a few nice settings to the sodium settings menu as well) and [MaliLib](https://github.com/maruohon/malilib) (a mod that is required for mods like Tweakeroo, Litematica and MiniHud to work), modified settings are not saved after closing and relaunching the game (they are saved after exiting and re-joining a world tho). I have reproduced this bug with both sodium 0.1.0 (stable branch) and sodium 0.1.1 (1.16.x/next branch).

**Comment by FlashyReese** [comment]
Look like Sodium Extras is modifying the same config file as us. 

https://github.com/eatmyvenom/sodium-extras/blob/897d394e4c94a9e0c4d9737450c49d5a459aabf6/src/main/java/io/github/eatmyvenom/sodiumExtras/SodiumExtra.java#L21

**Comment by DragonEggBedrockBreaking** [comment]
> Look like Sodium Extras is modifying the same config file as us.
> 
> https://github.com/eatmyvenom/sodium-extras/blob/897d394e4c94a9e0c4d9737450c49d5a459aabf6/src/main/java/io/github/eatmyvenom/sodiumExtras/SodiumExtra.java#L21

I opened an issue report on Sodium Extras' GitHub page, so maybe also explain there? I don't know java and have access to neither repository, so there's very little I can do.

**Comment by FlashyReese** [comment]
Optionally you can modify the config name at said line and compile yourself, they don't have an official release so I shouldn't be modifying my config file name for something that isn't released.

**Comment by DragonEggBedrockBreaking** [comment]
> they don't have an official release so I should been modifying my config file name for something that isn't released.

https://github.com/eatmyvenom/sodium-extras/releases/tag/0.1.0

> Optionally you can modify the config name at said line and compile yourself

ok, i can do that

**Comment by DragonEggBedrockBreaking** [comment]
That worked, will close this now. https://github.com/eatmyvenom/sodium-extras/pull/4
