### ISSUE TITLE
Cant see any options

### ISSUE THREAD

**Issue by lochlanmcelroy** [FlashyReese/sodium-extra-fabric#71]
<img width="871" alt="Screen Shot 2021-08-21 at 9 36 10 AM" src="https://user-images.githubusercontent.com/85311595/130325225-f3b82290-25f4-4e06-a53b-1d5e57ee3b3e.png">

I'm able to select options, but I cant see any of them unless they are hovered over, on which it displays what the option does.

**Comment by K0-RR** [comment]
Why didn't you use the template? You also failed to provide any needed details.

**Comment by FlashyReese** [comment]
This is an duplicated issue with retina displays. You can either use the [development build](https://github.com/FlashyReese/sodium-extra-fabric/suites/3556888105/artifacts/85328520) or you can use retiNO with the current version you have.

**Comment by celakk1** [comment]
> This is an duplicated issue with retina displays. You can either use the [development build](https://github.com/FlashyReese/sodium-extra-fabric/suites/3556888105/artifacts/85328520) or you can use retiNO with the current version you have.

its nice you send development build for 1.17.1 but i already have it fixed, but 1.16.5 is same like this guy, no options, im on mac.
if you can, send 1.16.5 development build of sodium extra.

**Comment by FlashyReese** [comment]
> > This is an duplicated issue with retina displays. You can either use the [development build](https://github.com/FlashyReese/sodium-extra-fabric/suites/3556888105/artifacts/85328520) or you can use retiNO with the current version you have.
> 
> its nice you send development build for 1.17.1 but i already have it fixed, but 1.16.5 is same like this guy, no options, im on mac.
> if you can, send 1.16.5 development build of sodium extra.

You should be able to workaround this with retiNO
