### ISSUE TITLE
UI going out of the screen / Resolution slider issue

### ISSUE THREAD

**Issue by jojos38** [FlashyReese/sodium-extra-fabric#74]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.4

### Sodium version.

0.3.0

### What happened?

On the latest version of Sodium Extra I encounter two bugs:
- The particles tab is going outside of the game window and the options at the bottom are unreachable unless I resize the window
- The resolution slider shows a number instead of showing the resolution if we keep the mouse on it

https://youtu.be/CSHWIunsgjI

(Nothing related but also I really preferred the old UI style with the buttons on the left, however the UI looks perfect now with Iris this is pretty cool)

### Relevant log.

Not needed

### Additional information.

Mods list can be seen in the video, removing them doesn't fix the issue

**Comment by K0-RR** [comment]
@jojos38 One of the changes in v0.3.4 is "Unbundle Reese's Sodium Options from Extra" which is required for:
- Scrollable pages (Sodium Extra adds tabs that may overextend so this helps)
- Scrollable sliders - this means you can change the value while hovering over them and scrolling

I'm not sure if the scrollable pages feature can help in your case but it's worth trying.

**Comment by jojos38** [comment]
> @jojos38 One of the changes in v0.3.4 is "Unbundle Reese's Sodium Options from Extra" which is required for:
> 
> * Scrollable pages (Sodium Extra adds tabs that may overextend so this helps)
> * Scrollable sliders - this means you can change the value while hovering over them and scrolling
> 
> I'm not sure if the scrollable pages feature can help in your case but it's worth trying.

Hey, thanks for your reply
It doesn't fix the resolution slider but it does fix the issues of elements going out of the screen, but shouldn't be this implemented by default into the mod? (At least the scrollable menus)

**Comment by FlashyReese** [comment]
Jelly made the slider like that intentionally. As for the pages over extending, I have unbundle Reese's Sodium Options because some people don't like the layout. You can still get it on CurseForge or Modrinth.

**Comment by jojos38** [comment]
> Jelly made the slider like that intentionally. As for the pages over extending, I have unbundle Reese's Sodium Options because some people don't like the layout. You can still get it on CurseForge or Modrinth.

Thank you! But is there a way to fix the page over extending without that addon? (Or is it planned)

**Comment by FlashyReese** [comment]
> Thank you! But is there a way to fix the page over extending without that addon? (Or is it planned)

Nope, I don't plan to replace entire user interface as it doesn't really fit this mod. Since Sodium still lacks a GUI API. I don't want to implement such change that may break every time with Sodium itself or other mods such as Iris.

**Comment by jojos38** [comment]
Alright, thanks for your time
