### ISSUE TITLE
Sodium Extra Bundled With Wrong Version Of Sodium

### ISSUE THREAD

**Issue by jakey1995abc** [FlashyReese/sodium-extra-fabric#81]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.4

### Sodium version.

0.1.0

### What happened?

I am trying to include Sodium Extra in a CurseForge modpack along with the latest version of Sodium (0.3.2) but for some reason every time I add Sodium Extra to my modpack it also installs a very old and incompatible version of Sodium. Is there anything that can be done to resolve this and will deleting the outdated version of sodium on my end fix the issue for users of my modpack, or will it also download the outdated version for them to?

### Relevant log.

n/a

**Comment by K0-RR** [comment]
This is not associated with Sodium Extra as this mod doesn't bundle Sodium in any way.
Curseforge launcher downloads all dependencies for you but the latest version of Sodium available on the CurseForge is 0.1.0 and that's because Jelly has trouble accessing her account. This means you can't add Sodium 0.3.2 to your modpack afaik.

**Comment by jakey1995abc** [comment]
> This is not associated with Sodium Extra as this mod doesn't bundle Sodium in any way.
> Curseforge launcher downloads all dependencies for you but the latest version of Sodium available on the CurseForge is 0.1.0 and that's because Jelly has trouble accessing her account. This means you can't add Sodium 0.3.2 to your modpack afaik.

Afaik the dependencies get selected on your end, and the purpose of dependencies is for curseforge to auto download any required mods when added to modpacks. I'd personally recommend removing Sodium as a listed dependency for now (if what I said above is true) until the issue is fixed, otherwise you won't benefit from people adding your mod to their modpacks and it will just cause issues over anything else.

**Comment by K0-RR** [comment]
First, I'm just a stranger explaining what happened.

> the purpose of dependencies is for curseforge to auto download any required mods when added to modpacks

That's what I said.

> I'd personally recommend removing Sodium as a listed dependency for now

This would not change much - it would fix " it also installs a very old and incompatible version of Sodium" but you can't just add a mod manually to the modpack - CF will remove it or sth - so until Jelly uploads a newer Sodium version to the CurseForge you won't have anything Sodium related in your modpack.

**Comment by FlashyReese** [comment]
To further add to the previous comment, it would still causes issues after removing since fabric loader will ask for Sodium.

Unfortunately there is nothing I can do to fix this until Jelly updates it on curseforge.

**Comment by Disguys** [comment]
@jakey1995abc JellySquid it no longer updates Sodium on CurseForge, since it has abandoned support for this mod on this platform and Forge. He updates it exclusively on the Modrinth website & GitHub

**Comment by jakey1995abc** [comment]
> To further add to the previous comment, it would still causes issues after removing since fabric loader will ask for Sodium.
> 
> Unfortunately there is nothing I can do to fix this until Jelly updates it on curseforge.

This is not true though. Modpack creators can include mods in their modpack even if they are hosted outside of curseforge, so it should completely fix the issue for modpack creators. Creators will still have to manually add the right version of sodium to their modpack, but without the dependency listing it won't break the modpacks for all users who want your mod in it. It's either this or modpack creators will be forced to also manually install Sodium Extra to their modpacks, meaning you will receive 0 downloads from modpack users.

**Comment by jakey1995abc** [comment]
If anything what I said above is incorrect or has changed, feel free to correct me, but afaik from my experience this is the way the service works

**Comment by FlashyReese** [comment]
> This is not true though. Modpack creators can include mods in their modpack even if they are hosted outside of curseforge, so it should completely fix the issue for modpack creators. Creators will still have to manually add the right version of sodium to their modpack, but without the dependency listing it won't break the modpacks for all users who want your mod in it. It's either this or modpack creators will be forced to also manually install Sodium Extra to their modpacks, meaning you will receive 0 downloads from modpack users.

I'm not aware of modpack being able to include mods outside of CurseForge. Perhaps I can do what you've suggested previously.

**Comment by FlashyReese** [comment]
I've removed them as a dependency(only for 1.17 releases) for the time being, let me know if this solves your issue.
