### ISSUE TITLE
language .json doesn't work on reduce_resolution_on_mac

### ISSUE THREAD

**Issue by amias1024** [FlashyReese/sodium-extra-fabric#82]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.4

### Sodium version.

0.3.2+b7

### What happened?

Hi, I am not 100% fluent in English.
I translate the language .json file to my own language:
All works except these two:
  "sodium-extra.option.reduce_resolution_on_mac": "",
  "sodium-extra.option.reduce_resolution_on_mac.tooltip": ""

### Relevant log.

no

**Comment by FlashyReese** [comment]
Seems to work just fine, can you verify this just to be sure?

**Comment by amias1024** [comment]
I'm so sorry for that I didn't know how to change language correctly before. Thank you for your response.
