### ISSUE TITLE
Incompatibility with Boosted Brightness

### ISSUE THREAD

**Issue by Alucaius** [FlashyReese/sodium-extra-fabric#85]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.4

### Sodium version.

0.3.2 Build 7

### What happened?

I am experiencing a crash whenever I click the Video Settings option. In other issues I have heard that using Iris' Sodium would cause this but I am still getting the same crash when using just Sodium.

### Relevant logs

[crash-2021-09-22_17.52.04-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/7211729/crash-2021-09-22_17.52.04-client.txt)

### Additional information

Here's my current list of mods if it's any help:
![image](https://user-images.githubusercontent.com/74951027/134367721-23882e2b-acc4-43e6-97bd-002b0b8992f7.png)

**Comment by FlashyReese** [comment]
Issue with Boosted Brightness, you can try a PR for it. https://github.com/FlashyReese/sodium-extra-fabric/issues/69#issuecomment-919421576
