### ISSUE TITLE
Incompatible with Essential.gg

### ISSUE THREAD

**Issue by Snapperito** [FlashyReese/sodium-extra-fabric#89]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.5

### Sodium version.

0.3.2

### What happened?

When launching sodium extra with [Essential](https://essential.gg) the game doesn't launch, and immediately crases. 

### Relevant logs

https://hastebin.com/cadumuboha.log

**Comment by FlashyReese** [comment]
I can't seem to replicate the issue 
![image](https://user-images.githubusercontent.com/30311066/138376021-a8cbbdd7-ef23-4c0b-ae68-aa6b8cbbb6ad.png)

**Comment by ssolom327-maker** [comment]
https://github.com/FlashyReese/sodium-extra/issues/new/choose
