### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [FlashyReese/sodium-extra-fabric#9]
### Any comments below that suggest to add or remove features will likely result in this comment being edited. If you want to implement the features, read this comment rather than the comments below. If you want justification for the features or want to suggest a change, comment below/read the below comments and I will respond as quickly as I can.

---

- More toggles in 'animations' tab
  - [x] Toggle for disabling block animations, because I swill want lava and water animations.
  - [ ] Toggle in for end portal and gateway animation.

- More particles to make toggleable:
  - [x] Villagers (happy, in love, etc. all under one toggle)
  - [x] Bone Meal (including composters)
  - [x] Dripping Particles (for water, lava, crying obsidian, etc. all under one toggle)
  - [x] Environment Particles (e.g. ash)

- New rendering tab (thanks to @Alejandro-Sosa) which contains toggles for rendering:
  - [x] Armour Stands
  - [x] Item Frames
  - [x] Move fog, light update and paintings toggles to this category

- Other stuff to add to 'extras':
  - [x] Cloud height slider (suggested by @Celled on discord)

**Comment by DragonEggBedrockBreaking** [comment]
I didn't include the checkmarks for when a feature is added (so that GitHub keeps track) because you may not want to include all features, but I can edit my comment to remove features you don't want to add and then I can add GitHub's feature tracking system.

**Comment by FlashyReese** [comment]
Perhaps, I'm quite busy these past few days. I don't really have much time to work on mods. It will depend on my schedule and free time and will to work on them.

**Comment by DragonEggBedrockBreaking** [comment]
> Perhaps, I'm quite busy these past few days. I don't really have much time to work on mods. It will depend on my schedule and free time and will to work on them.

Ok, that's fine.

**Comment by Madis0** [comment]
> Ideas for animations to make toggleable (there are more, but not many):
> 
> * Sea Lanterns
> * Magma Blocks

I don't really see a reason to include these individual blocks specifically, other than the fact that these are one of the few blocks in vanilla that are animated at all. Perhaps a "other animations" toggle, that could be compatible with resource packs and future vanilla items.

> Other:
> 
> * New toggle for not rendering item in offhand
>   (Ideas for this could simply be a single option in 'extra', or could be an entire tab which allows you to disable common items, e.g. food, fireworks and totems, with a general offhand rendering toggle at the top, just like animations, particles and detail)

Try [ShieldDistruptor](https://www.curseforge.com/minecraft/mc-mods/shielddisruptor), which does let you disable common items.

**Comment by DragonEggBedrockBreaking** [comment]
> I don't really see a reason to include these individual blocks specifically, other than the fact that these are one of the few blocks in vanilla that are animated at all. Perhaps a "other animations" toggle, that could be compatible with resource packs and future vanilla items.

Edited the animations part of my comment.

**Comment by DragonEggBedrockBreaking** [comment]
Edited original comment to include new Fog tab.
Edited original comment to clean up formatting.

> Try [ShieldDistruptor](https://www.curseforge.com/minecraft/mc-mods/shielddisruptor), which does let you disable common items.

imo item whitelist/blacklist doesn't really fit in to Sodium Extras, so I edited to just include a general toggle for offhand rendering

**Comment by ghost** [comment]
Options for rendering armorstands and itemframes would be a very nice addition ^^

**Comment by FlashyReese** [comment]
Perhaps :P

**Comment by DragonEggBedrockBreaking** [comment]
> Options for rendering armorstands and itemframes would be a very nice addition ^^

Added to my original comment, and I moved my offhand rendering idea to that category. I also suggested to move disabling shaders, light updates and fog to the new 'rendering' category.

**Comment by FlashyReese** [comment]
I don't think making a new tab is the right way to go at the moment, since Sodium still doesn't an options API and I will over extend the default launch window size with new tabs. 
There are 2 ways I can do this. 
1. I can wait for Sodium's GUI rework alongside options API
2. I can release https://github.com/FlashyReese/sodium-fabric/commit/df3f8af66a34d92f6e2d3e9d6d65c7178623c40a commit as a extension mod like Sodium Extra for the time being while waiting for option 1. For anyone that would like to try said commit you can [click here](https://github.com/FlashyReese/sodium-fabric/actions/runs/583960210).

I will be looking over some of these suggestions this weekend and probably deciding what I think is suitable for Sodium Extra.

**Comment by DragonEggBedrockBreaking** [comment]
I understand.

**Comment by DragonEggBedrockBreaking** [comment]
Updated original comment to include types of block animations that me and FlashyReese discussed on discord.

**Comment by ghost** [comment]
Some other suggestions:
- Beacon Beam toggle
- Joining world screen toggle
- Toggles for bossbar and scoreboard; actionbar and title messages

**Comment by DragonEggBedrockBreaking** [comment]
> Some other suggestions:
> 
> - Beacon Beam toggle
> 
> - Joining world screen toggle
> 
> - Toggles for bossbar and scoreboard; actionbar and title messages

I was actually gonna suggest bossbar toggle. I added the beacon beam, bossbar and scoreboard toggles, but can you explain further what you mean by joining world screen? If you mean the screen with the square and percentage, that is when the world is generating, and is not just some random optional thing (as far as I know)...

**Comment by ghost** [comment]
> > Some other suggestions:
> > 
> > * Beacon Beam toggle
> > * Joining world screen toggle
> > * Toggles for bossbar and scoreboard; actionbar and title messages
> 
> I was actually gonna suggest bossbar toggle. I added the beacon beam, bossbar and scoreboard toggles, but can you explain further what you mean by joining world screen? If you mean the screen with the square and percentage, that is when the world is generating, and is not just some random optional thing (as far as I know)...

When joining another world it shows the overlay not sure how to describe it but when going thru a portal and the transition. Hope my explanation makes sense.

**Comment by DragonEggBedrockBreaking** [comment]
> When joining another world it shows the overlay not sure how to describe it but when going thru a portal and the transition. Hope my explanation makes sense.

You mean the loading screen when going through a portal? There is a mod that removes it called 'immersive portals', but that mod does a lot more and requires a lot of code to do it. Doesn't feel to me in the scope of sodium extra.

**Comment by ghost** [comment]
> > When joining another world it shows the overlay not sure how to describe it but when going thru a portal and the transition. Hope my explanation makes sense.
> 
> You mean the loading screen when going through a portal? There is a mod that removes it called 'immersive portals', but that mod does a lot more and requires a lot of code to do it. Doesn't feel to me in the scope of sodium extra.

Not what i meant, whenever switching world there is a overlay in between saying "joining world". Maybe that is a requirement tho for the client i could be wrong and removing it would break things.

**Comment by DragonEggBedrockBreaking** [comment]
> Not what i meant, whenever switching world there is a overlay in between saying "joining world". Maybe that is a requirement tho for the client i could be wrong and removing it would break things.

Could you screen record and show, I'm really not understanding... @FlashyReese Do you understand? Idk whether to add it to the main feature list until I understand fully what is meant...

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=UeB2hKK07zA

**Comment by DragonEggBedrockBreaking** [comment]
> https://www.youtube.com/watch?v=UeB2hKK07zA

I don't really think this fits in with my suggestions, so I created a new issue report for that.

**Comment by DragonEggBedrockBreaking** [comment]
Edited original comment to add a checklist which GitHub keeps track of.

**Comment by DragonEggBedrockBreaking** [comment]
Btw, since you added one of the options, should this be maked 'in progress' in the 0.3.0 milestone?

**Comment by DragonEggBedrockBreaking** [comment]
Updated to include a 'fixes' section (section of the comment, not a new tab), and added iron bar z-fighting to that section.

**Comment by DragonEggBedrockBreaking** [comment]
### Major original comment refactor, to fit in with new ideas, and new changes

- removed fog tab suggestion
- removed block breaking animations toggle suggestion
- removed beacon beam toggle suggestion
- added end portal animation toggle suggestion
- moved some more stuff to the 'rendering' tab suggestion
- removed iron bar z-fighting toggle suggestion. 
- new overlays tab suggestion

**Comment by DragonEggBedrockBreaking** [comment]
Removed overlays tab suggestion, as it is pretty useless when you think about it

**Comment by DragonEggBedrockBreaking** [comment]
Redid formatting again

**Comment by DragonEggBedrockBreaking** [comment]
Redid formatting once again, because I can't seem to settle

**Comment by FlashyReese** [comment]
> Toggle in for end portal and gateway animation.

Apparently not an animation block like the nether portal. https://minecraft.fandom.com/wiki/Animation#Animated_textures

**Comment by DragonEggBedrockBreaking** [comment]
> Apparently not an animation block like the nether portal. https://minecraft.fandom.com/wiki/Animation#Animated_textures

Ok

**Comment by DragonEggBedrockBreaking** [comment]
> Apparently not an animation block like the nether portal. https://minecraft.fandom.com/wiki/Animation#Animated_textures

Is it still possible to toggle, or should I remove it from the list?

**Comment by DragonEggBedrockBreaking** [comment]
Added cloud height toggle to the list

**Comment by Felix14-v2** [comment]
It would be great to see an option to toggle ambient nether particles, such as ash. They are really strong load graphics card (especially in basalt deltas).

**Comment by DragonEggBedrockBreaking** [comment]
> It would be great to see an option to toggle ambient nether particles, such as ash. They are really strong load graphics card (especially in basalt deltas).

Added

**Comment by FlashyReese** [comment]
Closed with https://github.com/FlashyReese/sodium-extra-fabric/commit/55457139d7fe7f67d57d2e8eb056ecf7ea3836a0
