### ISSUE TITLE
[Feature Request] Option to toggle Nether ambient particles 

### ISSUE THREAD

**Issue by Abbanon** [FlashyReese/sodium-extra-fabric#90]
As the title says, it would be nice to have a toggle for the ambient particles in the Nether dimension biomes. 
For example: Ash particles in Basalt Deltas, spore particles in Crimson/Warped Forests, etc.
They can be pretty taxing on performance for lower-end hardware.

**Comment by FlashyReese** [comment]
Available in release `0.4.6`. [List of particles](https://minecraft.fandom.com/wiki/Particles)
