### ISSUE TITLE
Incompatible with Custom Fog

### ISSUE THREAD

**Issue by Snowiez** [FlashyReese/sodium-extra-fabric#92]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.2

### Sodium version.

0.3.5

### What happened?

Fog is overridden by sodium extra, even when Vanilla or Off is set.

### Relevant log.

https://paste.ee/p/d2L9r

**Comment by Indiglowr** [comment]
I think a bug i had is related to this, it was overwriting lava fog so even with just this, reese's options, origins and sodium installed fire res potions weren't altering the lava fog. Just nothing but solid red. removing this and reese's options fixed the issue.

**Comment by aeniii** [comment]
I noticed the same. Sodium extra overwrites the fog settings and the lava visibility from the tweakeroo mod doesn`t work anymore. I`m on version 1.18.
