### ISSUE TITLE
Cannot Use Shader While using Iris With Sodium and Extra Sodium

### ISSUE THREAD

**Issue by Zyno1x** [FlashyReese/sodium-extra-fabric#99]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17.1

### Sodium Extra version.

0.3.5

### Sodium version.

0.3.2+IRIS2-build.9

### What happened?

Can't Access Shaders Mod In Video Settings GUI When Using Sodium With Iris and Extra Sodium
The New Sections in Sodium Extra Move The Shaders Section to The Edge of The Screen and it Cannot Be Accessed

### Relevant log.

[https://paste.ee/p/PsyFe](url)

**Comment by FlashyReese** [comment]
Solution 1: Use [Reese's Sodium Options](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
Solution 2: Use GUI Scale 2 :^)
Solution 3: Wait for CaffeineMC to change the layout on 1.18 possibly?

There is nothing I can do as the layout was designed that way.
